"""Salesforce admin handoff: target capabilities, coverage, controls and proof."""
import html
E=lambda value:html.escape(str(value),quote=True)
OBJECT_ROWS=[
 ('Sales','C R E','C R E','C R E','Activity¹','R','Owned records, approved territory coverage and explicit account/deal-team shares.'),
 ('Sales Engineering','R','R E','C R E','Activity¹','C R E','Assigned technical coverage; technical Opportunity fields and assigned enhancement/deployment work only.'),
 ('Partner overlays','R','R E','R E','Activity¹','R','Active partner AND approved geography/territory match; direct-pipeline visibility needs an explicit grant.'),
 ('Sales Ops','C R E','C R E','C R E','Activity¹','R E','Approved operating region or named account list; correction actions separately granted. Opportunities remain User-owned.'),
 ('Partner Ops','C R E','R E','C R E','Activity¹','R','Partner master data and associated deals within coverage; commercial Opportunity fields remain read-only.'),
 ('RevOps','C R E','C R E','C R E','Activity¹','R E','Explicit process-support sharing remit; job title alone does not grant every record or Setup access.'),
 ('Finance','R','R','R','Activity¹','R','Assigned financial review context. Order edits and commercial approvals use separate entitlements.'),
 ('Product','R','R','R','Activity¹','C R E','Assigned enhancement Cases and the related customer/deal context; no deployment-Case edit by default.'),
 ('GSS','R','R','C R E','Activity¹','C R E','Assigned deployment/support Cases and related customer/deal context; no booked-sales edits.')]
ROLE_DEFS=[
 ('Sales','Owns qualification, commercial progression and customer actions.'),('Sales Engineering','Owns technical evaluation, configuration, POCs and technical risk.'),('Partner overlays','Internal partner managers and technical overlays within assigned partner and regional coverage.'),('Sales Ops','Maintains sales routing, coverage operations and approved data corrections.'),('Partner Ops','Maintains partner master data, partner coverage and delegated registration operations.'),('RevOps','Owns process design, attribution governance and the coverage-model specification.'),('Finance','Owns delegated commercial review and financial reconciliation.'),('Product','Owns enhancement triage, disposition and approved product responses.'),('GSS','Owns deployment/support execution and Case-based value realization.')]
SYSTEM_ROWS=[
 ('Sales','Run / create','Separate','—','—','—','—'),('Sales Engineering','Run / create','Separate','—','—','—','—'),('Partner overlays','Run / create','Separate','—','—','—','—'),('Sales Ops','Run / create','Separate','Separate','Separate','—','—'),('Partner Ops','Run / create','Separate','Separate','Separate','—','—'),('RevOps','Run / create','Separate','Separate','Separate','Separate','—'),('Finance','Run / create','Separate','Separate','Separate','—','—'),('Product','Run','Separate','—','—','—','—'),('GSS','Run / create','Separate','—','—','—','—')]
COVERAGE=[
 ('Geography / segment','Sales Ops maintains; RevOps governs the approved mapping.','Define which country/location drives coverage, any segment/vertical criteria and named-account exceptions. Use Sales Territories if enabled and suitable; configure Account assignment rules, user membership and access levels. Otherwise use explicit groups/teams and sharing.','Test a matching and nonmatching account, overlapping territories and a changed address/segment. Account Tier is not an access rule until its mapping is approved.'),
 ('Named / global accounts','Sales leadership names the accountable AE; Sales Ops maintains the approved roster.','Use named Account assignments and Account Teams for ongoing coverage. Define parent/subsidiary exceptions explicitly. Opportunity owner remains independently assigned; it is not forced to equal Account Owner.','A global parent does not automatically grant every subsidiary. Account hierarchy is relationship context, not a record-sharing grant.'),
 ('Opportunity / technical coverage','AE and SE leadership identify the deal team.','Use Opportunity Teams for the specific deal. Reconcile Primary SE and coverage ownership. Set the minimum record access and the separate field/action entitlements.','Account coverage must not silently expose every sibling opportunity. A team-role label alone grants no commercial approval or field permission.'),
 ('Partner + regional overlays','Partner Ops maintains partner coverage; Sales Ops maintains geographic scope.','Evaluate both the active partner association and the user’s geography/territory scope before generating an Opportunity Team/share grant. Multiple associations may justify the same user’s membership.','Same partner / wrong geography and same geography / wrong partner must fail unless another explicit entitlement applies. Independent partner and region shares would grant a union, not the required intersection.'),
 ('Temporary cover / specialists','The coverage owner records the approved user, scope and end date.','Use a named, time-bound assignment in the existing coverage source or a governed roster. Automate expiry/reconciliation; a date in a note does not remove access. Product specialists use Case/deal grants for their assigned work.','At expiry remove only grants owned by that assignment. Preserve separately authorized grants, and record why any access remains.'),
 ('Operations / service coverage','Sales Ops, Partner Ops, Finance, Product and GSS own their respective rosters.','Use approved public groups/sharing for operational regions and scoped Cases/Orders. Queues can route supported Tasks/Cases; do not use an Opportunity queue. Managers’ inherited access is reviewed separately.','Test cross-region requests, restricted Case types and record transfers. Support duties do not confer pricing, source correction, booking or broad export authority.')]
TERRITORY_STEPS=[
 ('1. Confirm the coverage source','Record the current Sales Territories model, enabled features and licenses. Identify the authoritative coverage roster and its owner. Confirm geography basis, named-account precedence, segment/vertical rules and exceptions before configuration; no new geography taxonomy is assumed.'),
 ('2. Map assignments separately','Distinguish Account Owner, Opportunity Owner, Account territory membership, Opportunity Territory, Account Team and Opportunity Team. Accounts may have overlapping coverage; an Opportunity has one Territory assignment. Use teams for additional specialists rather than inventing multiple Opportunity territories.'),
 ('3. Configure the intended grants','In Setup → Territory Models, work in a Planning model where Sales Territories is used. Define territory types/hierarchy, assignment rules, users and access levels; preview Account assignments. Configure Opportunity assignment separately, including manual exceptions or the supported assignment filter. Account assignment is not proof that the deal has the correct Territory.'),
 ('4. Check access before activation','Review both role and territory hierarchies, parent-territory access, Account implicit access, Account Teams and other sharing rules. Territory membership and territory administration are separate entitlements. A territory cannot remove access granted elsewhere.'),
 ('5. Reconcile every coverage change','Recalculate on user joins/leaves, partner or territory changes, account/deal transfers, inactive associations and expiry. Keep a grant source/reason so reconciliation can remove its own membership without deleting another justified grant. Test owner transfer: standard-object manual shares can be removed and may need reconciliation.')]
FIELDS=[
 ('Opportunity · sales/qualification','Sales; approved operations corrections','Use FLS for field capabilities and record sharing for scope. Validate stage actions against the user’s permitted deal role and all gates; technical edit access alone must not permit a commercial stage change.'),
 ('Opportunity · technical evidence','Assigned Sales Engineering','Technical Value/Outcome, POCs, technical risks and SE next actions. Product and partner technical specialists contribute only within explicitly assigned responsibilities.'),
 ('Account · coverage / tier','Partner Ops for partner owners; Sales / Sales Ops / RevOps for Account Tier','Tier choices remain 1 / 2 / 3. Partner manager, technical lead and Admin Contact stay on Account. A coverage lookup identifies responsibility; it does not itself share records or grant administrator rights.'),
 ('Account · RevOps Notes','RevOps writes; RevOps and expressly entitled Sales Ops read','Use FLS for the field, including reports/API. Check other permission sets and any broad field-visibility grant. Do not copy restricted text into widely visible fields, feeds or notifications.'),
 ('Opportunity · accepted Partner source','Authorized correction action','After acceptance, validate ordinary writes across UI/import/API. The action requires a dedicated custom permission plus evidence, reason and audit; check record scope as well. Management contribution override is a different entitlement.'),
 ('Opportunity · Amount / commercial fields','Authorized Sales / commercial process','Keep read-only for technical and partner-only personas; CPQ Primary Quote sync remains authoritative. A user with both Sales and overlay permission sets gains combined FLS: use record-specific authorization checks for commercial writes on overlay-only deals.'),
 ('Opportunity · system-maintained fields','Designated automation','AE Next Steps, Forecast Category (Sales), Stage 0–6 Dates, Pipeline Date/Entry Amount and review timestamps remain read-only to business users. Preserve logger/integration rights without a blanket validation bypass.'),
 ('Opportunity · booked facts','Authorized OM workflow / approved correction path','Protect booked Close Date, Amount, Products and attribution. Allow authorized 7 → 8 delivery progression and invoice/reference synchronization. A whole-record lock must not block those required updates.'),
 ('Cases · enhancement vs deployment','Product / assigned SE for enhancements; GSS for deployment','Configure Case sharing, FLS and server-side checks for the permitted workstream. Record types control available process/layout choices; they do not secure existing records by themselves. Sales supplies evidence; assigned SE/Product perform permitted Case writes.'),
 ('Privileged actions','Named delegated users only','Separate entitlements for record transfer, territory administration, registration approval, commercial approval, source correction, contribution override, OM booking and validation bypass. Check the actor and target record inside each action, not only button visibility.')]
RELATED=[
 ('Associated accounts','Existing Partner Opportunity Influence object; confirm API name and relationship type.','Authorized Sales / partner collaborators create and maintain in-scope associations; Partner Ops maintains coverage context. Align sharing with the permitted Opportunity and Account. Master-detail may inherit access; lookup relationships need an explicit sharing design.'),
 ('Opportunity Contact Roles / Users','Existing Contact Roles and User lookups.','Grant the parent Opportunity/Contact access needed for the supported Contact Role actions. Validate originating Contact linkage and lookup visibility; provide visibility to eligible AE/SE/coverage users without broad administrative grants.'),
 ('CPQ Quotes / lines / products','Verify installed CPQ package, licenses and object API names.','Grant pricing capabilities only to approved commercial users. Apply Stage 0–1 Budgetary and Stage 2–5 gates, Primary Quote synchronization and approval controls on the actual package objects.'),
 ('Orders / lines / invoice references','Existing Order integration and booking model.','Designated OM edits booking/fulfillment facts; Finance edits authorized financial context; GSS gets required delivery context. Confirm which fields integrations own and which named users may correct them.'),
 ('Files / Salesforce Content','PO, quote, technical and Win/Loss documents.','Configure file links and visibility separately from Opportunity sharing. Confirm a real PO File is accessible to OM; retain restricted Deal Team Reports and interview notes in controlled locations. A linked record does not justify unrestricted file distribution.')]
CONFIG=[
 ('Baseline and capability sets','Inventory profiles, permission sets/groups, licenses, OWD, role hierarchy, sharing rules, teams, territory model, integration users and bypasses. Build minimum capability permission sets for the nine personas; use groups to assemble them. Keep new capability grants separate from record coverage.'),
 ('Account / Opportunity / Contact sharing','Use Private Account/Opportunity OWD where needed to achieve the approved scope, after impact review. Decide Contact Controlled by Parent versus separate Contact sharing from the actual model. Include parent Account implicit access from shared Opportunities/Cases/Contacts and any Account-owner access to child records.'),
 ('Additive access and restrictions','Permissions and sharing grants combine. Muting one permission-set group cannot cancel a grant elsewhere. Accounts, Contacts and Opportunities are not supported by standard Restriction Rules; do not promise a rule will subtract broad territory or hierarchy access. Remove the unwanted grant at its source or resolve the coverage design.'),
 ('Activities¹','The Task column expresses intended create/read/edit capability, not a standard CRUD checkbox recipe. Configure Access Activities, Edit Tasks, Task/Activity FLS and Activity OWD. Test Name (Who), Related To (What), ownership and hierarchy together. Task edit can include delete/reassignment; confirm retention and correction controls explicitly.'),
 ('Conditional edits and execution context','FLS is per user/field, not per record. For dual-role users, enforce role-in-this-deal and stage/workstream conditions on the server. Flows/Apex must check intended record, object and field access; system execution must not become an unrestricted write path. Grant only the Flow/Apex/connected-app access needed.'),
 ('Reports and general system rights','Review report/dashboard folders and running-user exposure. Export Reports, data export, API access, imports and Setup are distinct permissions. Grant named-user add-ons only where needed; exclude View All / Modify All Data and object-wide sharing overrides from base personas.'),
 ('Territory administrator delegation','Manage Territories and related Setup permissions belong to designated admins. Use supported scoped territory administration only after checking the feature and required assignments. Do not give every territory member territory-admin rights or grant View All Accounts merely to simplify assignment operations.'),
 ('Evidence for handoff','Produce the approved coverage mapping, permission-set assignments, sharing configuration, privileged-action list and test results. Record unresolved API/package mappings as configuration dependencies; do not treat this page as evidence that the org already matches the target.')]
TESTS=[
 ('Seller / territory','AE can work an assigned deal; an unrelated territory’s deal is unavailable unless another approved share exists. Account and Opportunity owners may differ without forced reassignment.'),
 ('Partner intersection','Correct partner + correct region grants scoped access. Each one-condition-only case is denied. Test a second partner association, a direct deal with no entitlement, and a separately approved direct-pipeline entitlement.'),
 ('Hierarchy and overlap','Test territory parent, role manager, named/global account, overlapping territory, Account owner and Account Team access. Document every legitimate inherited grant; do not claim strict regional isolation while a broader grant remains.'),
 ('Dual-role user','A Sales + partner-overlay user can maintain authorized commercial fields on an owned Sales deal but cannot use those same global field permissions to rewrite commercial fields on an overlay-only deal.'),
 ('Coverage removal','Transfer the account/deal; remove or expire coverage; deactivate the partner association. Derived access is removed while separately justified access remains. Re-run to prove reconciliation is idempotent.'),
 ('Fields and actions','Restricted RevOps Notes stay hidden; system dates/logs reject manual writes; accepted Partner source requires the correction action; team membership cannot approve prices or book a deal.'),
 ('Tasks / Cases / Files','Test Task ownership and both related records, restricted Case workstreams, PO File access and private report documents. Sharing a Task must not grant the user a private deal. Read-only parent access must not be assumed to allow editing another user’s Task.'),
 ('Every write path','Test UI, stage screen flow, bulk/API/integration writes and record-type variants. A failed stage save creates no timestamps or partial evidence. Authorized delivery/invoice updates still work after booking.')]
SOURCES=[
 ('Sharing architecture','https://architect.salesforce.com/docs/architect/fundamentals/guide/platform-sharing-architecture.html'),
 ('Object, field and record access','https://help.salesforce.com/s/articleView?id=security_data_access.htm&language=en_US&type=5'),
 ('Territory assignment setup','https://help.salesforce.com/s/articleView?id=tm2_assign_accounts_to_territories.htm&language=en_US&type=5'),
 ('Opportunity territory assignment and parent access','https://help.salesforce.com/s/articleView?id=sales.tm2_assign_territory_to_opportunity_considerations.htm&language=en_US&type=5'),
 ('Single Opportunity territory / assignment behavior','https://help.salesforce.com/s/articleView?id=005133013&language=en_US&type=1'),
 ('Territory administrator permissions','https://help.salesforce.com/s/articleView?id=sf.tm2_how_access_permissions_work.htm&language=en_US&type=5'),
 ('Restriction Rule supported objects','https://help.salesforce.com/s/articleView?id=005167057&language=en_US&type=1'),
 ('Activity sharing and edit rules','https://help.salesforce.com/s/articleView?id=sales.activities_view.htm&language=en_US&type=5'),
 ('Access Activities permission','https://help.salesforce.com/s/articleView?id=sales.activity_access_user_perm.htm&language=en_US&type=5'),
 ('Permission-set capabilities','https://help.salesforce.com/s/articleView?id=platform.perm_sets_permissions_access.htm&language=en_US&type=5')]

def matrix(headers,rows,id):
 return '<div class="permission-table-scroll" tabindex="0" role="region" aria-label="'+E(id)+'"><table class="admin-matrix admin-cols-'+str(len(headers))+'"><thead><tr>'+''.join('<th scope="col">'+E(x)+'</th>' for x in headers)+'</tr></thead><tbody>'+''.join('<tr><th scope="row">'+E(row[0])+'</th>'+''.join('<td>'+('<span class="permission-code">'+E(c)+'</span>' if c in ['R','R E','C R E','Activity¹','—','Separate'] else E(c))+'</td>' for c in row[1:])+'</tr>' for row in rows)+'</tbody></table></div>'

def cards(rows):
 return '<div class="admin-config-grid">'+''.join('<article><h3>'+E(title)+'</h3><p>'+E(body)+'</p></article>' for title,body in rows)+'</div>'

def source_links(indices):
 return '<p class="admin-note">Salesforce reference: '+ ' · '.join('<a href="'+E(SOURCES[i][1])+'">'+E(SOURCES[i][0])+'</a>' for i in indices)+'.</p>'

def permissions_page(header):
 out='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Access and Permissions · GTM Process</title><link rel="stylesheet" href="assets/navigation.css"><link rel="stylesheet" href="assets/learning.css"></head><body id="top" data-page="permissions"><a class="skip" href="#main">Skip to content</a>'+header('permissions')+'<main id="main" class="permissions-shell"><p class="admin-eyebrow">Salesforce administrator reference</p><h1>Access and Permissions</h1><p class="page-intro">Configure three things together: what each role can do, which records its coverage grants, and which fields or actions need extra control.</p><p class="admin-note">Target design for internal DDN users. Current org configuration has not been inspected in this audit. Confirm metadata, licenses and existing grants before implementing the gap.</p><nav class="admin-page-jumps" aria-label="Permission sections">'+''.join('<a href="#'+id+'">'+title+'</a>' for id,title in [('role-definitions','Roles'),('coverage-model','Coverage model'),('territory-setup','Territories'),('object-matrix','Object access'),('field-access','Fields & actions'),('related-access','Related records'),('system-matrix','System access'),('configuration','Configure'),('access-tests','Validate')])+'</nav>'
 out+='<section id="role-definitions"><h2>Defined roles</h2><div class="admin-role-grid">'+''.join('<article><h3>'+E(name)+'</h3><p>'+E(desc)+'</p></article>' for name,desc in ROLE_DEFS)+'</div><p class="admin-note">These personas become capability permission-set groups, not nine required Salesforce hierarchy roles. Partner overlays are internal users; external partner/Experience Cloud access is a separate design. Order Management is a named booking entitlement, including when staffed by Sales Ops or Finance.</p></section>'
 out+='<section id="coverage-model"><h2>Coverage model</h2><p>Agree the scope and assignment owner for each model. Coverage grants record access; it does not change source attribution, sales credit or approval authority.</p>'+matrix(['Coverage','Accountable owner','Administrator configuration','Acceptance boundary'],COVERAGE,'Coverage model')+source_links([0,1])+'</section>'
 out+='<section id="territory-setup"><h2>Territory configuration</h2><p>Use Sales Territories (Enterprise Territory Management) when the existing org supports the approved coverage design. Do not enable a new territory feature or assume a Territory Planning add-on is required solely because of this document.</p>'+cards(TERRITORY_STEPS)+source_links([2,3,4,5])+'</section>'
 out+='<section id="object-matrix"><h2>Object permissions matrix</h2><p><strong>C</strong> Create · <strong>R</strong> Read · <strong>E</strong> Edit. Combine these capabilities with record sharing and field controls. No Delete or object-wide View All / Modify All is requested for the standard CRUD objects. <strong>Activity¹</strong> uses the separate activity configuration below.</p>'+matrix(['Role','Accounts','Opportunities','Contacts','Tasks¹','Cases','Record scope / edit boundary'],OBJECT_ROWS,'Object permissions matrix')+'<p class="admin-note">Read/Edit applies only within the approved workstream. Record type or page-layout assignment alone cannot restrict existing records. For Tasks, Edit Tasks and related access may permit deletion or reassignment; the CRUD legend does not prove those actions are blocked.</p>'+source_links([1,7,8])+'</section>'
 out+='<section id="field-access"><h2>Field and action controls</h2>'+matrix(['Object / field group','Who can write','Configure / limit'],FIELDS,'Field and action controls')+'</section>'
 out+='<section id="related-access"><h2>Related records and packages</h2><p>The core matrix is not sufficient for completing the process. Configure these dependencies using the org’s actual object and package mappings.</p>'+matrix(['Record group','Mapping to confirm','Required access design'],RELATED,'Related record access')+'</section>'
 out+='<section id="system-matrix"><h2>General system access</h2><p><strong>Separate</strong> = a dedicated entitlement for named users. <strong>—</strong> = no grant from this persona. Report creation still requires the correct folder and data access.</p>'+matrix(['Role','Reports / dashboards','Export reports','Import / bulk tools','API access','Setup / deployment','View All / Modify All Data'],SYSTEM_ROWS,'General system access')+source_links([9])+'</section>'
 out+='<section id="configuration"><h2>Administrator configuration</h2>'+cards(CONFIG)+source_links([0,1,6,7,8,9])+'</section>'
 out+='<section id="access-tests"><h2>Prove the access model</h2><p>Use named test users with their full combined grants. Record the expected and actual result for each allowed and denied action.</p>'+matrix(['Scenario','Expected result'],TESTS,'Access acceptance tests')+'<details class="admin-sources"><summary>Official platform references · reviewed 29 September 2026</summary><p>Salesforce mechanics are sourced below. DDN coverage assignments and role allocations remain the target business design.</p><ul>'+''.join('<li><a href="'+E(url)+'">'+E(label)+'</a></li>' for label,url in SOURCES)+'</ul></details></section></main><a class="backtop" href="#top" aria-label="Back to top">↑ Back to top</a></body></html>'
 return out
