"""Learning outcomes, self-contained practice and application checks.
All customer situations and example numbers are illustrative.
"""
DESIGN = {}
def review(id, goal, practice, model, question, answer, takeaway):
    DESIGN[id] = dict(goal=goal, practice=practice, model=model, question=question, answer=answer, takeaway=takeaway)

review('source',
'Identify the correct source and sourcing reference without confusing origin, ownership or fulfillment.',
'A campaign generates a qualified contact. An AE creates the opportunity and a reseller later handles fulfillment. What should the source and sourcing reference be?',
'Source: Marketing. Sourcing reference: the originating campaign. The AE is the Opportunity Owner; the reseller’s fulfillment role is captured separately. Neither changes the campaign origin.',
'A BDR hands you an opportunity, but the intake has no originating BDR reference. What must happen before creation?',
'Resolve the originating BDR reference with the intake team before creating the opportunity. Do not credit the current AE or integration user just to complete the record.',
'Origin → supporting handoff → matching sourcing reference. Record the current owner and fulfillment role separately.')
review('conversion',
'Reconstruct the correct qualification milestones for an inbound or seller-direct opportunity.',
'Compare a Marketing-qualified contact entering Validate with a seller-qualified opportunity created directly in Discovery. Write each conversion path.',
'Marketing inbound: MQL → SAL at opportunity creation → separate seller acceptance and inbound qualification → SQL on first Discovery entry. Seller-direct: SAL and SQL at direct Stage 1 creation, with auto-acceptance and the direct-entry path recorded. Do not add a fictional MQL or AQL.',
'A customer already has a mature Account lifecycle. A second opportunity starts in Validate. What should change?',
'Record the new opportunity’s SAL episode and originating Contact relationship. Preserve the existing customer lifecycle; a new early-stage deal is not evidence that the Account has moved backward.',
'For each episode: originating Contact + underlying source + qualification path + actual milestone. Keep separate opportunities reportable.')
review('sal-review',
'Make a clear handoff decision and explain what still needs to be satisfied before Discovery.',
'An inbound handoff has a Contact but no identifiable project or relevant need. Draft a rejection note that helps the originating team act.',
'“Rejected: the conversation did not establish an active project or a relevant customer challenge. Re-engage to confirm the affected workflow and why a change is needed; provide that evidence for a new review.” This explains the gap without inventing a SQL or a loss decision.',
'You accept an inbound opportunity, but its Money answer is missing. Can you move it into Discovery, and why?',
'No. Acceptance establishes the seller’s disposition, not completion of qualification. Resolve all five inbound CHAMPS answers, plus the assignment and Contact requirements, before Stage 1.',
'Decision + evidence + missing qualification + next action. Keep acceptance separate from the SAL creation milestone.')
review('challenge',
'Write a customer-evidenced Challenge statement that identifies the problem and affected workflow.',
'The customer says “our storage is old.” Ask two follow-ups, then draft a Challenge statement without inventing answers.',
'Ask: “What happened recently that made the age a problem?” and “Who was affected, and what could they not do?” Until answered, record: “Customer reports aging storage; the operational problem and affected workflow still need validation.” Replace that uncertainty with the customer’s evidence after the discussion.',
'The buyer requests twice the capacity but has not explained why. What should you discover before calling this a validated Challenge?',
'Ask what activity is constrained today, who experiences the constraint and a recent example. A requested specification is evidence of a request, not yet of the underlying problem.',
'“[Team] experiences [specific problem] during [workflow], as shown by [customer example].”')
review('authority',
'Distinguish a contact’s recommendation power from budget, technical and approval authority.',
'A contact says “I decide everything,” but mentions a finance review. Write two questions and the provisional authority note.',
'Ask: “What can you approve directly?” and “What decision does finance make, and can it stop the purchase?” Note: “Contact claims overall decision responsibility; finance’s approval role and any spending limit remain unconfirmed.” Do not resolve the ambiguity by title alone.',
'The architect can veto the design but cannot release funds. How should that affect your buying map?',
'Record the architect’s technical authority and identify who controls the budget separately. Strong technical influence does not prove Economic Buyer authority.',
'Person → decision they control → approval limit or dependency → evidence → access still needed.')
review('money',
'Capture funding evidence while clearly distinguishing estimates, requests and approved budget.',
'The customer says, “We expect $400,000, but finance has not approved it.” Rewrite the Money answer and name the next question.',
'“Customer estimates a $400,000 project budget; finance approval is pending.” Next ask what finance needs to approve the allocation and who is accountable for that decision. Keep the amount labeled as an estimate.',
'A buyer names a budget range but cannot identify its funding route or approver. What can you responsibly record?',
'Record the buyer-provided range and its source, with funding route and approval status still unconfirmed. Seek those facts instead of upgrading the estimate to an approved budget.',
'Amount or range + funding route + approval status + approver + remaining condition. Label unverified information.')
review('priority',
'Validate customer urgency through a business event, a consequence and competing priorities.',
'The prospect says “ASAP.” Write three questions that would make this useful for qualification.',
'“Which event or deadline makes this urgent?” “What happens if it is delayed?” “Which other projects compete for the same funding or people?” Together these test timing, consequence and relative importance.',
'The AE needs a quarter-end close, but the customer sees no consequence in waiting. What should the Priority answer say?',
'Describe the customer’s actual priority and the absence of a confirmed deadline. The seller’s target does not supply customer urgency. Continue discovery rather than presenting quarter-end as a customer requirement.',
'Customer event/date → consequence of delay → competing priorities → confirming person.')
review('stack',
'Create a useful technical handoff that separates measured facts from estimates and validation gaps.',
'The lab measured 8-hour staging. It estimates a 30% data increase and suspects a network bottleneck. Write the handoff.',
'“Measured: staging takes 8 hours under the observed conditions. Customer estimate: data volume may grow 30%. Hypothesis: network bottleneck. SE to validate workload conditions, growth assumptions and the actual limiting component.” Do not present the suspected bottleneck as a test result.',
'The intake lists product names and capacity but no workflow. What should the SE still learn before designing?',
'How data is ingested, stored, processed and accessed; where the constraint occurs; and relevant integration or migration dependencies. Product and capacity names alone do not establish technical fit.',
'Workflow + environment + observed constraint + dependencies. Mark each item measured, reported or still to validate.')
review('use-case',
'Translate requested specifications into a clear customer workflow and intended outcome.',
'A request says “more capacity and throughput.” The customer explains that researchers wait for dataset preparation between model-training runs. Write the use case.',
'“AI model training: researchers need datasets prepared faster between experiments so they spend less time waiting for the next run.” Capture the requested specifications as design inputs, not as the use case itself.',
'Two customers request the same product, one for archiving and one for model training. Should their Use Case information be identical?',
'No. Describe each customer’s activity, users and desired outcome. Similar products can serve different workflows with different evaluation requirements.',
'“[Users] need to [activity] so they can [intended outcome], within [relevant constraints].”')
review('route',
'Record the purchasing route without rewriting how the opportunity originated.',
'A BDR-origin opportunity will transact through a reseller. Identify the source, sourcing reference, route and additional route information.',
'Keep BDR as Opportunity Source and the originating BDR as Sourcing User. Set Route to Market to Indirect and choose the applicable supported Indirect Route Type. Capture the reseller’s involvement separately.',
'The customer switches from a reseller purchase to Direct. What happens to the source and the old indirect type?',
'The original source remains. The old Indirect Route Type becomes inactive for current attribution and is hidden, with its history preserved. Direct does not need a second route selection.',
'Origin answers “where did it come from?” Route answers “how will the customer buy?” Confirm each separately.')
review('pain',
'Develop the initial challenge into a validated consequence that explains why the customer should act.',
'The customer says “performance is slow.” You do not yet know the business impact. Draft two follow-ups and a responsible provisional pain note.',
'Ask: “What cannot happen while you wait?” and “How often does that affect the team?” Note: “Customer reports slow performance; downstream impact and frequency are not yet confirmed.” Develop the note only when the customer supplies evidence; do not invent savings.',
'The customer confirms repeated rescheduling but cannot quantify its cost. Is the pain unusable until a dollar amount is available?',
'No. Record the validated operational consequence and its frequency. Quantify the economic effect later with the customer. Preserve the original CHAMPS Challenge separately.',
'Problem → who is affected → consequence → frequency → customer evidence. Keep unconfirmed financial impact explicit.')
review('competition',
'Separate active alternatives, incumbent use and the actual competitive outcome.',
'A customer cancels its project without selecting a vendor. The incumbent equipment remains in use. Explain the loss outcome.',
'The existing vendor is still the incumbent, but that does not prove it won a competitive decision. Record the supported loss reason and Not lost to competitor when no vendor was selected, with details explaining the cancellation.',
'A vendor is on the shortlist but absent from the supported competitor list. What should you capture?',
'Use Other when available and supply the company name in Competitor Detail. Keep that specific name separate from the broader explanation of the customer’s evaluation or loss.',
'Current vendor ≠ shortlist ≠ final outcome. Ask the customer about each before recording it.')
review('technical-value',
'Explain why a selected configuration fits the customer’s criteria and cite the evidence behind it.',
'The criteria are workload performance, usable capacity and integration. Option A passes performance/capacity but has an untested integration; B passes all three in the agreed evaluation. Write a recommendation.',
'“Recommend configuration B, using the evaluated version, because evidence supports all three agreed criteria. A meets performance and capacity but its integration remains unvalidated.” Link the tests and exact version. Do not state that A fails a test that was never run.',
'The quote references version 2 while technical validation covered version 3. What must be reconciled before relying on the Technical Win?',
'The selected configuration, quote and supporting evidence must identify a consistent scope/version. Ask the SE to confirm technical substance after reconciliation; populated text alone does not resolve the mismatch.',
'Customer criterion → selected configuration/version → supporting evidence → remaining dependency.')
review('champion',
'Test advocacy through observable actions rather than treating friendliness as proof of influence.',
'A contact is enthusiastic but has not involved anyone else. Choose one useful action to request and what it would show.',
'Ask the contact to arrange a value discussion with the budget owner and help prepare for that buyer’s concerns. An actual introduction and useful internal context provide evidence of advocacy and reach. A promise alone remains untested.',
'Your contact praises the product but repeatedly cannot secure access to decision makers. How should you describe the champion position?',
'As unvalidated or limited, with the observed support and access gap stated clearly. Continue developing other relationships rather than treating enthusiasm as confirmed influence.',
'Person + reason they care + action taken + influence demonstrated + gap to test next.')
review('criteria',
'Turn broad preferences into customer-confirmed criteria that can distinguish competing solutions.',
'The customer asks for “fast, scalable and easy.” Write one evaluation question for each.',
'Fast: “Which workload and completion time will demonstrate acceptable performance?” Scalable: “What capacity or growth requirement must the design support?” Easy: “Which integration or operating task must your team complete, and how will you judge it?” Agree the answers rather than inventing thresholds.',
'The team proposes a benchmark it expects to win, but the customer says it does not represent their workload. Can it stand as the decisive criterion?',
'No. Reconfirm what the customer will actually evaluate and which evidence it accepts. A seller-favorable benchmark is not automatically a buyer criterion.',
'Requirement + measurement/test + acceptable result + customer confirmation.')
review('technical-outcome',
'Decide whether evaluation evidence supports Technical Win for the selected configuration.',
'The POC is complete, but the customer disputes the test conditions. What must be resolved before Technical Win is recorded?',
'Agree which conditions represent the customer’s workload, review or repeat the affected validation, and confirm the selected configuration against the criteria. Keep the POC’s Completed status distinct from the disputed technical conclusion.',
'The POC is Completed and Technical Outcome is Technical Loss. The AE wants Stage 4. What is the correct decision?',
'Do not advance to Stage 4. Technical Win and the other Buyer alignment requirements must be satisfied. Completion of the test does not override its outcome.',
'One selected configuration + agreed criteria + supporting evidence + SE-confirmed outcome.')
review('operational-value',
'Write a measurable operational outcome with a baseline, target and agreed validation method.',
'A lab measures 8-hour dataset staging and wants 2 hours. Draft the value statement, including what still needs agreement.',
'“Reduce staging from the measured 8-hour baseline to a 2-hour target using the same representative dataset and comparable conditions.” Agree the measurement participant, test conditions and assessment timing with the customer. Mark these as unresolved until confirmed.',
'The customer agrees to the 2-hour target before purchase. What belongs in Operational Value, and what cannot yet be claimed?',
'Record the baseline, target and measurement expectations. Do not claim value achieved: agreement defines the intended outcome; the later customer-supported assessment establishes the actual result.',
'“Improve [workflow] from [baseline] to [target], measured by [method] with [customer participant].”')
review('economic-buyer',
'Identify the actual budget decision maker and validate their authority for this purchase.',
'The CFO signs contracts, but the business unit director controls project funding. What would you verify before naming the Economic Buyer?',
'Confirm whether the director can allocate this amount, whether finance can withhold funding and whether additional approval is required. Contract signature alone does not settle budget control. Record the verified authority and remaining dependency.',
'Procurement can issue the PO after approval but cannot authorize spend. Should procurement be treated as the Economic Buyer?',
'No. Procurement owns part of the Paper Process. Identify the person who controls the budget and validate any limits on that authority.',
'Budget owner + authority for this amount + approval dependencies + confirming evidence.')
review('decision-process',
'Build a customer-confirmed decision sequence with people, dates and dependencies.',
'Technical review is Tuesday; the director reviews value Thursday; a committee meets the following Wednesday. The forecast assumes selection Friday. Identify the mismatch.',
'The selection date is unsupported if the committee must decide the following Wednesday. Confirm whether the committee is required and whether an earlier decision is possible; otherwise update expectations and the next action around the actual sequence.',
'The buyer says “the director decides,” but later mentions a mandatory committee. What should you do with the decision map?',
'Add and validate the committee’s role, timing and required evidence. Recheck dependencies and the expected close date rather than leaving a single-person assumption in place.',
'Step → decision owner → participants → evidence needed → date → dependency.')
review('business-value',
'Build a transparent economic case without equating elapsed time with financial savings.',
'Staging falls from 8 to 2 hours across 20 runs each month. Calculate the elapsed reduction and identify two assumptions to validate before assigning dollar savings.',
'(8 − 2) × 20 = 120 elapsed staging hours avoided per month. Validate whether the change releases staff time, machine capacity or only waiting time, and what financial value the customer assigns to that resource. Include relevant solution costs and avoid counting the same benefit twice.',
'Only 15 minutes of staff attention are needed during each 8-hour staging run. Can all 120 elapsed hours avoided be valued at the labor rate?',
'No. Elapsed duration is not staff effort. Establish the actual change in paid work or another validated economic outcome before applying a unit value.',
'Validated quantity × frequency × economic unit value, with costs, assumptions and customer approval made explicit.')
review('paper-process',
'Map the remaining transaction steps and test whether a promised PO date is credible.',
'The buyer promises a PO Friday; legal review starts Thursday. Draft a short clarification.',
'“To confirm Friday’s PO, who owns legal review and when can it finish? Does procurement need signed terms or onboarding before issuance, and who will approve those steps? Let’s confirm those dependencies before committing to Friday.”',
'The customer has selected your solution but vendor onboarding is incomplete. What belongs in the plan before treating procurement as complete?',
'The onboarding deliverables, responsible people, completion timing and dependency on PO issuance, alongside remaining legal and signature steps. Vendor selection alone does not complete the Paper Process.',
'Document or approval → owner → due date → prerequisite → evidence of completion.')
review('procurement',
'Prepare a consistent procurement package that OM can reconcile without guessing.',
'The selected quote specifies ten units, but the received PO lists eight. What must be resolved before the Stage 6 handoff?',
'Confirm the intended scope with the buyer and reconcile the quote and PO through the applicable correction process. Provide the correct PO and supporting agreements, IPG disposition and logistics. Do not silently alter scope or pass an unexplained mismatch to booking.',
'The PO is correct but IPG Finalized is blank. Can the team assume IPG is not required?',
'No. Record Completed after finalization/submission or an explicitly applicable Not Required disposition before Stage 6. Blank is not a decision.',
'Quote ↔ PO scope/amount; final agreements; IPG disposition; applicable logistics; accessible supporting files.')
review('won-decision',
'Explain the customer win and transfer a complete, actionable package into order and deployment review.',
'Prepare a Stage 6 handoff for a $1.4M win: selected configuration B, customer-supported value case, final PO attached, OM review pending.',
'Include the customer’s specific reason for selecting B and the linked value evidence; the quote/PO package and remaining OM review; named Resources Engaged; applicable interview eligibility and Contact or reason; and the coordinating deployment Case with GSS involvement. Forecast remains Commit while booking is pending.',
'The buyer has selected the solution and the AE has captured the win fields. OM has not reconciled the order. What stage/forecast should the team avoid claiming?',
'Do not claim OM-confirmed Closed won or forecast Won. Stage 6 records the won decision and remains Commit until OM completes the booking confirmation.',
'Why we won + customer value evidence + order package + conditional win information + deployment handoff.')
review('booking',
'Choose the correct correction path before and after booking while preserving booked facts.',
'Compare a quote-price error found at Stage 6 with a scope change found after Stage 7 booking.',
'At Stage 6: record the discrepancy, return to Stage 5 for CPQ correction, then revalidate procurement and Won decision entry. After booking: use the existing amendment/change-order process; any new sales quote uses a separately linked opportunity in Stages 2–5. Do not reopen the booked opportunity.',
'Order Review Status contains a “Booked” label but reconciliation is incomplete. Who decides whether Stage 7 is allowed?',
'OM must confirm reconciliation against the approved status and exception mapping. A nonblank status or the word “Booked” is not independent authority to advance.',
'Before booking: reconcile and revalidate. After booking: preserve the record and use the linked amendment process.')
review('invoice',
'Distinguish shipment, receipt and invoicing to decide when the Opportunity can finish.',
'Ten units are booked. The carrier dispatches all ten Monday, nine arrive Tuesday, the last arrives Thursday and the invoice follows Friday. Identify the Stage 8 milestone.',
'Thursday, once complete on-site receipt is verified. Shipment on Monday is insufficient and Tuesday is a partial delivery, so the opportunity remains in Stage 7 then. Record the invoice evidence when issued Friday; it does not reset the delivery milestone.',
'The full in-scope order is received but installation has not started. Does that prevent Stage 8?',
'No. Verified complete delivery controls Opportunity completion. Installation and value assessment continue on the coordinating Case; invoice reconciliation continues on the Order.',
'All non-cancelled booked items received? Verify the evidence, then complete the Opportunity. Keep later work on Order/Case.')
review('loss',
'Write a factual loss explanation with a useful follow-up and apply the reporting threshold correctly.',
'The customer confirms budget withdrawal; no vendor was selected. A salesperson suspects a competitor discount. Draft the loss note.',
'“Customer confirmed the project stopped because funding was withdrawn. No vendor was selected. A suspected competitor discount is unconfirmed and is not the recorded decision reason. Follow up after the next funding review.” Use the supported reason and competitive outcome that match those facts.',
'Compare a $1.4M loss from Stage 3 and a $5.1M loss from Stage 2. Which needs the qualifying Deal Team Loss Report?',
'Both. The first meets prior Stage ≥3 and amount >$1M; the second meets prior Stage ≥2 and amount >$5M. The restricted report is due within two business days and is never posted to #win-wire.',
'Confirmed decision + specific reason + competitor outcome + lesson + next action. Separate hypotheses from facts.')
review('quoting',
'Choose the quote purpose and urgency independently, then maintain the correct primary proposal.',
'The buyer needs a planning estimate before Friday’s budget review. Write the purpose and a defensible urgency explanation if standard timing would miss that meeting.',
'Purpose: Budgetary. Timing: Urgent only if the normal turnaround would miss the confirmed review. Reason: “Estimate required before Friday’s customer budget review; standard timing would miss the funding discussion.” Urgency does not turn the estimate into Best and Final.',
'A Stage 6 order review uncovers a product error requiring a new quote version. What should the team do?',
'Record the discrepancy and return to Stage 5 for the CPQ correction. Revalidate the procurement and Stage 6 entry requirements before returning. Quote creation/revision remains restricted to Stages 2–5.',
'Purpose + timing + urgency reason if needed + correct configuration + one Primary Quote belonging to the opportunity.')
review('next-steps',
'Write dated customer commitments and explicitly review whether they support the expected Close Date.',
'Rewrite “follow up,” “check legal” and “run test” into actions that identify who, what and when.',
'“Tuesday: AE and director confirm the funding decision date.” “Thursday: AE and procurement confirm legal approval and PO dependencies.” “Wednesday: SE and architect run the agreed migration validation.” Recheck whether each result supports the expected close; the SE’s review remains separate.',
'The next meeting and expected Close Date are unchanged this week. Must the seller rewrite them to prove a review?',
'No. Explicitly confirm the action and date through the supported review process even when the values are unchanged. Unrelated edits do not count as that review.',
'“[Date]: [participants] will [customer-facing action] to confirm [decision or result].” Review the Close Date assumption alongside it.')
review('buying-committee',
'Build a Contact-based buying map from verified roles rather than inferred titles.',
'The project involves a researcher, architect, budget owner and procurement lead. State what to verify for each before assigning supported Contact Roles.',
'Confirm whether the researcher uses or evaluates the solution; whether the architect evaluates or has technical decision authority; whether the budget owner controls the allocation; and which procurement steps the lead owns. Then assign supported roles to actual Contacts. Keep the originating conversion Contact distinct.',
'The originating researcher is linked at creation, but no Opportunity Contact Role is assigned. Is the Stage 2 Contact Role requirement satisfied?',
'No. Creation requires the resolved originating Contact; before Stage 2, at least one assigned Opportunity Contact Role is also required. These are separate checks.',
'Contact → verified buying role → influence/authority → relationship gap. Do not treat all committee members as conversion originators.')
review('poc',
'Plan a POC around a customer decision and correctly apply its completion gate.',
'A required POC is Blocked, but the AE wants to skip ahead to proposal. Explain the appropriate action.',
'Resolve the blocker and complete the evaluation, or record an actual cancellation with context. A required POC must be Cancelled or Completed before moving beyond Stage 2, including stage skips. Do not mark it complete simply to advance; assess Technical Outcome separately.',
'POC Required? is No. Must the team invent a Completed POC before Stage 3?',
'No. An explicit No may pass the POC check. The other Stage 2 requirements still apply; no dummy test or status is needed.',
'Uncertainty to resolve + customer criterion + representative test + agreed evidence + honest final disposition.')
review('risk',
'Explain a technical risk in terms of its condition, impact and evidence needed for resolution.',
'The required integration has not been validated and could delay launch. Draft a useful risk note.',
'“Integration behavior remains unvalidated. If it fails, the customer’s launch could be delayed. Track the integration issue and agreed test; maintain the appropriate risk level until validation demonstrates the requirement is met.” Add the linked issue, rather than using a general confidence statement.',
'Product accepts an enhancement request associated with this risk. Should the SE immediately mark the risk Resolved?',
'No. Acceptance of a request is not delivery or validation. Reassess using evidence that the relevant requirement has actually been met or the threat has otherwise been resolved.',
'Condition → customer/deal impact → category and severity → issue link → evidence needed to resolve.')
review('enhancements',
'Create a product request that explains the needed behavior and its customer impact without promising delivery.',
'The lab cannot pass job-status information from its scheduler to the proposed workflow. Draft a Case title and description.',
'Title: “Expose job status to the lab scheduler workflow.” Description: “The customer needs the scheduler to receive job-state updates so researchers can see whether a run completed. Current behavior does not support the required handoff. Validate the expected data and integration approach with Product; link the Opportunity.” No release date is promised.',
'The customer asks you to guarantee the requested capability next quarter, but Product has not confirmed timing. What should you say?',
'Explain that the request is under review and give only confirmed information. Agree how the team will communicate Product’s response and maintain the relevant technical risk. Filing the Case does not authorize a delivery commitment.',
'Title + customer workflow + missing behavior + expected result + impact + linked Opportunity.')
review('partner-accounts',
'Create distinct, actionable engagement plans for each organization involved in a deal.',
'A reseller handles purchasing; a technology vendor supports validation. Write one association plan for each.',
'Reseller: confirm the commercial route, fulfillment responsibilities and procurement contact; agree the next order-planning discussion. Technology vendor: identify the technical contact, validation contribution and next technical session. Use separate account associations so the roles and plans stay clear.',
'The end-customer Account is associated with the opportunity. Does that association itself establish partner credit?',
'No. End Customer-only associations do not trigger partner contribution. Credit depends on qualifying partner evidence and timing, not simply the presence of an associated account.',
'Account + role + expected contribution + contacts + next engagement. Preserve the original event history.')
review('fulfillment',
'Separate the fulfillment account from sourcing credit and the physical delivery destination.',
'Partner A originated the deal, reseller B fulfills it and the customer’s lab receives the equipment. Identify the three records of responsibility.',
'Partner A is the sourcing partner; reseller B is the fulfillment account; the lab is the actual receiving destination. OM must verify the ship-to account/address and arrangements rather than assuming either partner’s address is correct.',
'The current record still uses Primary Partner and the attribution migration is incomplete. Should a seller repurpose that relationship for fulfillment?',
'No. Confirm the rollout state with RevOps/Partner Managers. The rename depends on Associated accounts and migrated attribution being in place; changing the meaning early can corrupt historical credit.',
'Sourcing account → fulfillment account → verified ship-to account/address. Confirm each responsibility separately.')
review('partner-credit',
'Classify partner contribution from original ownership and the first qualifying event, preserving booked credit.',
'Classify: a partner/channel-only origin; a non-Partner-only deal with its first qualifying event in Stage 2; and one with its first event in Stage 4.',
'Partner/channel-only origin: Partner-only. First qualifying event in Stage 2: Partner-Led. First in Stage 4: Joint. Retain original origin, event date and event stage; later regression or transfers do not reset them.',
'A partner’s first association is added after booking at Stage 7. The team wants it to change automated credit. What happens?',
'The association remains visible, but automated credit is frozen at booking. An authorized management correction requires an audited reason; routine association changes do not rewrite booked credit.',
'Check origin first; then earliest qualifying event and stage; freeze at booking. Use evidence, not the latest owner or partner.')
review('nvidia',
'Keep NVIDIA’s account plan and Opportunity summary current without confusing their different statuses.',
'NVIDIA will join a technical workshop next Tuesday. Where should the meeting plan and overall engagement summary go?',
'The account-specific workshop plan, contacts and next steps belong on the NVIDIA association. The overall engagement and separately verified NVIDIA status belong in the Opportunity summary. Do not copy association Active/Inactive into the distinct status.',
'The canonical NVIDIA association becomes inactive. Should the team delete the history or keep entering new engagement information solely because NVIDIA was once involved?',
'Neither. Preserve the involvement history and stop requiring new input on the basis of that inactive association. Relevance depends on an active canonical NVIDIA association.',
'Account plan = who/what/next step. Opportunity summary = engagement and its supported status.')
review('logistics',
'Build a realistic sequence from shipping through receipt to installation, with clear dependencies.',
'The customer requests installation on the 20th and needs two days after receipt to prepare the site. What receipt target and confirmations are needed?',
'Receipt must be no later than the 18th if two calendar days is the agreed preparation interval. Confirm whether the customer means calendar or working days, site access, receiving availability, preparation responsibility and feasible shipping lead time before committing.',
'The carrier confirms dispatch, but the receiving contact has no delivery record. What date or milestone can you claim?',
'You can record the confirmed shipment. You cannot treat it as verified on-site receipt or installation. Obtain separate receiving evidence and maintain the distinct milestone dates.',
'Installation need ← site preparation ← receipt ← shipping. Confirm dates, owners and dependencies rather than copying one date into every field.')
review('ipg',
'Complete the IPG disposition and provide a handoff the receiving team can actually use.',
'The applicable IPG package was finalized and submitted as version 3. Write a concise handoff note using a placeholder for its actual location.',
'“IPG disposition: Completed. Submitted package: version 3. Supporting files: [actual location]. The receiving team can access that version; remaining handoff dependencies: [confirmed items or none].” Replace placeholders with verified information. Use the current internal IPG materials for package contents.',
'No one has determined whether IPG applies. Is Not Required a reasonable substitute for a blank field?',
'No. Confirm applicability with the responsible team. Before Stage 6, record either Completed or an explicitly applicable Not Required disposition; do not use it as a default shortcut.',
'Disposition + submitted version + accessible supporting files + remaining handoff dependencies.')
review('win-wire',
'Write an evidence-based win story and apply the exact amount thresholds.',
'Using the illustrative lab case, write a short win story and identify the additional requirements at $1M, $1.4M and $2.1M.',
'“The lab needed faster dataset preparation. The team validated a selected configuration against the customer’s criteria. The customer chose it for the documented technical and business value. The AE captured the decision evidence. The win story recognizes the account team and cross-functional contributors.” At $1M: Resources Engaged. At $1.4M: also the manager-reviewed Win wire within two business days. At $2.1M: also the Deal Team Win Report.',
'A win is exactly $2M. Does that amount trigger the additional above-$2M Deal Team Win Report?',
'No. The additional report threshold is strictly above $2M. The ≥$1M Resources Engaged requirement and >$1M two-day manager Win wire requirement still apply.',
'Customer problem + reason for selection + validated value + contributors. Check ≥$1M, >$1M and >$2M separately.')
review('interviews',
'Complete the correct interview-eligibility branch with an actual Contact or meaningful reason.',
'For a New Business win, the customer may be approached. For a Renewal loss, outreach is inappropriate. Describe the information required in each case.',
'Win: record Yes and select the appropriate Salesforce Contact. Loss: record No and provide the specific WL Reason Cannot Approach. Do not require or invent a Contact for the No branch, and do not substitute a free-text name for the Yes branch.',
'Eligibility is Yes, but the named person exists only in a note. What remains incomplete?',
'The actual Salesforce Contact relationship. Resolve and select the appropriate Contact; free-text identification does not satisfy Contact for Win/Loss Interview.',
'Yes → resolved Salesforce Contact. No → specific cannot-approach reason. Complete the applicable branch only.')
review('deployment',
'Hand off the full deployment scope with ownership and evidence for every workstream.',
'The lab needs hardware installation and data migration. Draft a handoff agenda that also preserves the promised customer value.',
'Confirm the coordinating Case and GSS owner; review both workstreams and their owners; agree shipping, receiving and installation dependencies; identify what proves each workstream is complete; and review the sales-defined value baseline, target and assessment plan. One completed workstream is not the full outcome.',
'Hardware installation is complete and its Case closes, but migration is still open. Can the team declare complete deployment?',
'No. The coordinating Case must account for all in-scope workstreams and their completion evidence. The original Opportunity still ends at Stage 8; it is not held open for migration or value assessment.',
'One coordinating Case + all workstreams + named owners + dependencies + completion evidence + value-validation plan.')
review('value-realization',
'Record an evidence-based value assessment and distinguish pending, achieved and missed outcomes.',
'The target is 2-hour staging. Write assessments for a customer-confirmed 2-hour result and a measured 3-hour result with agreed follow-up.',
'Achieved: “Customer measured 2 hours on the agreed workload and confirmed the target was met; record Yes, evidence and assessment date.” Missed: “Customer measured 3 hours against the 2-hour target; record No, the gap, assessment date and agreed investigation/retest.” If measurement has not happened, keep the assessment pending rather than using No.',
'The deployment checklist is complete but the customer has not measured the agreed outcome. What should Value Achieved? show?',
'Blank while the assessment is pending. Deployment completion is not evidence of value achievement; Yes requires confirmation, and No means assessed and not achieved.',
'Baseline/target → measured result → customer confirmation → Yes/No/date → evidence or gap and agreed action.')
review('time-to-value',
'Calculate Time to Value from the correct baseline and recognize when no result should be reported.',
'The Case opens September 28, full delivery is verified October 10, the invoice is issued October 18 and value is confirmed October 24. Calculate Time to Value.',
'14 days: October 24 minus October 10. Use the first verified delivery milestone, not Case creation or financial Invoice Date. The result is valid because achievement is confirmed and the assessment date is on or after the baseline.',
'Value is assessed as No on October 24. Should the same dates produce 14 days or zero?',
'Neither. Time to Value remains blank for No or pending; calculate only for confirmed Yes with valid dates. An unmet outcome is not zero-day achievement.',
'Time to Value = confirmed achievement date − first verified delivery date, only when Value Achieved? = Yes.')
review('forecast',
'Derive the sales forecast from the supported stage without treating a won decision as a booked win.',
'Map Validate, Discovery, Buyer alignment, Procurement, Won decision, Closed won and Invoice to the sales forecast.',
'Validate: Pre-pipeline. Discovery: Pipeline. Buyer alignment: Upside. Procurement and Won decision: Commit. Closed won and Invoice: Won. Solution design is also Pipeline; Proposal / negotiate is also Upside; Closed lost is Loss.',
'A seller-qualified opportunity is created directly in Discovery. Should its saved sales forecast remain Pre-pipeline because it is newly created?',
'No. It saves as Pipeline, derived from Stage 1. Creation is a capture step, not a separate numbered stage; the actual initial stage controls the category.',
'0 → Pre-pipeline; 1–2 → Pipeline; 3–4 → Upside; 5–6 → Commit; 7–8 → Won; Closed lost → Loss.')
review('deal-context',
'Write a concise opportunity summary and connect it to the exact technical evidence a teammate needs.',
'Write four sentences for the illustrative lab opportunity and identify the supporting technical material.',
'“The lab is preparing a new AI research workflow. Researchers report delays preparing datasets between experiments. The proposed solution will be evaluated against the agreed workload, capacity and integration criteria. The customer wants a validated reduction in staging time.” Link the current configuration/version, evaluation plan and results; mark any unvalidated statements as such.',
'A new SE finds two design versions in SharePoint and a Description that says only “see docs.” What should be corrected?',
'Provide the customer/solution/business-need summary and identify the current selected configuration with its supporting evidence. A collection of links does not tell the receiving team which scope or claims are valid.',
'Customer + workflow/problem + intended solution + business need. Link the current configuration and the evidence supporting it.')

# Only learner-relevant caveats remain visible, placed beside the method they affect.
CAVEATS = {
'source':'Use the current Sourcing Campaign reference until the Marketing migration is confirmed.',
'conversion':'PAX.AI is a qualification channel. Confirm its underlying Opportunity Source with RevOps rather than inventing a new source choice.',
'sal-review':'Use the supported acceptance/rejection process. Do not assume SAL Start Date means acceptance or SAL Completion Date means rejection.',
'competition':'Use the supported competitor choices; confirm taxonomy questions with RevOps rather than inventing a value.',
'operational-value':'Confirm with RevOps where Operational Value should be recorded if its proposed field is not yet available.',
'procurement':'For non-shipping or other exception motions, confirm applicable logistics evidence with OM/GSS. Do not enter placeholder dates or create dummy Cases.',
'booking':'OM and RevOps must confirm allowed order statuses and exception authority before the booking control is applied.',
'invoice':'For non-shipping motions, ask OM/GSS to confirm the applicable completion evidence rather than inventing physical receipt.',
'next-steps':'Use the review process confirmed for your rollout; ordinary record edits do not prove that a weekly review took place.',
'fulfillment':'Confirm attribution migration is complete before using the renamed Fulfillment Partner relationship.',
'partner-credit':'Before migration, qualifying association evidence comes from Primary Partner; afterward, from Associated accounts. End Customer-only associations never establish partner credit.',
'nvidia':'Confirm the supported NVIDIA status choices with RevOps. Association Active/Inactive is a different status.',
'logistics':'Confirm logistics requirements with OM/GSS for renewals, software/services and other non-shipping motions.',
'ipg':'Use the current internal IPG template and process for package contents; this lesson covers the disposition and handoff.',
'interviews':'Use the Win/Loss controls confirmed for your rollout.',
'deployment':'Confirm the applicable Case relationships and non-shipping requirements with OM/GSS. Reuse the coordinating Case on stage re-entry.',
'value-realization':'Use the Case controls confirmed for your rollout; value assessment does not create an additional Opportunity gate.'
}
