"""Course organization and approved learning changes; stable lesson IDs retained."""
STREAMS=[
 ('start-the-deal','Start the deal','Establish the account, origin, ownership and qualification needed to start a credible opportunity.',['source','conversion','sal-review','challenge','authority','money','priority','stack','use-case','route','account-context']),
 ('work-the-deal','Work the deal','Build customer evidence, align the buying team and demonstrate why DDN is the preferred solution.',['pain','competition','technical-value','champion','criteria','technical-outcome','operational-value','economic-buyer','decision-process','deal-context','buying-committee','poc','risk','enhancements','partner-accounts','partner-credit','nvidia','next-steps','meetings','forecast']),
 ('close-the-deal','Close the deal','Turn the agreed solution into an approved commercial decision and a clean booking handoff.',['business-value','paper-process','quoting','procurement','fulfillment','logistics','ipg','won-decision','win-wire','interviews','loss']),
 ('grow-the-deal','Grow the deal','Complete delivery, coordinate deployment and demonstrate the customer outcomes that support the next conversation.',['booking','invoice','deployment','value-realization','time-to-value'])]

def apply(MODULES,DESIGN,CAVEATS,TERM_TITLES,DEFINITION_TEXT,DEFINITION_EXAMPLES):
 def clean(x):
  if isinstance(x,str):return x.replace('Fulfillment Partner','Transacting Partner').replace('fulfillment partner','transacting partner').replace('Association Primary Contact','Association Sales Contact').replace('fulfillment account','transacting account').replace('fulfillment reseller','transacting reseller').replace('fulfillment responsibilities','transaction responsibilities').replace('fulfillment role','transaction role')
  if isinstance(x,list):return [clean(y) for y in x]
  if isinstance(x,dict):return {k:clean(v) for k,v in x.items()}
  return x
 for m in MODULES:m.update(clean(m))
 for k,d in DESIGN.items():d.update(clean(d))
 for mapping in [CAVEATS,TERM_TITLES,DEFINITION_TEXT,DEFINITION_EXAMPLES]:
  for k in mapping:mapping[k]=clean(mapping[k])
 M={m['id']:m for m in MODULES}
 M['source']['definition']='Opportunity Source records the verified origin of a deal: Direct, BDR, Marketing or Partner. Its sourcing reference identifies the originating user, campaign or partner.'
 M['source']['reminder']=['Direct / BDR → Sourcing User; Marketing → Sourcing Campaign; Partner → Sourcing Partner.','Registration and origination are separate: either can exist without the other.','Accepted partner origin is protected; authorized corrections require evidence and an audit trail.']
 M['source']['steps'][3]='Preserve and correct carefully — Keep accepted partner source when ownership or registration changes. Request an authorized RevOps / Partner Ops correction with evidence and a reason if the origin is wrong; a contribution override is a separate action.'
 DESIGN['source'].update(practice='A seller originates a deal. A reseller later registers it and will transact it. What source and references should be recorded?',model='Keep Direct with the originating seller as Sourcing User. Link the registration and associated reseller separately. A registration does not make the reseller the originating source.',question='Can a verified partner-origin deal be Source = Partner without an approved registration?',answer='Yes. Record the verified Sourcing Partner and origin evidence. Registration is a separate relationship and does not determine origin.')
 M['conversion']['reminder'][2]='Stage 0 is pre-pipeline. First Stage 1 entry snapshots pipeline Amount once; re-entry creates no new credit.'
 M['conversion']['steps'][3]+=' Stage 0 stays outside qualified pipeline totals. Preserve the first Stage 1 timestamp and Amount snapshot even when later pricing changes the current Amount.'
 M['route']['reminder'][2]='Direct pricing: notify the manager and relevant partner coverage before release; existing approvals still apply.'
 M['route']['steps'][3]+=' Notify the manager and relevant partner coverage before Direct customer pricing; capture the route earlier if requesting a Stage 0–1 budgetary quote. Notification itself is not a blanket approval gate.'
 M['technical-outcome'].update(definition='Technical Outcome records In Progress, Technical Win or Technical Loss. A win means the customer prefers DDN against the agreed criteria, supported by SE evidence and the selected configuration, subject to commercial agreement.',distinction='Technical fit demonstrates that DDN meets requirements. Technical Win also needs customer preference; completing a POC is not enough.',reminder=['Record In Progress while evaluation or customer preference is unresolved.','Confirm the customer prefers DDN, with criteria, configuration and evidence.','Only Technical Win passes the Stage 3 → 4 gate; record blockers and next actions while work continues.'],scenario='The lab confirms that DDN meets its performance target but is still comparing two vendors. The SE records In Progress, documents the unresolved comparison and schedules the customer decision review. After the customer confirms DDN is its preferred technical solution, the SE records the evidence for Technical Win.',strong='Technical Win: customer architect confirms DDN is preferred against the agreed ingest and recovery criteria; configuration B v3 and evaluation evidence linked; commercial agreement remains open.')
 M['technical-outcome']['steps'][2]='Confirm customer preference — Ask the customer which solution it prefers against the agreed criteria. Record In Progress until the evaluation and preference are resolved; use existing risk and SE Next Step fields for the blocker, owner and next action.'
 DESIGN['technical-outcome'].update(goal='Distinguish technical fit from customer-confirmed Technical Win and record the supported outcome.',practice='DDN passes the benchmark, but the customer is still choosing between two solutions. Set the outcome and the next action.',model='Record In Progress. Note that requirements are met but preference is unresolved; assign the SE to review the comparison and decision criteria with the customer. Do not advance past the Technical Win gate.',question='Can a passed POC and an SE-approved configuration establish Technical Win without customer preference?',answer='No. Those support technical fit. Technical Win additionally requires evidence that the customer prefers DDN against the agreed criteria, subject to commercial agreement.',takeaway='Ask which solution the customer prefers, why, and what remains unresolved. Record the evidence before changing the outcome.')
 M['technical-value']['steps'][3]+=' Meeting requirements establishes technical fit; Technical Win additionally requires customer-confirmed preference for DDN.'
 M['fulfillment'].update(title='Identify the Transacting Partner',definition='The Transacting Partner is the primary partner through which the commercial transaction is conducted. It can differ from the originating partner and the physical ship-to destination.',distinction='Commercial transaction, sourcing credit and ship-to destination are separate responsibilities.',reminder=['Confirm the partner through which the customer will transact.','Keep its role separate from source and partner contribution.','OM independently verifies the actual ship-to account and address.'],scenario='Partner A introduces a lab opportunity, reseller B will transact the purchase, and equipment must arrive at the lab. Record A as Sourcing Partner, B as Transacting Partner, and the lab as the verified ship-to destination.',questions=['Through which partner will the commercial transaction be conducted?','Where must the order arrive, and who will receive it?'])
 M['fulfillment']['strong']='Transacting reseller identified; end-customer receiving location independently verified by OM.'
 M['fulfillment']['steps'][0]='Confirm the commercial role — Identify the primary partner through which the transaction will be conducted and coordinate with the Partner Manager.'
 DESIGN['fulfillment']['question']='The Primary Partner attribution migration is incomplete. Should a seller repurpose that relationship for the transacting account?'
 DESIGN['fulfillment'].update(goal='Separate the transacting partner from source credit and delivery destination.',takeaway='Verify the originating partner, commercial transacting partner and actual ship-to account independently.')
 M['quoting'].update(stages='s0 s1 s2 s3 s4 s5 ongoing'.split(),definition='CPQ turns scope and pricing into a commercial proposal. Controlled Budgetary quotes are available in Stages 0–1; Stages 2–5 support broader quoting, with technical and commercial gates for Best and Final.',reminder=['Stages 0–1: Budgetary only, with customer context, scope, assumptions and commercial authority.','Before releasing Direct pricing, notify the manager and partner coverage.','Best and Final needs Technical Win and applicable approvals; retain Primary Quote synchronization and booked locks.'],scenario='A lab needs an indicative price during Discovery to size its funding request. The seller prepares a Budgetary quote with scope and assumptions, confirms the existing commercial authority and Direct-route notification, and explains the estimate’s limits. The quote does not imply a Technical Win or move the deal forward automatically.',steps=['Establish the request — Confirm Account, Opportunity, assigned seller, customer need, indicative scope/configuration and assumptions. In Stages 0–1, select Budgetary only.','Apply commercial controls — Select purpose and urgency; explain Urgent requests. Confirm existing pricing authority and Direct-route notification before customer release. Best and Final needs Technical Win, selected configuration and applicable approvals.','Build and reconcile — Use CPQ products and calculations. Select the single Primary Quote by Stage 4 and verify that it synchronizes Opportunity Amount and Products without overwriting first-entry pipeline credit.','Control changes — Revise under the permitted stage/purpose rules. Stage 6 corrections return to Stage 5 and revalidate; booked orders use the existing amendment path.'],strong='Stage 1 Budgetary quote: indicative scope and assumptions documented; assigned seller and account/deal links confirmed; Direct notification and existing commercial authority satisfied.',weak='Best and Final issued in Stage 1 because the customer wanted a price.')
 M['quoting']['answer']='No. Stage 6 uses the documented return to Stage 5 for correction; booked locks remain. Early Budgetary access only applies in Stages 0–1.'
 DESIGN['quoting'].update(goal='Choose the right quote purpose and apply the controls for early estimates and final pricing.',practice='A Stage 1 customer needs a planning estimate tomorrow. What can you provide, and what must be in place?',model='A Budgetary CPQ quote with customer/deal links, seller, need, indicative scope and assumptions; existing commercial authority and any Direct-route notification must be satisfied. Explain that it is an estimate and leave qualification and technical gates intact.',question='Does allowing early Budgetary quotes allow Best and Final in Stage 0 or a Stage 6 quote edit?',answer='No. Early access is Budgetary-only in Stages 0–1. Best and Final needs technical/commercial gates; Stage 6 corrections return to Stage 5.',takeaway='Match purpose to deal readiness. An early estimate is not evidence of qualification, technical preference or final approval.')
 M['partner-accounts']['steps'][2]+=' Maintain Association Sales Contact and Association Technical Contact. Use Other only with an explanation in Association Description / Plan. Active partner associations bring in the named Account partner manager and technical lead under scoped access.'
 M['partner-accounts']['reminder'][2]='Partners may join across the cycle; no universal partner gate. Booked credit remains protected.'
 M['partner-credit']['steps'][3]+=' Retain these contribution rules until an approved replacement is implemented; there is no automatic sunset.'
 M['enhancements']['steps'][3]+=' Product and RevOps aggregate linked demand across unique opportunities; several enhancement Cases must not multiply the same Amount. Associated revenue is exposure, not a promise.'
 M['forecast']['steps'][3]+=' Exclude Stage 0 from qualified pipeline totals and generation credit. First Stage 1 Amount is a historical snapshot; current Amount continues to reflect the live deal.'
 # Exact compact definitions override earlier explanations.
 for id in ['source','technical-outcome','fulfillment','quoting']:DEFINITION_TEXT[id]=M[id]['definition']
 DEFINITION_TEXT.update({'term-sourcing-partner':'The partner Account that actually originated an opportunity with Source = Partner. Registration, transaction and later contribution are separate relationships.','term-technical-win':'Customer-confirmed preference for DDN against agreed decision criteria, supported by SE evidence and the selected configuration, subject to commercial agreement.','term-association-sales-contact':'The sales contact for an associated account; captured separately from its technical contact.'})
 DEFINITION_EXAMPLES['term-technical-win']='The customer confirms DDN is its preferred technical solution after reviewing the agreed criteria and configuration; commercial agreement is still pending.'
 def add(id,title,stages,source,definition,reminder,scenario,steps,questions,weak,strong,goal,practice,model,question,answer,takeaway):
  MODULES.append(dict(id=id,title=title,stages=stages.split(),owner='Sales · cross-functional deal team',source=source,definition=definition,distinction=takeaway,reminder=reminder,scenario=scenario,steps=steps,questions=questions,weak=weak,strong=strong,practice=practice,check=question,answer=answer,note=''))
  DESIGN[id]=dict(goal=goal,practice=practice,model=model,question=question,answer=answer,takeaway=takeaway)
  TERM_TITLES[id]=title;DEFINITION_TEXT[id]=definition
 add('meetings','Customer meetings and follow-up','s0 s1 s2 s3 s4 s5 s6 s7 s8 post ongoing','ongoing-meetings-detail',
 'Meeting Tasks connect a customer conversation to its owner, date, account or deal, outcome and next actions. Synergy can create follow-up Tasks by voice; calendar sync is still outstanding.',
 ['Choose the existing meeting Type; name the purpose, owner, date and customer/deal.','Record what happened, then complete the held meeting and assign separate follow-ups.','Review Synergy voice-created Tasks before saving; keep calendar invitations current separately.'],
 'After a lab discovery call, the AE records the funding condition and agreed next steps on the meeting Task. The AE uses Synergy to draft a technical workshop follow-up for the SE, checks the owner and due date, and updates the deal’s Next Step. The calendar invite is handled separately.',
 ['Prepare the meeting — Create one Task using Meeting: Phone, Meeting: Face to Face or Meeting: Video Conference. Set Subject, owner, Due Date, customer/deal link and agenda in Comments. Keep meeting times and invitations in the calendar.','Track the actual event — Reschedule the same Task if the meeting moves. Record cancellation or no-show with the supported status/disposition; do not count it as held.','Capture the result — Add outcome, decisions and risks in Comments. Complete the held-meeting Task after recording the result; an invitation alone does not mean the meeting happened.','Assign the follow-up — Create separate action Tasks with owner and due date, manually or through Synergy voice. Verify links and dates, and update Next Step / SE Next Step when the agreed next action changes.'],
 ['What decision or progress should this meeting produce?','Who owns each agreed action, and by when?'],
 'Meeting completed because an invitation was sent; next step: follow up.',
 'Held discovery call; funding depends on finance review. SE owns sizing workshop by Friday; AE owns finance introduction by Tuesday; customer/deal links verified.',
 'Record a customer meeting and turn its outcome into clear, owned follow-up.',
 'The customer misses a video meeting. Synergy drafted a follow-up assigned to the wrong person. What should you do?',
 'Record the no-show using the supported disposition and avoid counting the meeting as held. Correct the drafted Task owner, due date and customer/deal link before saving; arrange the new invitation separately.',
 'Does a saved Task or Synergy voice follow-up automatically synchronize the calendar or advance the sales stage?',
 'No. Calendar sync remains outstanding. Tasks record activity and actions; stage advancement still requires its own evidence and gates.',
 'Every meeting needs a purpose and an outcome; every follow-up needs an owner and date.')
 add('account-context','Account tier and coverage','creation s0 s1 ongoing','account-management',
 'Account Tier classifies an account as Tier 1, Tier 2 or Tier 3. Partner coverage and the partner’s admin contact live on the Account; RevOps Notes provides restricted operational context.',
 ['Use the agreed Account Tier; do not guess a tier from deal size.','Keep partner manager, technical lead and Partner Admin Contact current.','RevOps owns RevOps Notes; a contact or team role does not grant approval rights.'],
 'A partner account changes coverage. Partner Ops updates the DDN partner manager and technical lead. Active opportunity associations bring the correct people onto deal teams within their coverage, while accepted source and booked credit remain intact.',
 ['Confirm the account — Use the correct customer or partner account and check existing ownership and history.','Set the tier — Select Tier 1, Tier 2 or Tier 3 using the agreed criteria; ask Sales Ops or RevOps to resolve unclear assignments.','Maintain partner coverage — Partner Ops updates the commercial and technical owners plus Partner Admin Contact; validate active users and the contact’s account.','Use the right notes — Sales keeps customer/deal evidence in its normal fields. RevOps maintains restricted RevOps Notes; access follows the permissions matrix.'],
 ['Which agreed criteria support this tier?','Who owns commercial and technical coverage for this partner?'],
 'Set Tier 1 because the opportunity is large; give the admin contact approval access.',
 'Tier follows agreed account criteria; active coverage owners and the partner admin contact verified; no approval entitlement inferred.',
 'Maintain account context without confusing segmentation, coverage and authority.',
 'A new Partner Admin Contact requests authority to approve pricing. Does adding that contact grant it?',
 'No. Partner Admin Contact is a relationship. Pricing approval follows the existing authority matrix and explicit entitlements.',
 'Can an assigned partner overlay change forecast or approve a registration simply because it is on the opportunity team?',
 'No. Team membership provides scoped collaboration only; those actions require separate authority.',
 'Account context tells the team who is involved; explicit permissions determine what each person can do.')

 from sales_ops_updates import learning
 learning(MODULES,DESIGN,DEFINITION_TEXT,DEFINITION_EXAMPLES)
 from audit_updates import learning as audit_learning
 audit_learning(MODULES,DESIGN,DEFINITION_TEXT,DEFINITION_EXAMPLES)

STREAM_OVERVIEWS={
 'start-the-deal':dict(
  overview='Learn how to turn an introduction into a traceable, owned and qualified opportunity. Follow the correct intake path, establish the customer problem and funding context, and separate the source of the deal from how it will transact.',
  learn=['Identify the real origin and sourcing reference, including partner registration scenarios.','Review SAL acceptance and apply CHAMPS at the correct inbound or seller-direct gate.','Confirm account tier, coverage, use case, route to market and the first qualified pipeline milestone.'],
  takeaway='An actionable handoff: correct account and source, a responsible seller, supported qualification and a clear next conversation.',
  apply='Use this stream when creating a deal, reviewing a handoff or preparing to enter Discovery.'),
 'work-the-deal':dict(
  overview='Learn how to turn initial interest into customer-supported evidence for DDN. Connect pain and decision criteria to the technical evaluation, build access to the buying team, and coordinate partners and customer actions while making risks visible.',
  learn=['Develop pain, technical and operational value, a champion, economic-buyer access and a decision path.','Run a purposeful POC and distinguish technical fit from customer-confirmed Technical Win.','Maintain meeting outcomes, owned follow-ups, partner plans, product requests and an accurate view of progress.'],
  takeaway='A supported deal position: the customer’s criteria, preferred solution, decision owners, unresolved blockers and dated next actions.',
  apply='Use this stream during discovery follow-up, solution design, buyer alignment and weekly deal reviews.'),
 'close-the-deal':dict(
  overview='Learn how to convert an agreed solution into a controlled commercial decision and a clean order handoff. Connect the business case, quote, procurement plan and delivery expectations so the deal can progress on evidence.',
  learn=['Build Business Value and a Paper Process with customer-owned milestones.','Choose Budgetary or Best and Final appropriately and satisfy technical, pricing and procurement controls.','Confirm the transacting partner, logistics, won/lost evidence and the information needed by Order Management.'],
  takeaway='A reconciled commercial package: the right quote, customer commitments, required evidence and accountable handoff owners.',
  apply='Use this stream when preparing pricing, negotiating, coordinating procurement or recording the customer’s decision. Early Budgetary quoting is included.'),
 'grow-the-deal':dict(
  overview='Learn how to carry the customer commitment through booking, delivery, deployment and value confirmation. Keep the sales record accurate while GSS manages execution and evidence on the coordinating Case, giving the account team a grounded basis for the next customer conversation.',
  learn=['Distinguish a customer won decision, OM booking and verified delivery-led completion.','Coordinate order, receiving and deployment responsibilities without reopening booked sales facts.','Plan the value assessment, record customer-confirmed results or gaps, and calculate Time to Value from the correct milestone.'],
  takeaway='A documented customer outcome: delivery evidence, deployment ownership, measured value and agreed follow-up where gaps remain.',
  apply='Use this stream for the post-decision handoff and customer outcome reviews. It does not introduce a new renewal workflow.')}
