"""Authored teaching content. Rules are grounded in the linked system sections.
Examples are fictional; questions and coaching methods are teaching guidance.
"""
MODULES = []
def lesson(id, title, stages, owner, source, definition, distinction, reminder, scenario, steps, questions, weak, strong, practice, check, answer, note=''):
    MODULES.append(dict(id=id,title=title,stages=stages.split(),owner=owner,source=source,definition=definition,distinction=distinction,reminder=reminder.split('|'),scenario=scenario,steps=steps.split('|'),questions=questions.split('|'),weak=weak,strong=strong,practice=practice,check=check,answer=answer,note=note))

lesson('source','Opportunity source and sourcing credit','creation s0','Sales · Marketing · BDRs · Partners','creation',
'Opportunity Source records where the opportunity originated. Its matching sourcing reference identifies the credited user, campaign or partner.',
'Source describes origin; Opportunity Owner describes accountability; Route to Market describes how the sale will transact.',
'Confirm the original intake path.|Direct or BDR: identify the Sourcing User. Marketing: identify the Sourcing Campaign. Other nonblank sources: identify the Sourcing Partner.|Preserve origin when ownership changes.',
'A BDR identifies a research lab and hands it to an AE. The AE creates the record from the handoff. They retain BDR as the source and the originating BDR as Sourcing User. The new AE owns the deal; that assignment does not turn the source into Direct.',
'Trace the introduction — Review the originating handoff or registration and identify the source evidence before creation.|Select the matching reference — Link the actual originating person, campaign or partner. A background integration user is not the sourcing person.|Resolve ambiguity — If the handoff lacks its source reference, resolve it with the originating team before creating the opportunity. Do not select a convenient substitute.|Carry the history — Review source and ownership separately at handoff. Authorized corrections should preserve the prior attribution and reason.',
'Who initiated this opportunity?|Which original handoff, campaign or registration supports that attribution?',
'Direct, because the AE entered the record.',
'BDR source; originating BDR linked; assigned AE owns the opportunity; handoff evidence retained.',
'A Marketing campaign produces a lead that a partner later helps fulfill. Identify the source, sourcing reference and which later relationship should be captured separately.',
'Does a new AE assignment change Opportunity Source?',
'No. Preserve the originating source and sourcing reference. Assignment and fulfillment are separate concepts.',
'The future MAP move from Sourcing Campaign to Marketing Source is not part of the current field change. Continue using the existing campaign reference until that migration is confirmed.')

lesson('conversion','MQL, AQL, SAL and SQL','creation s0 s1','Marketing · BDRs · Partners · Sales · RevOps','ongoing-conversion-detail',
'MQL and AQL are distinct Contact qualification paths. Opportunity creation records SAL; first entry to Discovery records SQL for the relevant opportunity and linked Contact episode.',
'SAL is a lifecycle milestone. Seller acceptance is a separate decision. MQL and AQL are not mandatory sequential steps.',
'Keep MQL and AQL paths distinct.|Record SAL at creation and SQL at first Stage 1 entry.|Preserve each opportunity episode and the originating Contact.',
'PAX.AI qualifies a prospect as AQL. An opportunity is created in Validate, recording SAL. After seller acceptance and CHAMPS qualification it enters Discovery, recording SQL. The team can explain the AQL-to-SAL-to-SQL path without inventing an MQL event.',
'Identify the path — Establish whether qualification came from Marketing, PAX.AI, a BDR, a partner or the seller.|Resolve the person — Associate the designated originating Contact with the opportunity and correct account context. Do not update every committee member as a conversion.|Follow the milestones — For inbound intake, creation records SAL, then acceptance and qualification enable SQL. A seller-qualified direct Stage 1 creation records SAL and SQL together.|Protect reporting — Retain the episode, source and history. Do not fabricate earlier events or downgrade an existing customer lifecycle because another opportunity begins.',
'Which Contact was qualified for this opportunity?|Was the opportunity inbound or genuinely seller-self-qualified?',
'Every SQL must first be recorded as both MQL and AQL.',
'AQL → SAL → SQL, with separate seller-acceptance evidence and one linked opportunity episode.',
'Compare a campaign-sourced inbound opportunity with a seller-qualified direct Stage 1 opportunity. Describe the legitimate milestones for each.',
'Can a seller-direct SQL be counted as a Marketing conversion without evidence of MQL?',
'No. Seller-direct SQLs remain a separate cohort. Record SAL and SQL for that direct entry without manufacturing MQL or AQL history.',
'PAX.AI is a qualification channel, not a newly approved Opportunity Source choice. Its underlying source mapping remains a RevOps dependency.')

lesson('sal-review','Review and accept a SAL','s0 s1','Assigned AE · Marketing · BDRs · Partners','s0',
'SAL review is the assigned seller’s explicit acceptance or rejection of an opportunity handoff, separate from the SAL creation milestone.',
'Accepted does not itself mean qualified for Stage 1. Assignment and the inbound CHAMPS requirements must also be satisfied.',
'Review the original handoff and seller assignment.|Record the acceptance or rejection decision and supporting context.|For inbound intake, complete all five CHAMPS answers before Stage 1.',
'An AE receives an attractive lab opportunity but the handoff has no funding information. The AE accepts responsibility, then works with the BDR to complete Money and the remaining CHAMPS evidence. They enter Discovery only after the inbound gate is complete.',
'Read the handoff — Confirm customer context, source, originating Contact and accountable seller.|Assess the disposition — Decide whether to accept the handoff. When rejecting, explain the specific gap so the originating team can learn or act.|Complete qualification — For inbound intake, review Challenge, Authority, Money, Priority and Stack / Storage. Acceptance does not substitute for these answers.|Document the decision — Use the supported acceptance/rejection process so actor and time are recorded. Marketing SAL rejection requires date and notes; acceptance requires its date.',
'What evidence makes this handoff actionable?|What is missing, and who can resolve it?',
'Accepted; moved to Discovery although CHAMPS is incomplete.',
'Accepted by the assigned AE; source and Contact verified; all five inbound CHAMPS answers supported before SQL.',
'Write a useful rejection note for an inbound record with no identifiable project or relevant customer need.',
'Does rejecting a SAL automatically make it Closed lost?',
'No. Rejection remains a distinct SAL disposition and does not create SQL or automatically close the opportunity as lost.',
'Existing SAL Status choices and date mappings must be verified in the system. Do not assume SAL Start Date means acceptance or SAL Completion Date means rejection.')

lesson('challenge','CHAMPS: Challenge','s0 s1','BDRs · Partners · Marketing · AE','s0',
'Challenge is the customer-evidenced problem that establishes why the opportunity deserves qualification.',
'Challenge captures the initial problem. Identify Pain later develops its impact and business consequences.',
'Ask about a specific problem, not a product request.|Record who experiences it and a recent example.|Inbound: before Stage 1. Seller-qualified direct entry: before Stage 2.',
'A lab requests more storage. The BDR asks what triggered the request. The researcher explains that datasets wait overnight before processing. The handoff now describes delayed analysis rather than simply “needs more capacity.”',
'Start with the trigger — Ask what happened that caused the customer to seek a change.|Locate the impact — Identify the team, workload and recurring interruption. Separate observation from assumption.|Check understanding — Restate the problem in the customer’s words and invite correction.|Record evidence — Capture the situation and source in CHAMPS Challenge. Carry the answer into deeper pain discovery without replacing it.',
'What happened the last time this became a problem?|Who is affected and what do they have to do differently?',
'Customer needs a faster product.',
'Research team reports overnight data staging delays before each analysis run; lab manager confirmed the workflow.',
'Turn “our storage is old” into two discovery questions and an evidence-based Challenge statement.',
'Should Stage 2 Identify Pain overwrite the original CHAMPS Challenge?',
'No. Retain Challenge and develop the deeper impact separately in Identify Pain.')

lesson('authority','CHAMPS: Authority','s0 s1','BDRs · Partners · Marketing · AE','s0',
'Authority records what is known about the contact’s decision influence and access to the people who can approve the project.',
'An influential evaluator is not automatically the Economic Buyer. Early authority discovery identifies the path to decision makers.',
'Establish the contact’s role in the decision.|Ask who approves funding and who evaluates the solution.|Record evidence and remaining access gaps.',
'A storage architect can recommend the design but says the infrastructure director owns the budget. The AE records both roles and asks the architect to arrange a joint discussion rather than describing the architect as the budget holder.',
'Understand involvement — Ask how the contact participated in the last comparable purchase.|Map the limits — Separate recommendation, technical veto, budget authority and signature responsibilities.|Find the access path — Agree how to involve the relevant decision makers and record any uncertainty.|Document the handoff — Capture the known roles in Authority; refine the buying committee as discovery progresses. Complete inbound CHAMPS before Stage 1 or seller-direct CHAMPS before Stage 2.',
'Who else needs to agree for this project to happen?|Who could approve or stop the spend?',
'Senior title, so probably the decision maker.',
'Architect owns technical recommendation; director controls project budget; introduction requested.',
'A friendly contact says “I decide everything” but needs a finance review. Draft questions that establish the scope of their authority.',
'Is job seniority enough to confirm economic authority?',
'No. Validate the person’s actual role and approval limits in this purchase.')

lesson('money','CHAMPS: Money','s0 s1','BDRs · Partners · Marketing · AE','s0',
'Money captures evidence of funding, funding access and the customer’s commercial capacity for the proposed project.',
'A funding hypothesis is different from an approved budget. Record the status accurately rather than treating an estimate as approval.',
'Ask how the project will be funded.|Separate known budget, estimates and approval conditions.|Document the source of the funding evidence.',
'A customer estimates a $400,000 project but says approval depends on a business case. The seller records the estimate and its approval condition. They do not call the funding approved simply because a number was discussed.',
'Explore the mechanism — Ask whether the project uses an allocated budget, a new request or another funding route.|Establish the status — Clarify which amounts are confirmed and which are estimates; identify the approving person.|Identify the condition — Learn what evidence is needed for funding and when the decision can occur.|Record faithfully — Capture the amount or commercial capacity evidence, funding status and unresolved conditions in Money. Apply the source-dependent CHAMPS timing.',
'Is this funding allocated or still being requested?|What must be demonstrated for the funding to be approved?',
'Budget: $400,000 approved.',
'Customer estimate: $400,000; funding request depends on finance accepting the business case.',
'Rewrite “budget available” into a statement that distinguishes evidence from the assumption you still need to test.',
'Does a customer’s rough estimate prove budget approval?',
'No. Capture it as an estimate and identify the approval conditions and responsible person.')

lesson('priority','CHAMPS: Priority','s0 s1','BDRs · Partners · Marketing · AE','s0',
'Priority is the urgency and business importance of addressing the customer’s challenge.',
'A seller’s quarter-end target is not evidence of customer urgency.',
'Identify the customer’s event or deadline.|Explore the consequence of delay.|Confirm priority relative to competing projects.',
'A lab wants the platform before a new research program starts in January. Missing that date would delay onboarding. The AE records the program milestone and consequence, then checks whether funding and installation can realistically support it.',
'Find the event — Ask why the customer is addressing the issue now and which business activity depends on it.|Test the consequence — Explore what happens if the project is delayed or no change is made.|Compare priorities — Ask what other initiatives compete for the same people, funds and approval time.|Record a supported timeline — Capture the event, impact and customer confirmation in Priority. Complete it at the appropriate inbound or seller-direct CHAMPS gate.',
'What changes if this is not solved by that date?|Where does this sit among the team’s other funded priorities?',
'Must close this quarter.',
'January program launch requires the new workflow; director confirms a delay would postpone researcher onboarding.',
'A prospect says “ASAP.” Write three follow-up questions that turn this into a usable priority assessment.',
'Can the seller’s forecast date substitute for a customer deadline?',
'No. The priority needs customer evidence and a consequence of delay.')

lesson('stack','CHAMPS: Stack / Storage','s0 s1','BDRs · Partners · AE · Sales Engineering','s0',
'Stack / Storage captures the current environment and relevant storage or technical requirements that establish technical relevance.',
'Early qualification identifies context; it does not commit to a final configuration or assert a Technical Win.',
'Understand the current workload and environment.|Identify the storage constraint and dependencies.|Separate customer facts from items the SE still needs to validate.',
'A lab uses shared storage for ingest and model training. The BDR captures capacity, workload patterns and a reported ingest bottleneck, then flags throughput validation for the SE. They avoid prescribing a configuration during intake.',
'Map the workflow — Follow the data from creation through storage, processing and access.|Identify constraints — Ask about capacity, performance, integration and migration concerns relevant to that workflow.|Capture the evidence quality — Distinguish measurements from customer estimates and secondhand claims.|Hand off intelligently — Record the environment in CHAMPS and the questions needing SE validation. Complete the appropriate qualification gate without presenting estimates as test results.',
'Where does the workload slow down today?|Which applications, interfaces or migration dependencies must be supported?',
'Needs high-performance storage.',
'Shared storage supports ingest and training; reported ingest bottleneck needs validation with the customer workload.',
'Create a short technical handoff from an intake conversation containing one measured fact and two unverified estimates.',
'Does completing Stack / Storage select the final design?',
'No. Configuration development occurs in Solution design and converges during Buyer alignment.')

lesson('use-case','Discover the use case','s1','AE · Sales Engineering','s1',
'Use Case describes what the customer intends to accomplish with the solution; supporting information captures the workload and expected outcomes.',
'A product family describes what is sold. A use case describes what the customer will do with it.',
'Name the customer workflow and its users.|Connect the workflow to the intended outcome.|Complete discovery and AE/Primary SE assignment before Stage 2.',
'A prospect asks about storage capacity. Discovery reveals that the requirement supports a new AI training pipeline, with researchers waiting for data preparation. The seller records the use case and context so the SE can design for the actual workflow.',
'Walk the workflow — Ask the customer to describe the activity from input to result and identify its users.|Connect the outcome — Explore what a successful change enables for those users and why that matters.|Choose and explain — Select the appropriate Use Case and add the specific workload, constraints and intended result in Additional Use Case Information.|Coordinate discovery — Confirm the assigned AE and Primary SE, complete CHAMPS at its required timing, and establish at least one Contact Role before Stage 2.',
'What will your users be able to do after this change?|Which workload should our design be evaluated against?',
'Use case: storage.',
'AI model training; researchers need faster dataset preparation to reduce idle time between experiments.',
'Turn a list of requested product specifications into a customer-centered use-case description.',
'Is a product name alone an adequate use-case description?',
'No. Capture the customer activity, relevant users and intended outcome.')

lesson('route','Choose the route to market','s1','AE · Partner Managers','s1',
'Route to Market describes whether the opportunity will transact directly or indirectly. Indirect Route Type specifies the indirect motion.',
'Transaction route does not rewrite the original Opportunity Source or establish partner-contribution credit.',
'Confirm how the customer expects to buy.|For Indirect, select the applicable Indirect Route Type.|Keep route separate from origin and partner contribution.',
'A Marketing-sourced customer chooses to purchase through a reseller. The AE keeps Marketing and the original campaign as sourcing attribution, sets Route to Market to Indirect, and selects the applicable indirect type.',
'Ask about purchasing — Establish whether the customer buys from DDN or through another party.|Validate participants — Confirm the commercial role of the partner and involve the Partner Manager when needed.|Record the route — Complete Route to Market during discovery. Indirect requires its type; Direct does not require a second selection.|Handle changes — If the route changes to Direct, the old indirect type no longer drives current attribution; retain its history rather than rewriting origin.',
'Which entity will the customer place the order with?|Has that purchasing route been confirmed by the customer?',
'Changed source to Channel Partners because the customer will buy through a reseller.',
'Marketing origin retained; Indirect route and its type reflect the confirmed reseller transaction.',
'Explain the source and route for a BDR-origin opportunity that later transacts through a partner.',
'Does Direct require an Indirect Route Type?',
'No. Indirect Route Type applies only when Route to Market is Indirect.')

lesson('pain','Identify Pain','s2','AE · Sales Engineering','s2',
'Identify Pain develops the customer’s initial challenge into a specific problem with validated consequences and reasons to act.',
'Keep the earlier CHAMPS Challenge. Identify Pain deepens it; Business Value later quantifies the economic case.',
'Follow the problem through to its consequence.|Validate who is affected and how often.|Complete before Stage 3 alongside the technical-fit evidence.',
'The lab’s overnight staging delay sounds inconvenient. The AE learns it causes missed processing windows and repeat scheduling work. The customer confirms the impact. The opportunity now explains why the problem matters rather than relying on a generic performance claim.',
'Revisit Challenge — Begin with the original customer problem so the customer does not have to restart discovery.|Follow the effects — Ask what the disruption prevents, how frequently it occurs and who bears the consequence.|Validate significance — Ask the customer to correct your summary and distinguish proven impact from your hypothesis.|Record the pain — Save the evidence in Identify Pain and use it to guide technical evaluation and the later value case.',
'What happens downstream when this delay occurs?|If the problem continues, what outcome is at risk?',
'Customer unhappy with incumbent.',
'Lab manager confirms staging delays cause missed processing windows and extra rescheduling each week.',
'Develop a pain statement from “performance is slow” without inventing a financial impact.',
'Where should the initial CHAMPS Challenge go after pain discovery?',
'It stays in its existing field. Identify Pain carries the developed impact separately.')

lesson('competition','Understand competitors and the status quo','s2 lost','AE · Sales Engineering','s2',
'Competitor discovery identifies the alternatives the customer is considering, including retaining the current approach.',
'Incumbent vendors are what the customer uses today; Competitor Lost To records the outcome at loss. Those may differ.',
'Ask which alternatives are actually being evaluated.|Include the do-nothing or incumbent alternative in the conversation.|When Other is selected, provide the company name.',
'A customer compares DDN with two vendors but says keeping the existing platform is also possible. The AE asks what would make each path acceptable and records the verified competitors, keeping incumbent use distinct from active evaluation.',
'Invite comparison — Ask which approaches the customer is considering and why each remains credible.|Test the status quo — Explore what would cause the customer to defer the project or stay with the incumbent.|Connect to criteria — Discuss how the alternatives will be assessed using the customer’s decision criteria instead of unsupported claims.|Document precisely — Complete Stage 2 competitor capture before Stage 3. If Other is used, record the company name; at loss, separately identify the actual outcome.',
'What alternatives remain on the shortlist?|What would make you keep the current approach?',
'Competition: probably the incumbent.',
'Customer-confirmed shortlist recorded; current incumbent distinguished from active alternatives; Other vendor named.',
'A customer cancels a project without selecting a vendor. Explain how this differs from losing to the incumbent.',
'At loss, must a vendor be invented if no competitor won?',
'No. Use the permitted Not lost to competitor outcome and explain the actual reason.',
'The shared competitor taxonomy still requires approval in the source. Do not invent new picklist choices.')

lesson('technical-value','Build Technical Value','s2 s3','Sales Engineering · AE','s2',
'Technical Value explains technical fit and configuration choices in Stage 2, then identifies the one selected configuration in Stage 3.',
'Technical Value describes the solution’s fit. Technical Outcome records the evaluation result; Operational Value describes the operational improvement.',
'Connect configuration choices to customer requirements.|Compare alternatives during Stage 2.|Before Technical Win, identify the selected configuration and supporting evidence.',
'The SE compares two configurations for the lab’s workload. Testing and customer discussion establish which fits the agreed requirements. In Buyer alignment, the SE records the chosen version and links its supporting evidence so quoting and handoff use the same design.',
'Translate requirements — Connect the customer workload and Decision Criteria to capabilities the design must demonstrate.|Explore options — Document why each candidate configuration may fit, what is uncertain and what validation is needed.|Converge with the buyer — Review the evidence with the customer, select one configuration and identify its version.|Keep a coherent record — Update Technical Value and the supporting SharePoint material together. Before recording Technical Win, the SE confirms the substance of the chosen design.',
'Which requirement does this configuration satisfy?|What evidence supports the selection over the other option?',
'The solution is fast and scalable.',
'Selected configuration B, version 3; workload validation and agreed requirements linked; remaining dependencies documented.',
'Write a short recommendation comparing two configurations against three customer criteria, then name the evidence needed to select one.',
'Does nonblank Technical Value text by itself prove technical fit?',
'No. The SE must confirm the technical substance and supporting configuration evidence.')

lesson('champion','Validate a champion','s2','AE · Sales Engineering','s2',
'A Champion is the internal customer advocate whose support has been tested through observable actions that help the opportunity advance.',
'A friendly contact is a possible advocate. Economic authority is a separate role and must be confirmed independently.',
'Look for advocacy in action.|Understand why this person wants the outcome.|Validate the relationship before Stage 3.',
'A lab architect likes the solution. The AE asks them to bring the infrastructure director into a value discussion. The architect arranges the meeting and explains the internal approval concerns. Those actions provide stronger evidence of advocacy than enthusiasm alone.',
'Understand the motivation — Ask what the project changes for this person and why they care about its success.|Assess their reach — Explore who trusts their recommendation and where their influence is limited.|Agree a useful action — Ask for a relevant introduction, feedback on the case or help navigating a real buying step. Treat this as evidence gathering, not a new system gate.|Document observed support — Record the person, their motivation, actions and remaining gaps in Champion before Stage 3. Reassess as the deal changes.',
'Who needs to understand this case internally?|Can we review the proposal together before you discuss it with the decision team?',
'Champion: likes us.',
'Architect convened the director meeting, explained approval concerns and helped validate the evaluation plan.',
'Choose one observable action that would help you evaluate an enthusiastic contact’s ability to advocate internally.',
'Does enthusiasm prove that a contact is a champion?',
'No. Use observable advocacy and influence as evidence; keep untested assumptions explicit.')

lesson('criteria','Establish Decision Criteria','s2','AE · Sales Engineering','s2',
'Decision Criteria describe how the customer will evaluate the available options.',
'Criteria are what the buyer evaluates. Decision Process describes who decides, in what sequence and when.',
'Ask the customer to define success for the evaluation.|Make criteria specific enough to compare alternatives.|Complete before Stage 3.',
'The lab initially asks for “better performance.” The SE helps define an evaluation using representative workloads, capacity requirements and integration needs. The customer confirms what will count as acceptable, making the comparison repeatable.',
'Collect requirements — Build on CHAMPS Money, Priority and Stack / Storage and the established use case.|Make them assessable — Ask how each requirement will be judged and what evidence is acceptable.|Validate tradeoffs — Discuss which criteria are decisive and how conflicts will be resolved. Avoid presenting seller preferences as buyer requirements.|Record agreement — Capture the criteria and their customer source; connect the technical evaluation and any POC to them.',
'How will you determine whether an option meets this requirement?|Which criteria could eliminate an otherwise strong solution?',
'Fast, cheap and easy.',
'Customer-confirmed workload, capacity and integration criteria with an agreed evaluation approach.',
'Turn three adjectives from a customer request into evaluation questions that can produce usable evidence.',
'Is the signature sequence a Decision Criterion?',
'No. It belongs in the decision or paper process. Criteria describe how options are evaluated.')

lesson('technical-outcome','Confirm the Technical Outcome','s3','Sales Engineering · AE','s3',
'Technical Outcome records Technical Win or Technical Loss after evaluation. Technical Win is required before Stage 4.',
'A completed POC is a process state; it does not automatically establish a Technical Win.',
'Confirm one selected configuration.|Review the evidence against customer requirements.|Record Technical Win only when justified; Technical Loss does not pass the Stage 4 gate.',
'A POC is complete, but an integration requirement remains unmet. The SE explains that completion alone is not a technical win. The team resolves the issue and validates the selected configuration before recording Technical Win and moving toward proposal.',
'Collect the evaluation — Review Decision Criteria, tests, configuration versions and any required POC disposition.|Resolve the selection — Establish which single configuration is being proposed and ensure supporting documents match it.|Assess the outcome — The SE determines whether the evidence supports Technical Win or Technical Loss. Do not let a populated field substitute for judgment.|Complete Buyer alignment — Before Stage 4, also confirm Operational Value, Economic Buyer and Decision Process alongside Technical Value.',
'Which evidence shows the selected configuration meets the criteria?|What technical issue could still change the customer’s decision?',
'POC completed, therefore Technical Win.',
'SE-confirmed Technical Win for selected configuration B v3, supported by the customer evaluation evidence.',
'A test is complete but the buyer disputes the results. Describe what needs resolution before recording a win.',
'Can Technical Loss pass the Stage 3 → 4 gate?',
'No. Technical Outcome must be Technical Win, with the other Stage 3 requirements complete.')

lesson('operational-value','Establish Operational Value','s3','AE · Sales Engineering','s3',
'Operational Value captures the expected operational outcome, its baseline, target and measurement expectations.',
'Technical Value explains fit; Operational Value describes a measurable workflow improvement; Business Value expresses the economic case.',
'Establish the current baseline.|Agree the target improvement and how it will be measured.|Complete during Buyer alignment before Stage 4.',
'The fictional lab spends eight hours staging a dataset. The customer agrees to evaluate a two-hour target using the same dataset and conditions. The AE and SE record the baseline, target and measurement approach, distinguishing the target from an achieved result.',
'Define the activity — Choose the customer workflow whose improvement matters, using the earlier pain and use-case evidence.|Establish the baseline — Ask how current performance was measured, by whom and under what conditions. Label estimates honestly.|Agree a target — Validate the desired outcome with the customer and define a comparable measurement approach and responsible participant.|Document and hand off — Record the baseline, target and measurement expectations in Operational Value before Stage 4. Carry them forward to the GSS value plan.',
'What is today’s measured result for this workflow?|How will we both know that the improvement has occurred?',
'Improve performance significantly.',
'Reduce dataset staging from 8 hours to a customer-agreed 2-hour target, measured on the same representative dataset.',
'Rewrite “make operations more efficient” with a baseline, target and measurement plan. Mark any unknowns instead of inventing values.',
'Does an agreed target mean the value has already been achieved?',
'No. It is a planned outcome. GSS later confirms actual results and evidence on the Case.',
'The Operational Value field is proposed in the system specification. Its final storage mapping requires confirmation; this lesson teaches the concept without claiming the control is live.')

lesson('economic-buyer','Confirm the Economic Buyer','s3','AE','s3',
'The Economic Buyer is the person who controls the budget for the customer’s purchase.',
'Technical approval, advocacy and contract signing do not necessarily establish budget authority.',
'Identify who controls the relevant budget.|Validate authority for this particular purchase.|Complete before Stage 4.',
'The architect recommends the design, procurement handles the order, and the infrastructure director decides whether to allocate the funds. The AE records the director as Economic Buyer and engages them on the business outcome.',
'Use the authority map — Revisit early CHAMPS Authority and identify which roles remain assumptions.|Validate the budget decision — Ask who can approve the allocation and what approval limits or dependencies apply.|Engage on value — Discuss the outcome and economic justification relevant to that person, using the customer’s context.|Record evidence — Name the buyer and authority evidence in Economic Buyer and maintain their Contact Role when appropriate. Establish this before Stage 4.',
'Who can authorize the budget for this purchase?|What evidence does that person need to commit the funds?',
'Procurement contact signs the paperwork, so they own the budget.',
'Infrastructure director controls project allocation; procurement executes the purchasing process.',
'A CFO signs all contracts, but the business unit director controls the project budget. Describe what you would verify before naming the Economic Buyer.',
'Is the person who signs the contract always the Economic Buyer?',
'No. Confirm actual budget control for the opportunity rather than inferring it from signature authority.')

lesson('decision-process','Map the Decision Process','s3','AE · Sales Engineering','s3',
'Decision Process is the customer’s sequence of decision steps, participants and timing for selecting a solution.',
'Paper Process covers the legal, procurement, signature and PO steps needed to transact after or alongside selection.',
'Map who decides what and when.|Identify dependencies between decision steps.|Confirm the sequence with the customer before Stage 4.',
'The lab first requires technical approval, then the director reviews the value case, then a steering committee selects the vendor. The AE maps the sequence and confirms the committee date rather than assuming a successful test immediately produces an order.',
'Start from the decision — Ask the buyer to describe how a comparable purchase was approved.|Map each step — Identify its owner, participants, expected date and the evidence needed to complete it.|Test dependencies — Ask what could delay a step and whether another approval must happen first.|Validate and maintain — Review the map with the buyer and update Decision Process before Stage 4; use it to support realistic next steps and close-date discussions.',
'What must happen between technical approval and vendor selection?|Who participates in the final selection, and when do they meet?',
'Customer will decide soon.',
'Technical review → director value review → steering committee selection, with participants and dates confirmed.',
'Draw a three-step decision map and identify one dependency that could make the current close date unrealistic.',
'Is an internal seller close plan sufficient evidence of the buyer’s Decision Process?',
'No. Validate the actual customer sequence, participants and timing.')

lesson('business-value','Build the Business Value case','s4 s6','AE · Sales Engineering','s4',
'Business Value is the quantified economic justification for the purchase; at Won decision it is enriched with specific win-reason and ROI or cost-saving evidence.',
'Operational targets are inputs to the economic case. They do not automatically prove cash savings or revenue gains.',
'Connect the operational improvement to an economic outcome.|Show assumptions and validate them with the customer.|Complete before Stage 5 and enrich the same record at Won decision.',
'The fictional lab targets six hours less staging per run across twenty runs each month: 120 hours of elapsed staging time avoided. The AE checks whether those hours represent staff effort, machine availability or waiting time before making a financial claim. The buyer validates the applicable economic model.',
'Start from the outcome — Use the agreed Operational Value baseline and target as evidence, not as an automatic financial benefit.|Build a transparent model — State quantities, frequency, unit value and assumptions. Separate elapsed time from labor and avoid double counting benefits.|Validate with the buyer — Ask the Economic Buyer or relevant finance participant to confirm what value counts and how costs should be compared.|Maintain the case — Record quantified Business Value before Stage 5. At Stage 6, add why the customer chose the solution and the supporting ROI or cost-saving evidence.',
'Which of these improvements creates an economic benefit you recognize?|Which assumptions would finance challenge?',
'120 hours saved, so 120 hours of salary eliminated.',
'120 elapsed staging hours avoided monthly; financial impact pending validation of affected resources and actual cost basis.',
'Build a simple benefit calculation and identify two assumptions that need customer confirmation before it can be called a business case.',
'Does faster elapsed processing automatically equal lower payroll cost?',
'No. Validate what resource or economic outcome changes and use an appropriate cost or benefit model.')

lesson('paper-process','Navigate the Paper Process','s4 s5','AE · Procurement and legal participants','s4',
'Paper Process documents the legal, procurement, signature and purchase-order steps needed to complete the transaction.',
'Customer selection is not the same as a completed procurement process or a secured PO.',
'Map legal, procurement, signatures and PO steps.|Identify owners, dates and dependencies.|Capture during Stage 4, before Stage 5.',
'The customer selects DDN but legal still needs a terms review and procurement requires vendor onboarding. The AE maps both tasks and their owners, then revises the expected close date to reflect the actual path to an order.',
'Ask the process owners — Engage procurement and legal contacts early enough to learn their actual requirements.|List deliverables — Identify vendor onboarding, agreements, approvals, signatures and PO issuance as applicable.|Build a workable sequence — Confirm who owns each step and which dates depend on another approval or document.|Keep it connected — Document Paper Process in Stage 4 and use it to prepare Stage 5 evidence. Review progress with the next customer action and expected close date.',
'What must procurement receive before it can issue a PO?|Which agreement review or signature is on the critical path?',
'Procurement should be quick.',
'Legal review owner and date confirmed; onboarding precedes PO issuance; signature authority identified.',
'A buyer promises a PO Friday, but legal review begins Thursday. Draft a clarification message that tests the date without making an unsupported commitment.',
'Does a verbal vendor-selection decision mean the Paper Process is complete?',
'No. Confirm the remaining legal, procurement, signature and PO steps.')

lesson('procurement','Complete procurement evidence','s5','AE · Sales Engineering','s5',
'Procurement completes the IPG disposition, shipping and delivery timing, secured PO and final agreements required before Won decision.',
'PO evidence and a won decision precede OM’s independent booking confirmation.',
'Secure and attach the PO; confirm final agreements.|Finalize IPG and capture shipping/delivery timing and notes.|Reconcile the package before Stage 6.',
'The buyer emails a PO, but its products differ from the Primary Quote. The AE and SE reconcile the discrepancy before the handoff. They attach the correct PO, confirm agreements and logistics, and provide a package OM can review.',
'Check the commercial package — Compare the PO, Primary Quote, products and amount. Resolve mismatches with the appropriate owner.|Complete disposition — Finalize and submit IPG or confirm an explicitly applicable Not Required disposition.|Confirm logistics — Capture Estimated Shipping Date, Requested Delivery Date and Delivery Notes, carrying forward the installation request.|Prepare the handoff — Link the PO through Salesforce Files, retain final agreements and verify the Stage 5 requirements before advancing to Won decision.',
'Do the PO and selected quote describe the same scope?|Which unresolved document or logistics dependency could prevent order acceptance?',
'PO received; everything else can be fixed after booking.',
'PO matched to quote and attached; agreements confirmed; IPG disposition and logistics recorded for review.',
'Review a fictional PO with the wrong quantity. Identify the correction and evidence needed before progressing.',
'Can the AE treat a received PO as OM booking confirmation?',
'No. OM must independently reconcile and confirm the order before Closed won.',
'Logistics applicability for renewals, software/services and No Shipping required orders is still to be confirmed by OM/GSS. Do not use fabricated dates or dummy Cases.')

lesson('won-decision','Record the won decision','s6','AE · Sales Engineering · Sales Manager','s6',
'Won decision records the customer’s win outcome, reconciles the order and initiates the deployment Case and logistics plan. Forecast remains Commit until booking.',
'Stage 6 is not Closed won. OM controls the later booking confirmation.',
'Capture Won Reason and specific Business Value detail on entry.|Confirm the win evidence and interview eligibility.|Start the deployment handoff while OM reviews the order.',
'The fictional lab selects DDN and the procurement package is complete. The AE records the win reason and quantified value evidence at Stage 6. GSS begins deployment planning, while OM checks the order. The team does not report a booked win until OM confirms Stage 7.',
'Explain the decision — Capture the customer-supported Won Reason and enrich Business Value with specific win detail and ROI or cost-saving evidence.|Complete conditional information — Record incumbent vendors. At amounts ≥$1M, name Resources Engaged. For New Business, Existing Business and Renewal, capture interview eligibility and the required Contact or reason.|Coordinate review — Give OM the products, amount, documents and delivery context needed to reconcile the order.|Start delivery planning — Create or link the coordinating deployment Case, involve GSS and agree the ownership and logistics needed before booking.',
'What customer evidence explains why we won?|Who needs the commercial, technical and value context to deliver successfully?',
'Customer said yes; mark Closed won immediately.',
'Won decision recorded with reason and evidence; OM review in progress; GSS deployment planning initiated.',
'Prepare a concise Stage 6 handoff that explains the customer decision, value, commercial package and remaining review work.',
'Which forecast category applies in Won decision?',
'Commit. The sales forecast becomes Won at Closed won, after OM booking confirmation.')

lesson('booking','Confirm booking and protect booked facts','s6 s7','Order Management · Sales · GSS','s7',
'Closed won is the OM-confirmed booked PO. Booking locks the booked facts and Close Date, and freezes automated partner-contribution credit.',
'A nonblank Order Review Status or any label containing “Booked” does not by itself prove the order is cleared to book.',
'OM confirms reconciliation before Stage 7.|Resolve Stage 6 quote discrepancies through the documented return to Stage 5.|After booking, use the existing amendment/change-order process.',
'OM finds a pricing mismatch at Stage 6. The reason is recorded and the opportunity returns to Stage 5 for CPQ correction. After revalidation, OM completes reconciliation and books the order. A later scope change follows the booked-order amendment process.',
'Reconcile the order — OM compares the quote, PO, products, amount and required agreements against the allowed booking criteria.|Resolve pre-booking discrepancies — Record the issue and return to Stage 5 when a quote correction is required. Revalidate procurement and Stage 6 entry requirements afterward.|Confirm authority and handoff — OM controls entry to Stage 7. Identify the GSS Case owner and delivery, receiving and installation plans before booking.|Protect the record — Preserve the locked Close Date and booked facts. Post-booking corrections follow the existing amendment process; a new sales quote uses a separately linked opportunity in Stages 2–5.',
'What remains unreconciled in the order package?|Has the deployment owner received the agreed scope and dependencies?',
'Order status contains Booked, so advance automatically.',
'OM reconciled the package against approved booking criteria, confirmed authority and locked the booked result.',
'Explain the different correction paths for a pricing error discovered before booking and one found afterward.',
'Can a booked opportunity be reopened simply to revise its CPQ quote?',
'No. Follow the existing change-order/amendment process; use a separately linked opportunity in Stages 2–5 when a new sales quote is needed.',
'RevOps and OM must approve the mapping of existing order statuses, exceptions and booking authority. This lesson does not invent allowed status values.')

lesson('invoice','Confirm delivery and invoice evidence','s7 s8','Order Management · GSS','s8',
'Stage 8 Invoice is the final Opportunity stage, reached when the complete in-scope order has been verified as delivered on site. Financial invoicing is tracked separately.',
'Shipment, customer receipt, invoice issuance, deployment completion and value achievement are distinct events.',
'Verify receipt for every non-cancelled booked item.|Partial deliveries remain in Stage 7.|Capture invoice references and dates when issued; pending invoicing does not block complete delivery.',
'Nine of ten booked units arrive at the customer site. OM keeps the opportunity in Stage 7. When the final unit is received and verified with GSS, it enters Stage 8 even though one financial invoice is still pending. GSS continues deployment on the Case.',
'Check the booked scope — Review every non-cancelled item and any approved scope changes on the Order.|Verify receipt — Obtain on-site delivery evidence with GSS; a carrier dispatch notice alone is insufficient.|Complete the Opportunity — Once the complete in-scope order is delivered, move to Stage 8 and preserve booked facts. Continue invoice reconciliation on the Order.|Maintain separate milestones — Capture Invoice Reference and Invoice Date when issued. Deployment and value assessment continue on the Case without reopening the Opportunity.',
'Has every in-scope item been received on site?|Which invoices remain to be issued or reconciled?',
'Carrier shipped the order; delivery complete.',
'Full on-site receipt verified; Stage 8 entered; outstanding invoice tracked on Order; deployment remains active on Case.',
'Classify shipment, partial receipt, full receipt and invoice issuance as separate milestones in a fictional order timeline.',
'Does a pending invoice prevent Stage 8 after complete on-site delivery?',
'No. Verified complete delivery controls the transition; invoice evidence is required when the invoice is issued.',
'Alternative completion evidence for non-shipping motions remains an OM/GSS decision. Do not invent physical delivery evidence for those orders.')

lesson('loss','Learn from a Closed lost opportunity','lost','AE · Sales Engineering · Sales Manager','lost',
'Closed lost records the loss decision, specific reason, competitive outcome, learning and appropriate follow-up.',
'A lost sale differs from a rejected SAL, an administrative duplicate or an unrealized outcome after a booked sale.',
'Confirm the actual loss decision and date.|Record reason, details, competitive outcome and next-step recommendation.|Capture conditional interview information and qualifying loss reports.',
'A customer stops its project after funding is withdrawn. The AE records the supported reason and explains the decision, rather than blaming an unconfirmed competitor. They recommend a future funding check and record whether a customer feedback interview is permitted.',
'Obtain decision evidence — Debrief the customer where possible and distinguish confirmed reasons from internal interpretation.|Record a specific explanation — Complete Loss Reason, Loss Reason Details, Competitor Lost To and Lost — Next Step Recommendation. Other competitor requires its name; Opportunity Misqualified applies only to losses from Stage 0.|Capture feedback access — For the applicable business types, record interview eligibility. Yes needs a Salesforce Contact; No needs the reason the team cannot approach.|Complete reporting — Confirm Close Date as the actual loss decision date. A qualifying Deal Team Loss Report is due within two business days and stays restricted; never post it to #win-wire.',
'What drove the customer’s decision?|What could we change in a future opportunity, and what follow-up is appropriate?',
'Lost on price; no supporting detail.',
'Customer confirmed budget withdrawal; no competitor selected; funding-review follow-up agreed and evidence recorded.',
'Draft a loss explanation that separates customer-confirmed facts, internal hypotheses and a useful follow-up.',
'When does the source require the loss-report notification?',
'When the prior stage is ≥3 and amount is >$1M, or the prior stage is ≥2 and amount is >$5M. The qualifying Deal Team Loss Report is due within two business days.')

lesson('quoting','Create and maintain the quote','s2 s3 s4 s5 ongoing','AE · Sales Engineering','ongoing-quoting-detail',
'Quoting develops the commercial proposal in CPQ during Stages 2–5. A single Primary Quote for the opportunity synchronizes its Amount and Products.',
'Quote Purpose (Budgetary or Best and Final) and Timing Urgency (Standard or Urgent) answer different questions.',
'Create or revise quotes only in Stages 2–5.|Choose the purpose and urgency; explain Urgent requests.|Select the Primary Quote by Stage 4, before Stage 5.',
'The lab requests a budget estimate while configurations are still being compared. The seller uses Budgetary purpose with Standard urgency. Once scope is selected, they prepare the final commercial proposal and identify the correct Primary Quote for the opportunity.',
'Confirm readiness — Use discovery and technical context to understand what the customer needs priced. Quoting remains disabled before Stage 2.|Set the request accurately — Choose Budgetary or Best and Final, then Standard or Urgent. An Urgent request requires an Urgency Reason; competitor pricing is optional.|Build and reconcile — Use the selected configuration, products and calculations in CPQ. Check that the single Primary Quote belongs to this opportunity and synchronizes Amount and Products.|Control revisions — Revise while in Stages 2–5. If a Stage 6 discrepancy requires correction, follow the documented return to Stage 5 and revalidation; booked orders use the amendment path.',
'Is this a budget estimate or the final commercial proposal?|What customer event justifies urgency?',
'Every quote is Urgent; reason blank.',
'Budgetary quote for customer planning; Standard urgency; final primary proposal linked after scope selection.',
'Write a useful urgency reason tied to a real customer event and explain why it does not change the quote purpose.',
'Can the team create a new quote directly in Stage 6?',
'No. Quote creation and revision are restricted to Stages 2–5. Use the documented correction path when needed.')

lesson('next-steps','Keep Next Steps and Close Date current','s1 s2 s3 s4 s5 s6 ongoing','AE · Sales Engineering','ongoing-next-detail',
'Next Step records a dated customer-facing action. AE review confirms that action and the expected Close Date at least weekly in open Stages 1–6; SE reviews its technical next action separately.',
'An unrelated record edit is not a review. An unchanged next step can still be explicitly reviewed and confirmed.',
'Record a concrete customer action with a date.|Review Next Step and expected Close Date at least weekly.|Keep the SE technical action distinct; preserve the booked Close Date.',
'The next action is a Friday review with the director. On Monday the AE confirms the meeting and close-date assumptions even though neither value changes. The SE separately confirms a Wednesday validation session. Both reviews stay meaningful without cosmetic text edits.',
'Choose the next commitment — Define the customer-facing action, participant, expected result and date. Avoid vague internal intentions.|Test the close date — Compare the expected close with the customer decision and paper processes. Update it when evidence changes.|Review weekly — Use the supported AE review action to confirm both Next Step and Close Date, even if unchanged. SE confirms its technical action separately.|Act on staleness — Resolve open Stage 1–6 records without a review for seven days. At booking the Close Date locks; later activity does not rewrite it.',
'What will the customer and our team do next, and by when?|What evidence still supports the expected close date?',
'Follow up.',
'Friday: AE and director review quantified business case and confirm remaining procurement steps.',
'Rewrite three vague next steps into dated customer actions and identify the close-date assumption each would test.',
'Does editing an unrelated field refresh the weekly review?',
'No. A specific AE or SE review is needed; unrelated edits do not reset freshness.',
'The system-maintained review timestamp mapping must be confirmed before rollout. Do not invent a live review button or claim ordinary edits satisfy the control.')

lesson('buying-committee','Build the buying committee','s1 s2 s3 s4 s5 ongoing','AE · Sales Engineering','ongoing-buying-committee',
'The buying committee is the set of Salesforce Contacts participating in the purchase, with their roles assigned on the opportunity.',
'The designated originating/conversion Contact supports lifecycle tracking. Other buying-committee members do not automatically inherit that conversion event.',
'Add real Salesforce Contacts and assign supported buying roles.|Require at least one assigned Opportunity Contact Role before Stage 2.|Expand the map as decision and procurement participants emerge.',
'The original researcher introduced the project. During discovery the AE adds the architect, infrastructure director and procurement lead, reflecting their actual roles. The researcher remains the conversion Contact; the added committee members do not become the originators of the deal.',
'Find participants — Ask who evaluates, influences, funds and approves the purchase.|Resolve the records — Reuse the correct Salesforce Contacts, checking account context rather than adding free-text names.|Assign roles — Choose supported Opportunity Contact Roles based on customer evidence. Ensure at least one is assigned before Stage 2.|Maintain coverage — Revisit the map through Stages 1–5 as authority, decision and paper processes become clearer. Keep the conversion relationship separate.',
'Who could block or accelerate this decision?|Which important participant have we not engaged yet?',
'Committee is a list of names in notes only.',
'Contacts linked to the opportunity with validated roles; originating Contact separately designated.',
'Map a researcher, architect, budget owner and procurement lead to the roles you would verify before assigning them.',
'Must every committee member be captured at opportunity creation?',
'No. A resolved originating Contact is needed at creation; develop the committee through discovery and later buying stages.')

lesson('poc','Run a purposeful POC','s1 s2 ongoing','Sales Engineering · AE','ongoing-poc-detail',
'A proof of concept (POC) is a scoped evaluation used when needed to address technical questions. Required POCs must be Cancelled or Completed before Stage 3.',
'POC disposition is distinct from the Technical Outcome. Completion does not automatically mean technical success.',
'Make an explicit POC Required? Yes/No decision.|Connect the evaluation to customer criteria.|If required, resolve it as Cancelled or Completed before Stage 3.',
'The lab needs to validate ingest performance. The SE agrees a representative workload and success criteria, runs the evaluation and documents the result. The POC is marked Completed, while the overall Technical Outcome is assessed separately during Buyer alignment.',
'Decide the need — Identify the uncertainty that a POC would resolve and record an explicit Yes or No.|Define the evaluation — Agree the workload, conditions, evidence and participants with the customer. Avoid a test with no decision it can inform.|Manage progress — Keep planning, execution and blockers visible; address impediments with the responsible participants.|Close honestly — If required, record Completed with results or Cancelled with context before Stage 3. None, Planning, In Progress and Blocked do not pass, including stage skips.',
'What decision will this test help the customer make?|What result would demonstrate the agreed criterion?',
'Run a demo and call it a successful POC.',
'Agreed representative test, evidence captured, POC Completed; Technical Outcome evaluated separately.',
'A required POC is Blocked but the AE wants to advance to proposal. Explain the gate and what must be resolved.',
'Can a required POC in progress pass into Stage 3?',
'No. A required POC must be Cancelled or Completed before any forward move beyond Stage 2.')

lesson('risk','Manage Technical Deal Risk','s1 s2 s3 s4 s5 s6 ongoing','Sales Engineering','ongoing-risk-detail',
'Technical Deal Risk records the category, severity, explanation and linked issue for a technical threat to the opportunity.',
'It is maintained across Stages 1–6 and remains separate from the removed generic Known Opportunity Risks stage prompt.',
'Name the specific uncertainty and its impact.|Set the category and risk level; link the issue.|Reassess as evidence changes and document resolution.',
'The SE discovers a migration dependency that could delay the customer’s launch. They record Migration as the category, explain the impact, choose the supported severity and link the issue. After validation, they update the assessment with resolution evidence.',
'Identify the threat — Describe the technical condition and the customer or deal outcome it could affect.|Classify accurately — Use applicable categories such as Integration, Migration, Software or Timeline; use High, Medium, Low or Resolved according to the evidence.|Connect the work — Link the associated issue and discuss the action, responsible participant and next review in the working plan.|Reassess explicitly — Update the explanation and severity when validation or product work changes the risk. Resolved should be supported by evidence, not optimism.',
'What would happen if this technical issue remains unresolved?|What evidence would let us lower or resolve the risk?',
'Risk low because the team feels confident.',
'Migration dependency documented with impact, supported severity and issue link; resolution tied to validation evidence.',
'Write a risk explanation that separates the condition, impact and evidence needed for resolution.',
'Is a feature request alone proof that the associated technical risk is resolved?',
'No. Track the risk until evidence supports changing its assessment; a request is not delivery or validation.')

lesson('enhancements','Handle product enhancements','s2 s3 s4 s5 ongoing','Sales Engineering · Product','ongoing-product-detail',
'A product enhancement request is a linked Case describing a needed capability, created from the opportunity during Stages 2–5.',
'A submitted request is not a product delivery commitment or evidence that a technical risk has been resolved.',
'Describe the customer need and missing capability.|Create the linked Case with title, description and Opportunity.|Keep customer expectations and related risk grounded in confirmed information.',
'The lab needs an integration behavior the current design does not provide. The SE writes a specific request describing the workflow and business impact, links it to the opportunity and works with Product. They do not promise a release date that Product has not confirmed.',
'Clarify the need — Ask what task the customer cannot complete and whether an existing approach can meet it.|Write a useful request — Give the Case a precise title and describe the workflow, missing behavior, expected result and impact.|Link and route — Create the product-feature Case in Stages 2–5 with the Opportunity relationship so Product has the deal context.|Close the loop — Communicate confirmed outcomes and maintain any Technical Deal Risk. Keep assumptions or proposed timing separate from approved commitments.',
'What customer task requires this capability?|What would an acceptable result or workaround look like?',
'Need better integration urgently.',
'Linked Case describes the exact integration gap, affected workflow, desired behavior and deal impact.',
'Draft a Case title and description for a missing workflow capability without promising a delivery date.',
'Does filing a product enhancement authorize a delivery promise?',
'No. Communicate only confirmed product commitments and maintain the unresolved risk.')

lesson('partner-accounts','Manage associated accounts','s0 s1 s2 s3 s4 s5 s6 s7 ongoing','AE · Partner Managers','ongoing-partners-detail',
'Associated accounts represent the organizations connected to an opportunity, including their account classification, role, impact and engagement plan.',
'Association detail explains an account’s involvement. Automated contribution credit uses qualifying origin and timing evidence.',
'Link each relevant account and classify its involvement.|Keep account-specific contacts, plans and engagement current.|Preserve historical involvement when relationships change.',
'A reseller handles the transaction while a technology partner assists validation. The team links both accounts, records distinct roles and plans, and identifies the appropriate contacts. They avoid forcing every partner relationship into one Primary Partner record.',
'Identify the organizations — Ask which partners, vendors and customer entities are involved and what each contributes.|Use the correct account — Link the canonical account record and choose the supported association classifications and roles.|Make the plan actionable — Describe the account’s impact and engagement plan; identify primary and technical contacts when applicable.|Maintain the relationship — Review engagement through the opportunity. Preserve the timing and history needed for attribution; End Customer-only associations do not trigger partner credit.',
'What is this account contributing to the opportunity?|Who owns the next engagement with its business or technical contact?',
'One partner name with no role or plan.',
'Reseller and technology partner linked separately, with role, contribution context, contacts and engagement plans.',
'Write two distinct association plans for a fulfillment reseller and a vendor providing technical support.',
'Does every associated account automatically create partner contribution credit?',
'No. Qualifying partner evidence and timing determine credit; an End Customer-only association does not qualify.')

lesson('fulfillment','Identify the Fulfillment Partner','s0 s1 s2 s3 s4 s5 s6 ongoing','AE · Partner Managers · Order Management','ongoing-primary-detail',
'Fulfillment Partner identifies the partner account handling fulfillment after the multi-partner attribution migration is in place.',
'Fulfillment responsibility is separate from sourcing and contribution credit. The partner is not necessarily the ship-to destination.',
'Confirm which partner handles fulfillment.|Keep its role separate from originating source and partner credit.|OM verifies the actual ship-to account and address.',
'A reseller fulfills the lab’s order, but equipment must ship to the lab’s receiving dock. The AE identifies the fulfillment account and gives OM the confirmed end-customer delivery details. OM verifies the destination rather than shipping to the reseller by assumption.',
'Confirm the commercial role — Establish which account is responsible for fulfillment and coordinate with the Partner Manager.|Check the rollout state — Use Fulfillment Partner only after Associated accounts and attribution migration are in place; do not independently repurpose historical Primary Partner data.|Connect the order — Carry the account reference into the Order shipping workflow with the relevant delivery context.|Verify the destination — OM confirms actual ship-to account, address and receiving arrangements, coordinating logistics through booking.',
'Which partner is handling fulfillment?|Where must the order physically arrive, and who will receive it?',
'Ship to the partner because they are in Fulfillment Partner.',
'Fulfillment reseller identified; end-customer site and receiving contact independently verified by OM.',
'Explain the three separate roles of a sourcing partner, a fulfillment reseller and the final receiving site.',
'Can Primary Partner be renamed before attribution migration is complete?',
'No. The source makes Associated accounts and attribution migration prerequisites for that rename.',
'The rename and shipping connection are dependent on migration. This course does not assert that the change is already deployed.')

lesson('partner-credit','Understand partner contribution','creation s0 s1 s2 s3 s4 s5 s6 s7 ongoing','Partner Managers · RevOps · AE','ongoing-contribution-detail',
'Partner Contribution classifies partner involvement using channel ownership at creation and the earliest qualifying partner event, with automated credit frozen at booking.',
'Contribution is not simply the current owner or latest partner added. Original event timing is retained through regressions, removals and transfers.',
'Partner-only reflects partner/channel-only creation and ownership.|Otherwise, first qualifying event before Stage 3 is Partner-Led; first in Stages 3–6 is Joint.|Freeze automated credit at Stage 7 booking.',
'A partner first qualifies for association during Solution design, Stage 2. The deal later regresses and changes owners. It remains Partner-Led because the original qualifying event is preserved. A second partner added after booking is visible but does not change booked credit.',
'Establish origin — Check whether the opportunity was created and owned solely by partner/channel, supporting Partner-only.|Find the earliest event — For other opportunities, locate the first qualifying association or approved registration and its original stage and timestamp.|Apply the timing — Before Stage 3 is Partner-Led; first event in Stages 3–6 is Joint. No qualifying event retains Sales only or the existing no-partner disposition.|Freeze and correct carefully — Evaluate immediately before booking and freeze automated credit. A management override requires an audited reason; routine transfers or partner removal do not reset evidence.',
'What is the earliest qualifying partner event?|What original creation or registration evidence supports this classification?',
'Latest partner added determines all credit.',
'Original Stage 2 qualifying event retained; Partner-Led credit frozen at booking; later associations remain visible.',
'Classify three cases: channel-only origin, first partner event in Stage 2, and first partner event in Stage 4.',
'Does an association added in Stage 7 change automated booked credit?',
'No. Credit freezes at booking. A later association remains visible; an authorized management correction needs an audited reason.',
'Before migration the qualifying association is Primary Partner; after migration it is the first qualifying partner in Associated accounts. End Customer-only associations do not qualify.')

lesson('nvidia','Coordinate NVIDIA engagement','s1 s2 s3 s4 s5 s6 ongoing','Partner Managers · Sales Engineering','ongoing-nvidia-detail',
'NVIDIA engagement combines an account-specific relationship plan with the Opportunity’s NVIDIA engagement summary and specific engagement status when NVIDIA is relevant.',
'The association’s Active/Inactive state is different from the NVIDIA Engagement Status on the Opportunity.',
'Use the canonical NVIDIA Associated account when relevant.|Keep its account plan and next steps on the association.|Maintain the Opportunity engagement summary and verified status while the association is active.',
'NVIDIA begins helping with the lab’s solution design. The Partner Manager activates the correct association and records the technical engagement plan. The SE updates the Opportunity summary using supported values, without substituting “Active” for the separate engagement status.',
'Confirm relevance — Determine whether an active association with the canonical NVIDIA Account exists.|Describe the relationship — Record the account-specific plan, participants and next steps on Associated accounts.|Update the summary — Complete the existing Nvidia Engagement and separately verified NVIDIA Engagement Status when relevant, including activation and stage advancement.|Preserve history — When the association becomes inactive, retain its history and stop requiring new engagement input solely because of that former relationship.',
'What specifically is NVIDIA helping the customer or deal team accomplish?|Does the summary accurately reflect the current engagement?',
'NVIDIA Engagement Status = Active because the association is active.',
'Active NVIDIA association with a specific plan; Opportunity engagement and separately supported status maintained.',
'Explain where to record the partner’s next meeting and where to record the Opportunity-level engagement summary.',
'Is NVIDIA engagement a universal gate on every opportunity?',
'No. It applies when the active canonical NVIDIA association makes NVIDIA relevant.',
'The source requires verification of the specific NVIDIA status field and allowed choices. Do not invent status values or teach an unverified control as live.')

lesson('logistics','Align lead time, delivery and installation','s3 s4 s5 s6 s7 ongoing','AE · Sales Engineering · Order Management · GSS','ongoing-logistics-detail',
'Logistics planning aligns the customer’s requested installation with shipping, delivery, receiving and deployment responsibilities.',
'Requested installation, estimated shipping, requested delivery, actual shipment and actual receipt are different dates.',
'Begin alignment in Stage 3.|Capture Requested Install Date in Stage 4; shipping and requested delivery dates in Stage 5.|Reconcile the plan with OM and GSS at handoff and booking.',
'The lab wants installation before its January program. Sales learns that site access is limited during a holiday closure. The team works backward through delivery and shipping, confirms the receiving contact and documents the dependency for OM and GSS.',
'Start with customer intent — Ask when installation is needed and which business event it supports. Clarify site-readiness dependencies.|Separate the milestones — Record Requested Install Date in Stage 4; Estimated Shipping Date and Requested Delivery Date in Stage 5. Do not use one date for every event.|Assign the handoffs — Confirm receiving contact, site access, shipping context and deployment responsibilities in the Case/Order plan.|Reconcile the plan — Review lead times and dependencies with OM and GSS at booking, keeping requested, scheduled and actual events distinct.',
'When can the site receive equipment and when is it ready for installation?|Which dependency could make the requested installation date unachievable?',
'One date copied into shipping, delivery and installation.',
'Installation request, shipping estimate and requested receipt recorded separately with site-access dependencies and owners.',
'Build a timeline for a site that needs two days between receipt and installation; identify what must be confirmed before committing dates.',
'Can a shipping date be used as proof of customer receipt?',
'No. Actual on-site receipt requires separate evidence.',
'OM/GSS must confirm applicability for renewals, software/services, Internal Transfer, Non-Revenue and No Shipping required orders. Do not invent dates to satisfy physical-delivery requirements.')

lesson('ipg','Finalize and hand off IPG','s4 s5 s6 ongoing','Sales Engineering · AE','ongoing-ipg-detail',
'The IPG process gathers, finalizes and submits the required package during procurement and carries it into the order and deployment handoff.',
'IPG Finalized needs an explicit Completed or applicable Not Required disposition. Blank is not a disposition.',
'Gather IPG information during proposal and procurement.|Finalize and submit during Stage 5.|Before Stage 6, record Completed or explicitly applicable Not Required.',
'The SE assembles the lab’s IPG package and reviews it with Sales before procurement ends. They submit the completed information and ensure the handoff team can access the supporting files. A blank status is not treated as “probably not needed.”',
'Identify the applicable package — Review the current IPG requirements with the responsible internal team; use the supported process and materials.|Gather and reconcile — Ensure the package reflects the selected solution, procurement evidence and delivery context.|Submit and record — Before Stage 6, select Completed when finalized and submitted, or Not Required when explicitly applicable.|Carry it forward — Keep the package and supporting files accessible to OM and the coordinating deployment Case so the handoff does not lose context.',
'What remains incomplete in the applicable IPG package?|Can the receiving team access the submitted version?',
'IPG blank; assume not required.',
'IPG Completed; submitted package linked and accessible in the order/deployment handoff.',
'Prepare an IPG handoff note naming its disposition, submitted version and where the receiving team can find it.',
'Which dispositions satisfy the IPG requirement before Stage 6?',
'Completed or an explicitly applicable Not Required disposition. Blank does not satisfy it.',
'The source does not provide the IPG acronym expansion or a detailed internal template. Use the organization’s current IPG materials; do not invent their contents.')

lesson('win-wire','Tell the win story','s6 s7 ongoing','AE · Sales Manager','win-wire',
'A Win wire communicates the customer win, its value and contributors after AE capture and manager review, with the source’s amount-based requirements.',
'The Resources Engaged threshold is ≥$1M; the manager Win wire threshold is >$1M. Exact boundaries matter.',
'At Stage 6, record Won Reason and specific Business Value evidence.|At ≥$1M, name Resources Engaged.|Above $1M, manager submits reviewed Win wire within two business days; above $2M, also provide the Deal Team Win Report.',
'A fictional $1.4M lab win includes a customer-confirmed operational outcome and several internal contributors. The AE captures the evidence and contributor names. The manager reviews the story and submits it to Enablement / #win-wire within two business days.',
'Collect facts — Start from the won decision, customer need, chosen solution and specific value evidence; avoid unvalidated claims.|Recognize contributions — At amounts ≥$1M, complete Resources Engaged with the account team and cross-functional contributors.|Review and route — Above $1M, the Sales Manager receives the notification with the AE copied, reviews the content and submits the Win wire to Enablement / #win-wire within two business days.|Complete the larger-deal report — Above $2M, also prepare the Deal Team Win Report. Keep loss reporting separate and restricted.',
'What evidence makes this win instructive for the team?|Who contributed materially and should be recognized?',
'Huge win; great teamwork; no customer context.',
'Customer problem, validated value, reason for selection and named contributors reviewed by the manager.',
'Write a five-sentence win story using customer evidence, then identify the requirements for $1M, $1.4M and $2.1M deals.',
'At exactly $1M, are both Resources Engaged and the above-$1M Win wire automatically required by these thresholds?',
'No. Resources Engaged applies at ≥$1M. The manager’s two-day Win wire rule applies above $1M; the additional report applies above $2M.')

lesson('interviews','Capture win/loss interview eligibility','s6 lost ongoing','AE · Win/Loss team','s6',
'Interview eligibility records whether the Win/Loss team may approach a customer Contact for feedback and supplies the appropriate contact or reason.',
'Eligibility captures permission to approach in this process. It is separate from the win/loss reason and is not an instruction to send an interview request.',
'For New Business, Existing Business and Renewal, record Yes or No at win decision or loss.|Yes requires a Salesforce Contact.|No requires WL Reason Cannot Approach.',
'After the lab decision, the AE confirms that a customer contact may be approached for feedback. They select Yes and link that person’s Salesforce Contact. For another deal where outreach is inappropriate, they select No and explain the reason.',
'Confirm applicability — Use this capture at Won decision or Closed lost for New Business, Existing Business and Renewal.|Assess approachability — Determine whether the team can appropriately approach a customer for feedback, using the actual relationship context.|Complete the correct branch — Yes requires Contact for Win/Loss Interview as a Contact record. No requires WL Reason Cannot Approach.|Review for clarity — Ensure the contact is resolved and the reason is meaningful when No. Do not populate the irrelevant conditional field to satisfy a hidden requirement.',
'Can the Win/Loss team approach a customer contact for feedback?|Which Contact is appropriate, or why can the team not approach?',
'Yes; contact name typed into a note only.',
'Yes with the correct Salesforce Contact linked, or No with a specific reason the team cannot approach.',
'Complete the two possible branches for a fictional win and a loss, explaining which information is required in each.',
'If eligibility is No, should an interview Contact still be required?',
'No. The required branch is WL Reason Cannot Approach; the Contact is required when eligibility is Yes.',
'The source calls for reuse of the Win/Loss rollout controls where already deployed. Exact deployment state must be confirmed.')

lesson('deployment','Start and manage the deployment Case','s6 s7 s8 post ongoing','GSS · Order Management · Sales Engineering · AE','case-current-state',
'The coordinating deployment Case holds the deployment plan, workstreams and responsibilities from Won decision onward, continuing after the Opportunity ends.',
'The Opportunity ends at Stage 8. Deployment and value realization continue on the Case, not in additional Opportunity stages.',
'Create or link the coordinating Case at Stage 6.|Before booking, identify the GSS owner and shipping, receiving and installation plans.|Keep all in-scope workstreams and completion evidence connected.',
'The lab order needs hardware setup and a separate migration workstream. GSS links both to the coordinating Case. Hardware installation finishes first, but the team continues tracking migration and customer outcomes after the Opportunity reaches Stage 8.',
'Initiate the handoff — At Won decision, create or link the coordinating PS deployment Case using the supported relationships and bring in GSS.|Establish ownership and scope — Before Stage 7, identify the Case owner, in-scope workstreams, logistics dates, responsibilities and dependencies.|Coordinate execution — Maintain the plan across OM, GSS and the customer; associate later Orders with the same coordinating Case and retain subordinate workstreams.|Verify completion — Use actual deployment checklist and workstream evidence. One closed subordinate Case does not establish full deployment. Keep value assessment distinct from deployment completion.',
'Who owns the complete deployment outcome?|Which workstreams remain open even if installation is finished?',
'Hardware Case closed, so all deployment and value are complete.',
'Coordinating Case tracks installation and migration; each has evidence and an owner; value assessment remains distinct.',
'Create a handoff agenda covering scope, ownership, logistics, dependencies and the sales-defined value plan.',
'Should the original Opportunity stay open until deployment is finished?',
'No. It ends at Stage 8. Deployment and value work continue on the Case.',
'Existing Case relationship and status mappings, and applicability for non-shipping motions, remain to be confirmed. Avoid duplicate or dummy Cases.')

lesson('value-realization','Confirm value realization','s6 s7 s8 post ongoing','GSS · AE · Customer outcome owner','case-value-realization',
'Value realization assesses whether the customer achieved the sales-defined Operational Value and Business Value, using a plan, target date and outcome evidence on the coordinating Case.',
'Deployment completion or Case closure does not itself prove customer value. A pending assessment is different from an assessed No.',
'Plan from Stage 6 using the agreed sales value case.|Keep the outcome blank while pending; confirm Yes or No when assessed.|For No, explain the gap and agreed disposition.',
'The lab’s system is installed, but the agreed staging measurement has not yet been run. GSS leaves Value Achieved? pending. After the customer measures the representative workflow, GSS records the result, customer confirmation and assessment date, then compares it with the agreed target.',
'Transfer the promise — Review the Operational Value baseline and target and the Business Value assumptions with Sales and the customer.|Build the validation plan — Record how the outcome will be measured, who participates and the target realization date on the Case. Scope of Work alone is not the value plan.|Assess with evidence — Compare actual results with the agreed outcome. Record Yes only when achieved and confirmed; No when assessed and not achieved; leave pending blank.|Agree the next action — Record measured results, confirmation or gap and disposition, plus the outcome-confirmation date. Use insights for separately linked renewal or expansion opportunities.',
'What evidence will demonstrate the customer’s intended outcome?|If the target was missed, what gap and next action have we agreed?',
'Case closed, therefore Value Achieved = Yes.',
'Customer measurement compared with the sales-defined target; result, evidence, assessment date and disposition recorded.',
'Write two assessment notes: one with confirmed achievement, another with a measured shortfall and agreed next action.',
'What value outcome should be recorded before the assessment is complete?',
'Leave it blank while pending. No means assessed and not achieved, not “we have not measured yet.”',
'The value fields are proposed on the PS Case. They do not create new Opportunity stages or completion gates.')

lesson('time-to-value','Measure Time to Value','s8 post ongoing','GSS · RevOps','case-value-realization',
'Time to Value is the number of days from the first verified Stage 8/on-site-delivery milestone to confirmed value achievement, calculated on the coordinating Case when Value Achieved? is Yes.',
'The start is not Case creation, invoice issuance or booking. A No or pending value assessment does not produce Time to Value.',
'Preserve the first delivery-based Value Tracking Start Date.|Calculate only for confirmed Yes with a valid assessment date.|Keep pending and No blank; investigate a missing baseline.',
'The fictional lab’s coordinating Case starts on October 1, full delivery is verified on October 10 and value is confirmed on October 24. Time to Value is 14 days from delivery. A later Case reassignment does not restart the clock.',
'Locate the baseline — Confirm the first Stage 8/on-site-delivery milestone is preserved as Value Tracking Start Date on the Case.|Check the outcome — Require Value Achieved? = Yes and a Value Outcome Confirmed Date on or after that baseline.|Interpret the result — Calculate elapsed days between the delivery milestone and confirmed achievement. Keep financial invoice timing separate.|Resolve exceptions — Investigate missing or invalid dates without reopening the Opportunity. Re-entry, retries and Case reassignment must not reset the original start.',
'What event established the original value-tracking baseline?|Has value actually been confirmed, and is the date valid?',
'Calculate from the invoice date even though delivery happened earlier.',
'October 10 delivery to October 24 confirmed achievement = 14 days; baseline preserved on the Case.',
'Calculate the example again if the Case opened September 28 and the invoice was issued October 18. Explain why those dates do not change the answer.',
'Is Time to Value zero when Value Achieved? is No?',
'No. It stays blank for No or pending. Calculate only when achievement is confirmed and the assessment date is valid.')

lesson('forecast','Use the stage-based sales forecast','creation s0 s1 s2 s3 s4 s5 s6 s7 s8 lost ongoing','Sales · Managers · RevOps','creation',
'Forecast Category (Sales) is the system-maintained classification derived from the permitted sales stage.',
'It is separate from lifecycle conversion and from other standard Salesforce forecast fields. Sellers do not maintain a conflicting value independently.',
'Creation / 0: Pre-pipeline; 1–2: Pipeline.|3–4: Upside; 5–6: Commit.|7–8: Won; Closed lost: Loss.',
'A seller-qualified opportunity is created directly in Discovery. Its saved sales forecast is Pipeline even though the creation flow normally starts with Pre-pipeline. Later it reaches Won decision and remains Commit until OM confirms booking.',
'Understand the mapping — Learn the stage categories and explain why customer progress changes the forecast.|Use evidence-based stages — Advance only when the required stage evidence is satisfied; a stage skip cannot bypass earlier gates.|Review discrepancies — If the sales forecast conflicts with stage, raise the mismatch for correction rather than compensating with an unsupported manual category.|Preserve exceptions correctly — Permitted return to Stage 0 restores Pre-pipeline; booked-record locks and existing administrative outcomes remain in force.',
'Which stage does the customer evidence actually support?|Does the sales forecast match that permitted stage?',
'Won decision always means forecast Won.',
'Won decision is Commit; OM-confirmed Closed won becomes Won.',
'Map a fictional opportunity’s progression from Validate to Invoice to the correct sales forecast categories.',
'What category is saved for seller-qualified direct creation in Stage 1?',
'Pipeline. The category is derived from the actual initial stage; creation is a capture step, not another numbered stage.')

lesson('deal-context','Maintain the deal description and evidence','s2 s3 ongoing','AE · Sales Engineering','s2',
'Description preserves concise customer context, intended solution and business need. SharePoint Link connects the technical documentation supporting the opportunity.',
'A document link gives access to evidence; it does not replace the required summary or prove that the linked material is current.',
'Write a concise customer-centered Description before Stage 3.|Link relevant technical documentation in SharePoint Link.|Keep configuration versions and summaries aligned.',
'A new SE joins the lab opportunity. The Description explains the customer’s workflow and need, while SharePoint Link leads to the current design and validation evidence. The selected configuration version is clear, so the SE avoids reusing an obsolete proposal.',
'Summarize the context — State who the customer is, the workflow or need, the intended solution and why the project matters.|Organize the evidence — Link relevant technical documentation, using the existing rich-text SharePoint Link field for multiple references where needed.|Check currency — Identify which configuration or document version supports the current stage; update the narrative when the agreed design changes.|Support the handoff — Verify the receiving team can locate the material and understand its relationship to Technical Value, criteria and the selected configuration.',
'Could a new team member understand this opportunity from the summary?|Which linked evidence supports the configuration we are actually proposing?',
'“See docs,” with an unexplained link to an old design.',
'Concise customer and solution context plus clearly identified current design and evaluation references.',
'Write a four-sentence Description for the fictional lab and list the technical evidence a new SE would need.',
'Does a SharePoint link alone replace the Stage 2 Description requirement?',
'No. Keep the concise Description and the linked technical evidence; both serve different purposes.')
