STAGES = [
('creation','Create','Opportunity creation','Sales · Marketing · BDRs · Partners','Pre-pipeline; direct Stage 1 saves Pipeline','Capture a traceable opportunity and route it to the right starting point.','Source and matching reference; originating Contact; core deal details; SAL at creation.','Inbound enters Validate. Assigned seller-self-qualified opportunities may enter Discovery directly.',['source','conversion','forecast']),
('s0','0','Validate','Marketing · Partners · BDRs · assigned seller','Pre-pipeline','Qualify the handoff and establish seller accountability.','Assigned seller acceptance and all five CHAMPS answers for non-self-qualified inbound intake.','Before Stage 1: assignment, acceptance, originating Contact and inbound CHAMPS.',['sal-review','challenge','authority','money','priority','stack']),
('s1','1','Discovery','Sales · Sales Engineering','Pipeline','Establish business fit and the customer use case.','CHAMPS, use case, route to market, AE/Primary SE and at least one assigned Contact Role.','SQL is recorded on entry. Complete discovery before Stage 2; quoting stays disabled here.',['use-case','route','buying-committee','conversion','challenge','authority','money','priority','stack']),
('s2','2','Solution design','Sales · Sales Engineering','Pipeline','Assess technical fit through candidate configurations.','Pain, competitors, Technical Value, Champion, criteria, Description, technical links and resolved required POC.','Complete Stage 2 evidence and an explicit POC decision before Stage 3.',['pain','competition','technical-value','champion','criteria','deal-context','poc','quoting']),
('s3','3','Buyer alignment','Sales · Sales Engineering','Upside','Agree one configuration and align the buying decision.','Technical Win, selected configuration, Operational Value, Economic Buyer and Decision Process.','Technical Outcome must be Technical Win before Stage 4.',['technical-outcome','technical-value','operational-value','economic-buyer','decision-process']),
('s4','4','Proposal / negotiate','Sales · Sales Engineering','Upside','Align the commercial proposal with business value.','Quantified Business Value, Primary Quote, Paper Process and Requested Install Date.','Complete Stage 4 requirements before Stage 5; confirm logistics applicability for non-shipping motions.',['business-value','quoting','paper-process','logistics','ipg']),
('s5','5','Procurement','Sales · Sales Engineering','Commit','Complete the procurement package and delivery timing.','IPG disposition, secured/attached PO, final agreements, shipping estimate, requested delivery and notes.','Complete procurement evidence before Won decision; quoting revisions remain permitted in Stage 5.',['procurement','ipg','logistics','quoting']),
('s6','6','Won decision','Sales · Sales Engineering; OM and GSS handoff','Commit','Capture why the customer chose us and prepare order and deployment review.','Win evidence and conditional interview/contributor information; reconciled package; coordinating deployment Case.','OM must confirm reconciliation before Stage 7; identify the GSS owner and handoff plan before booking.',['won-decision','interviews','win-wire','booking','deployment','value-realization']),
('s7','7','Closed won','Order Management · GSS','Won','Confirm booking and coordinate fulfillment.','OM-confirmed booked PO, locked Close Date and booked facts; linked Order/Case delivery plan.','Complete verified on-site receipt of in-scope items controls Stage 8; partial delivery remains in Stage 7.',['booking','logistics','invoice','deployment','partner-credit']),
('s8','8','Invoice','Order Management · GSS','Won','Complete the Opportunity at verified on-site delivery.','Complete delivery evidence; invoice references and dates when issued; linked deployment Case.','Final Opportunity stage. Pending invoices, deployment and value assessment continue on Order/Case.',['invoice','deployment','value-realization','time-to-value']),
('lost','Lost','Closed lost','Sales · Sales Engineering','Loss','Capture the decision, learning and appropriate follow-up.','Loss reason/details, competitor outcome, next-step recommendation and conditional interview capture.','Use the loss-entry rules and actual decision date; prior sales gates need not be completed to record a loss.',['loss','competition','interviews']),
('post','Case','Deployment & value','GSS · Order Management','Opportunity remains Won','Deliver the agreed outcome and confirm customer value.','Coordinating Case, workstream evidence, value plan, target date and final outcome assessment.','Continues on the Case after Stage 8; it is not an additional Opportunity stage.',['deployment','value-realization','time-to-value'])
]

# Additional reference terms share the module's role, scope, example and source.
# Each item: term, module, meaning, distinction.
TERMS = [
('MQL — Marketing Qualified Lead','conversion','The Contact qualification milestone supplied by Marketing’s automation platform.','MQL is distinct from AQL; neither is fabricated for a seller-direct SQL.'),
('AQL — Agentic Qualified Lead','conversion','The Contact qualification milestone supplied by PAX.AI.','PAX.AI is the qualification channel, not a newly approved Opportunity Source choice.'),
('SAL — Sales Accepted Lead','sal-review','The conversion milestone recorded when an opportunity is created for its originating Contact and Opportunity Conversion Lifecycle.','In this framework, SAL creation does not itself mean the assigned seller has accepted the handoff.'),
('SQL — Sales Qualified Lead','conversion','The conversion milestone recorded on first entry to Discovery, after the applicable acceptance and qualification checks.','Seller-qualified direct Stage 1 creation records SAL and SQL together without inventing prior MQL/AQL.'),
('Conversion Contact','conversion','The designated originating Contact resolved and associated with the opportunity for conversion tracking.','A conversion Contact is required at creation; the full buying committee develops later.'),
('Opportunity Conversion Lifecycle','conversion','The system-maintained Opportunity milestone showing SAL at creation and SQL at Stage 1, retained after discovery.','It is separate from the numbered sales Stage and the existing Contact/Account lifecycle.'),
('Account Lifecycle Stage (ALS)','conversion','The existing Account lifecycle context whose mappings are extended for approved conversion visibility.','A new Stage 0 opportunity does not downgrade an Account already further through its lifecycle or change customer-state semantics.'),
('Seller-self-qualified entry','sal-review','The assigned seller’s documented direct creation of a qualified opportunity in Stage 1, recording auto-accepted SAL and SQL.','CHAMPS remains required before Stage 2. Integration-created inbound records do not become seller-self-qualified merely because of their creator.'),
('CHAMPS','challenge','The five qualification answers: Challenge, Authority, Money, Priority and Stack / Storage.','All five are due before Stage 1 for non-self-qualified inbound intake, or before Stage 2 for seller-self-qualified entry.'),
('Opportunity Owner / Assigned AE','sal-review','The seller accountable for the opportunity and its relevant acceptance and execution responsibilities.','Current ownership does not rewrite the original sourcing attribution.'),
('Primary SE','use-case','The assigned Sales Engineering lead for technical discovery and solution work, reconciled with the opportunity team.','AE and SE responsibilities are related but their next-action reviews are tracked separately.'),
('Opportunity Type','source','The classification of the sales motion: New Business, Existing Business, Renewal, Internal Transfer or Non-Revenue.','Conditional rules may depend on Type; non-shipping and other motion-specific logistics require confirmed applicability.'),
('Opportunity Name','source','The name identifying the deal clearly at creation.','A name identifies the record; Description later captures substantive customer and solution context.'),
('Amount','quoting','The opportunity’s value, captured at creation and kept current as quoting develops; the Primary CPQ Quote synchronizes quoted Amount.','A manually typed estimate is not an independently reconciled booked amount.'),
('Sourcing User','source','The User credited with originating a Direct or BDR opportunity.','For BDR origin, use the originating BDR rather than the current AE or background integration user.'),
('Sourcing Campaign','source','The existing campaign reference credited with a Marketing-origin opportunity.','The future MAP Marketing Source change is a separate dependency, not a current rename.'),
('Sourcing Partner','source','The verified originating partner Account for Opportunity Source = Partner. Registration and origination are separate.','The sourcing partner may differ from the transacting partner or a later contributor.'),
('Indirect Route Type','route','The required subtype when Route to Market is Indirect.','It is inactive for current attribution when the route is Direct; retain historical selections in audit history.'),
('Additional Use Case Information','use-case','The supporting explanation of the customer workload, context and intended outcome behind the selected Use Case.','It supplies specific context that a broad picklist label cannot convey.'),
('Opportunity Contact Roles','buying-committee','The associations between Salesforce Contacts and their supported buying roles on the opportunity.','At least one assigned role is required before Stage 2; it is separate from the resolved originating Contact check at creation.'),
('Technical Win','technical-outcome','The SE-confirmed Technical Outcome required before Stage 4, supported by the selected configuration and technical evidence.','A completed POC, a populated text field or customer enthusiasm alone does not establish Technical Win.'),
('Technical Loss','technical-outcome','The Technical Outcome indicating a loss in technical evaluation.','It does not pass the Stage 3 → 4 gate and is distinct from the overall Closed lost decision.'),
('Description','deal-context','The concise opportunity narrative covering customer context, intended solution and business need, required in Stage 2.','The Description complements the technical evidence rather than replacing it.'),
('SharePoint Link','deal-context','The existing rich-text location for technical-document links supporting the opportunity.','It can hold multiple references and is not simply a single URL input.'),
('Primary Quote','quoting','The one primary CPQ quote belonging to the opportunity, selected by Stage 4 and synchronizing Amount and Products.','Other quote versions may exist, but they do not all act as the primary commercial record.'),
('Quote Purpose','quoting','The purpose of the CPQ request: Budgetary or Best and Final.','Purpose is separate from Timing Urgency.'),
('Timing Urgency','quoting','The CPQ timing classification, Standard by default or Urgent with an Urgency Reason.','Urgency does not change the quote purpose or bypass the stage restrictions on quoting.'),
('Close Date','next-steps','The expected close date while open, confirmed as the decision date at closure and locked at Closed won.','Do not substitute a later invoice, deployment or value-achievement date for the booked Close Date.'),
('Next Step','next-steps','A dated customer-facing action maintained with expected Close Date in open Stages 1–6.','“Follow up” without a specific action and date does not give the team a useful commitment.'),
('SE Next Step','next-steps','The Sales Engineering technical next action, reviewed separately from the AE’s customer/commercial next step.','An AE review does not automatically stand in for the SE review.'),
('Weekly review freshness','next-steps','Evidence that the AE reviewed Next Step and expected Close Date, and that the SE separately reviewed its technical action.','Unrelated edits do not reset freshness; unchanged values can still be explicitly reviewed.'),
('POC Required?','poc','The explicit Yes/No decision about whether a proof of concept is required before Stage 3.','If Yes, status must be Cancelled or Completed before progressing beyond Stage 2.'),
('POC Status','poc','The tracked POC state; a required POC must reach Cancelled or Completed to pass the Stage 3 entry check.','None, Planning, In Progress and Blocked do not pass. Completed does not automatically mean Technical Win.'),
('Technical Deal Risk Category','risk','The category or categories of the technical risk: Parts, Software, System, Expertise, Timeline, Integration, Migration, Engineering or Support.','Category names the kind of threat; risk level expresses its severity or resolution.'),
('Technical Level of Risk','risk','The supported severity/resolution classification: High, Medium, Low or Resolved.','Resolution should be backed by evidence, not merely by a request being submitted.'),
('Association Engagement Status','partner-accounts','The Active/Inactive state of an associated account’s engagement in the opportunity.','This is not the separate NVIDIA Engagement Status.'),
('NVIDIA Engagement Status','nvidia','The specific Opportunity-level NVIDIA status required when the canonical NVIDIA association is active.','The exact existing mapping and allowed choices remain unverified; do not substitute association Active/Inactive.'),
('Partner-only','partner-credit','Contribution classification for an opportunity created and owned solely by the partner/channel.','Later ownership transfers do not rewrite that origin.'),
('Partner-Led','partner-credit','For non-Partner-only opportunities, classification based on the earliest qualifying partner event before Stage 3.','Preserve the original event even if the opportunity regresses or a partner is later removed.'),
('Joint','partner-credit','For non-Partner-only opportunities, classification when the first qualifying partner event occurs in Stages 3–6.','An association added only after booking does not change frozen automated credit.'),
('Partner contribution override','partner-credit','A management correction to reporting with an audited reason; a blank override uses automated contribution.','Routine association changes or ownership transfers are not management overrides.'),
('Requested Install Date','logistics','The customer’s requested installation date captured in Stage 4 before Stage 5.','It is not actual installation completion or the requested delivery date.'),
('Estimated Shipping Date','logistics','The shipping estimate captured during Stage 5 procurement.','Shipping is distinct from on-site receipt and installation.'),
('Requested Delivery Date','logistics','The desired customer delivery date captured during Stage 5 procurement.','A requested date does not prove actual receipt.'),
('Delivery Notes','logistics','The context needed for order, shipping, receiving and deployment coordination.','Notes should explain dependencies and arrangements rather than replace separate milestone dates.'),
('IPG Finalized','ipg','The disposition Completed or explicitly applicable Not Required, required before Stage 6.','A blank field does not mean Not Required.'),
('PO Secured / PO Attachment','procurement','Confirmation of the secured purchase order and its supporting document, using Salesforce Files for the PO.','A received PO must still be reconciled with the quote and order package.'),
('Final Agreements Received','procurement','Confirmation that the final agreements needed for the procurement package have been received before Stage 6.','A verbal selection or unfinished legal review is not the final agreement package.'),
('Order Review Status','booking','The existing order-processing status used within OM’s reconciliation and booking controls.','A nonblank value is insufficient; allowed and blocked existing states and exception authority require approved mapping.'),
('Sales Order Reference','booking','The link or reference connecting the booked opportunity to its sales order and fulfillment context.','The Order carries continued fulfillment and invoice reconciliation after Opportunity completion.'),
('Won Reason','won-decision','The specific reason the customer selected the solution, captured on entry to Stage 6.','Business Value supplies the detailed win and economic evidence; a reason selection alone is not the whole story.'),
('Incumbent Vendor(s)','competition','The vendors the customer currently uses, or Not Applicable if there are none.','Current use differs from active competitors and the final Competitor Lost To outcome.'),
('Resources Engaged','win-wire','The internal account-team and cross-functional contributors named for wins at amounts ≥$1M.','This inclusive threshold differs from the above-$1M manager Win wire rule.'),
('Deal Team Win Report','win-wire','The additional win report required above $2M.','It supplements the manager-reviewed Win wire required above $1M.'),
('OK to Interview (Win/Loss)?','interviews','The Yes/No decision on whether the Win/Loss team may approach a customer Contact for feedback.','For New Business, Existing Business and Renewal, Yes needs the Contact; No needs the cannot-approach reason.'),
('Contact for Win/Loss Interview','interviews','The Salesforce Contact selected when interview eligibility is Yes.','A free-text name does not substitute for the Contact relationship.'),
('WL Reason Cannot Approach','interviews','The explanatory reason required only when interview eligibility is No.','It should not be required or validated as a hidden field when eligibility is Yes.'),
('Loss Reason','loss','The specific reason for the loss, required at Closed lost with evidence-based details.','There is no Other reason choice; Opportunity Misqualified applies only when the prior stage was 0.'),
('Loss Reason Details','loss','The evidence-based explanation of the decision, competitive factors, gaps, lessons and action.','Distinguish customer-confirmed facts from internal interpretation.'),
('Competitor Lost To','competition','The actual competitive outcome at loss, including the permitted Not lost to competitor choice.','It is different from the incumbent list or all alternatives considered earlier.'),
('Competitor Detail (if Other)','competition','The company name required whenever Other is selected in Competitors or Competitor Lost To.','Use it for the company name, not a replacement for the loss explanation.'),
('Lost — Next Step Recommendation','loss','The appropriate follow-up recommended after the lost decision.','It captures a considered next action or disposition rather than leaving the team to infer what happens next.'),
('Deal Team Loss Report','loss','The restricted report due within two business days for a qualifying loss.','Qualifies at prior Stage ≥3 and amount >$1M, or prior Stage ≥2 and amount >$5M. Never post it to #win-wire.'),
('Invoice Reference / Invoice Date','invoice','Evidence recorded and reconciled when the financial invoice is issued.','Pending issuance does not prevent Stage 8 after full on-site delivery; financial Invoice Date is not the value-tracking baseline.'),
('Deployment Case Link','deployment','The connection to the coordinating PS deployment Case initiated at Stage 6, using confirmed existing Opportunity and Order relationships.','Avoid duplicate Cases on re-entry; deployment and value detail remain on the Case.'),
('Value Realization Plan','value-realization','The Case-based plan for validating the sales-defined operational and business outcomes, begun from Stage 6.','Case Scope of Work alone is not the value-validation plan.'),
('Target Value Realization Date','value-realization','The planned date for confirming customer value, maintained on the coordinating Case.','It is separate from delivery, installation and the final assessment date.'),
('Value Achieved?','value-realization','The final Case assessment: Yes for achieved and confirmed, No for assessed and not achieved, blank while pending.','No does not mean unmeasured; it requires the gap and agreed disposition.'),
('Value Realization Context','value-realization','The measured results, customer confirmation and evidence, or gap and disposition, supporting the Case value assessment.','Case closure alone does not supply this evidence.'),
('Value Outcome Confirmed Date','value-realization','The date of the final Yes/No value assessment on the Case.','It differs from deployment completion and Case closure.'),
('Value Tracking Start Date','time-to-value','The first verified Stage 8/on-site-delivery milestone preserved once on the coordinating Case.','Case creation, booking, invoice date, retries and reassignment do not replace or reset the start.'),
('Pre-pipeline','forecast','The sales forecast category for creation/Stage 0.','A seller-qualified opportunity saved directly in Stage 1 is Pipeline immediately.'),
('Pipeline','forecast','The sales forecast category for Stages 1–2.','It is derived from the permitted stage rather than independently maintained by the seller.'),
('Upside','forecast','The sales forecast category for Stages 3–4.','It does not replace the required technical and buyer-alignment evidence.'),
('Commit','forecast','The sales forecast category for Stages 5–6.','Won decision remains Commit until OM confirms booking.'),
('Won','forecast','The sales forecast category for Stages 7–8.','Deployment and value assessment continue without changing the original booked win.'),
('Loss','forecast','The sales forecast category for Closed lost.','An unrealized post-sales outcome does not convert a booked sale into a loss.'),
('Administrative outcomes','forecast','The existing Duplicate, Transacted-Internal Order and Transacted-Reference Opty dispositions retained with their current handling.','They are not additional sales stages or Closed lost outcomes.'),
]

TERM_TITLES = {
'source':'Opportunity Source','conversion':'Conversion tracking','sal-review':'SAL acceptance / rejection','challenge':'CHAMPS — Challenge','authority':'CHAMPS — Authority','money':'CHAMPS — Money','priority':'CHAMPS — Priority','stack':'CHAMPS — Stack / Storage','use-case':'Use Case','route':'Route to Market','pain':'Identify Pain','competition':'Competitors and status quo','technical-value':'Technical Value','champion':'Champion','criteria':'Decision Criteria','technical-outcome':'Technical Outcome','operational-value':'Operational Value','economic-buyer':'Economic Buyer','decision-process':'Decision Process','business-value':'Business Value','paper-process':'Paper Process','procurement':'Procurement evidence','won-decision':'Won decision','booking':'Booking confirmation','invoice':'Delivery-led Opportunity completion','loss':'Lost deal review','quoting':'Quoting','next-steps':'Next Steps and Close Date review','buying-committee':'Buying committee','poc':'POC — Proof of concept','risk':'Technical Deal Risk','enhancements':'Product enhancements','partner-accounts':'Associated accounts','fulfillment':'Transacting Partner','partner-credit':'Partner Contribution','nvidia':'NVIDIA Engagement','logistics':'Lead time and logistics','ipg':'IPG Process','win-wire':'Win wire','interviews':'Win/Loss interview eligibility','deployment':'Coordinating deployment Case','value-realization':'Value realization','time-to-value':'Time to Value','forecast':'Forecast Category (Sales)','deal-context':'Deal context and technical evidence'
}

TERM_EXAMPLES = {
'MQL — Marketing Qualified Lead':'A campaign contact reaches Marketing’s qualification threshold and receives MQL before a later opportunity creates SAL.',
'AQL — Agentic Qualified Lead':'PAX.AI qualifies the lab researcher as AQL; no MQL is invented for that episode.',
'SAL — Sales Accepted Lead':'The inbound opportunity is created in Validate: SAL is recorded while the assigned AE’s acceptance is still pending.',
'SQL — Sales Qualified Lead':'After acceptance and inbound CHAMPS are complete, the opportunity enters Discovery and records SQL.',
'Conversion Contact':'The researcher who originated the qualified opportunity is explicitly linked, even after other committee members join.',
'Opportunity Conversion Lifecycle':'A deal now in Procurement still shows SQL as its last conversion milestone.',
'Account Lifecycle Stage (ALS)':'A new opportunity begins in Validate for an existing customer; the Account is not downgraded to an earlier lifecycle.',
'Seller-self-qualified entry':'An assigned AE creates a self-qualified deal directly in Discovery, recording SAL and SQL, then completes CHAMPS before Solution design.',
'CHAMPS':'The inbound handoff includes the lab’s problem, decision influence, funding evidence, urgency and current storage environment.',
'Opportunity Owner / Assigned AE':'An AE takes responsibility for a BDR-origin deal; the BDR sourcing credit stays intact.',
'Primary SE':'The assigned SE leads workload validation while the AE coordinates the customer’s commercial decision.',
'Opportunity Type':'A contract extension is classified as Renewal; its applicable interview and logistics rules are reviewed accordingly.',
'Opportunity Name':'“Research Lab — AI Training Storage Expansion” identifies the customer and intended project.',
'Amount':'An early estimate is replaced by the synchronized total from the opportunity’s Primary Quote as the proposal develops.',
'Sourcing User':'The originating BDR is linked as Sourcing User even though an AE enters the opportunity.',
'Sourcing Campaign':'The original qualifying campaign remains linked after the opportunity changes owners.',
'Sourcing Partner':'The registering partner Account is retained as the sourcing reference on a partner-origin opportunity.',
'Indirect Route Type':'The confirmed reseller purchase uses Indirect plus the applicable supported subtype.',
'Additional Use Case Information':'AI training is the selected use case; the explanation identifies dataset preparation, researchers and the desired reduction in idle time.',
'Opportunity Contact Roles':'The architect and budget owner are linked as actual Salesforce Contacts with their supported buying roles.',
'Technical Win':'The SE confirms the selected configuration meets the customer evaluation criteria and links the supporting evidence.',
'Technical Loss':'The evaluated configuration fails a required integration criterion; that result does not permit Stage 4 entry.',
'Description':'The lab needs to reduce dataset preparation delays for a new research program using a validated storage configuration.',
'SharePoint Link':'The rich-text field links the current configuration, evaluation plan and technical results with clear descriptions.',
'Primary Quote':'The selected final proposal belongs to this opportunity and supplies its Amount and Products.',
'Quote Purpose':'A planning estimate is Budgetary even when the customer needs it urgently.',
'Timing Urgency':'An Urgent quote request states the customer approval deadline and why the standard timing would miss it.',
'Close Date':'An expected date changes when the buyer’s approval meeting moves; the booked date later locks at Closed won.',
'Next Step':'Friday: AE and director review the value case and confirm the procurement sequence.',
'SE Next Step':'Wednesday: SE and architect validate the migration requirement against the selected configuration.',
'Weekly review freshness':'The AE explicitly confirms the same next action and close date this week; no cosmetic text change is needed.',
'POC Required?':'The customer does not need a POC, so the team records an explicit No before Stage 3.',
'POC Status':'A required test remains Blocked; the opportunity cannot move beyond Stage 2 until it is Cancelled or Completed.',
'Technical Deal Risk Category':'A dependency in moving the customer’s data is categorized as Migration.',
'Technical Level of Risk':'The SE changes the assessment to Resolved after validation closes the tracked integration issue.',
'Association Engagement Status':'A former partner engagement is set Inactive while its involvement history is retained.',
'NVIDIA Engagement Status':'NVIDIA has an active association; the team uses the separately verified NVIDIA status rather than copying “Active.”',
'Partner-only':'The opportunity was created and owned solely by the partner/channel; a later ownership transfer does not rewrite that origin.',
'Partner-Led':'The first qualifying partner association occurs in Stage 2 and the original event is preserved.',
'Joint':'The first qualifying partner event occurs during Proposal / negotiate, Stage 4.',
'Partner contribution override':'Management corrects credit with an audited reason while the original automated classification remains traceable.',
'Requested Install Date':'The customer requests installation before its January program begins; actual completion has not yet occurred.',
'Estimated Shipping Date':'The Stage 5 package records the current shipping estimate, separately from the customer’s receipt request.',
'Requested Delivery Date':'The customer requests arrival on a day when its receiving dock is staffed.',
'Delivery Notes':'The plan identifies the receiving contact, site-access window and installation dependency.',
'IPG Finalized':'The SE finalizes and submits the applicable package, then records Completed before Stage 6.',
'PO Secured / PO Attachment':'The received PO is reconciled to the quote and attached through Salesforce Files.',
'Final Agreements Received':'The procurement package includes the final agreements rather than a draft still under review.',
'Order Review Status':'OM checks the approved booking criteria and evidence instead of assuming any populated status permits booking.',
'Sales Order Reference':'The booked opportunity points to the Order OM uses to reconcile partial receipts and later invoices.',
'Won Reason':'The customer confirms the selected solution best met its validated technical and business needs; the supporting detail is retained.',
'Incumbent Vendor(s)':'The lab currently uses vendor A while evaluating DDN and vendor B; incumbent and competitor information stay distinct.',
'Resources Engaged':'For an exactly $1M win, the AE names the internal account team and cross-functional contributors.',
'Deal Team Win Report':'A $2.1M win requires the additional report as well as the reviewed Win wire.',
'OK to Interview (Win/Loss)?':'The AE confirms that the Win/Loss team may approach the lab contact and selects Yes.',
'Contact for Win/Loss Interview':'The named customer participant is linked as a Salesforce Contact after eligibility is set to Yes.',
'WL Reason Cannot Approach':'When eligibility is No, the AE explains the specific relationship context preventing outreach.',
'Loss Reason':'A customer-confirmed budget withdrawal is recorded with the supported reason and an evidence-based explanation.',
'Loss Reason Details':'The note explains the customer decision, which factors were confirmed, the lesson and the recommended next action.',
'Competitor Lost To':'The project was cancelled without a vendor selection, so Not lost to competitor reflects the outcome.',
'Competitor Detail (if Other)':'A named competing company is entered when it is represented by Other in the competitor selection.',
'Lost — Next Step Recommendation':'Reconnect after the customer’s next funding review, with the relevant timing and context recorded.',
'Deal Team Loss Report':'A $1.4M loss from Stage 3 triggers the restricted report due within two business days.',
'Invoice Reference / Invoice Date':'The full order is already delivered and the Opportunity is in Stage 8; OM adds the invoice evidence when issued.',
'Deployment Case Link':'The Stage 6 opportunity links to one coordinating Case covering installation and migration workstreams.',
'Value Realization Plan':'GSS plans how the customer will measure the agreed staging-time target against the original baseline.',
'Target Value Realization Date':'The customer and GSS plan a value assessment two weeks after the representative workload is running.',
'Value Achieved?':'The measurement is not complete, so the field stays blank; after a confirmed shortfall it becomes No with explanation.',
'Value Realization Context':'The assessment records measured staging time, customer confirmation and the comparison with the agreed target.',
'Value Outcome Confirmed Date':'The final customer-supported assessment is recorded on October 24, separately from earlier installation completion.',
'Value Tracking Start Date':'Full on-site delivery is verified October 10; that original date remains the baseline after Case reassignment.',
'Pre-pipeline':'An inbound opportunity in Validate is Pre-pipeline while seller review is pending.',
'Pipeline':'An opportunity in Discovery or Solution design is Pipeline.',
'Upside':'The opportunity reaches Buyer alignment with the corresponding Upside sales forecast.',
'Commit':'A Stage 6 won decision remains Commit while OM completes booking review.',
'Won':'OM confirms Closed won; the category remains Won through Invoice and the continuing Case work.',
'Loss':'The opportunity is Closed lost with the actual decision date and the Loss sales forecast.',
'Administrative outcomes':'A duplicate is handled through the retained administrative disposition rather than being reported as a lost customer decision.'
}

# Compact dictionary copy; process detail stays in the system and courses.
DEFINITION_TEXT = {
'source':'The origin of an opportunity, supported by the credited sourcing user, campaign or partner. It stays separate from the current owner and transaction route.',
'conversion':'The progression from Contact qualification to opportunity creation and sales qualification. MQL and AQL are separate entry paths; SAL is recorded at creation and SQL on first entry to Discovery.',
'sal-review':'The assigned seller’s decision to accept or reject an opportunity handoff. This decision is separate from the SAL milestone recorded at opportunity creation.',
'challenge':'The customer’s initial problem or unmet need, supported by customer evidence.',
'authority':'The contact’s role and influence in the buying decision, including access to those who approve the purchase.',
'money':'Evidence of the customer’s funding, funding access and ability to pay for the project.',
'priority':'The urgency and business importance of solving the customer’s problem, including the consequence of delay.',
'stack':'The customer’s current technical environment, workloads and relevant storage requirements.',
'use-case':'The activity or workflow the customer intends to support with the solution, and the outcome they want to achieve.',
'route':'How the sale will transact: Direct or Indirect. Indirect requires an applicable Indirect Route Type.',
'pain':'The customer’s problem and its validated impact on people, operations or business results. It develops the initial CHAMPS Challenge into a clear reason to act.',
'competition':'The alternatives the customer is considering, including other vendors and keeping the current approach.',
'technical-value':'How the proposed solution meets the customer’s technical requirements, including the configuration and evidence supporting its fit.',
'champion':'An internal customer advocate whose influence and support are demonstrated through actions that help the opportunity progress.',
'criteria':'The requirements the customer uses to evaluate and compare solutions.',
'technical-outcome':'The result of technical evaluation: Technical Win or Technical Loss. Technical Win is required before Stage 4.',
'operational-value':'The measurable improvement the solution is expected to deliver to the customer’s operations, expressed as a baseline, target and measurement approach.',
'economic-buyer':'The person who controls the budget for the purchase.',
'decision-process':'The steps, participants and timing through which the customer selects a solution.',
'business-value':'The quantified economic justification for the purchase, based on customer-validated benefits, costs and assumptions.',
'paper-process':'The legal, procurement, signature and purchase-order steps required to complete the transaction.',
'procurement':'The documents and confirmations needed to complete procurement, including the PO, final agreements, IPG disposition and applicable delivery information.',
'won-decision':'The customer’s decision to buy, recorded before Order Management confirms the booked order. The sales forecast remains Commit.',
'booking':'Order Management’s confirmation that the order is reconciled and booked. It establishes Closed won and locks booked facts and Close Date.',
'invoice':'Completion of the Opportunity at Stage 8 when the full in-scope order is verified as delivered on site. Financial invoicing, deployment and value assessment are separate events.',
'loss':'An assessment of why the customer did not buy, what the team learned and what follow-up is appropriate.',
'quoting':'The creation and revision of commercial proposals in CPQ, permitted during Stages 2–5.',
'next-steps':'The weekly confirmation of the next customer action and expected Close Date for open opportunities in Stages 1–6. The SE reviews its technical action separately.',
'buying-committee':'The people involved in evaluating, influencing, funding and approving the purchase, linked as Salesforce Contacts with their opportunity roles.',
'poc':'A proof of concept: a scoped evaluation used to test technical requirements. A required POC must be Cancelled or Completed before Stage 3; completion alone does not establish a Technical Win.',
'risk':'A technical issue or uncertainty that could affect the opportunity, recorded with its category, severity, explanation and linked issue.',
'enhancements':'Requests for needed product capabilities, documented in Cases linked to the opportunity. A request is not a delivery commitment.',
'partner-accounts':'The organizations involved in an opportunity, with their roles, impact, contacts and engagement plans.',
'fulfillment':'The partner account responsible for fulfillment. It may differ from the sourcing partner and the actual ship-to destination.',
'partner-credit':'The classification of partner involvement based on channel ownership at creation and the earliest qualifying partner event. Automated credit freezes at booking.',
'nvidia':'NVIDIA’s involvement in an opportunity, recorded through its account-specific engagement plan and the Opportunity’s engagement summary and status.',
'logistics':'Planning that connects shipping, customer receipt and installation, including the dates, responsibilities and dependencies for each.',
'ipg':'The process for gathering, finalizing and submitting the IPG package during procurement and carrying it into the order and deployment handoff.',
'win-wire':'A manager-reviewed summary of why a deal was won, the customer value and the contributors. Above $1M, it is submitted to Enablement / #win-wire within two business days.',
'interviews':'Whether the Win/Loss team may approach a customer for feedback. Yes requires a Salesforce Contact; No requires a reason the team cannot approach.',
'deployment':'The Case that coordinates deployment scope, ownership, plans and workstreams, starting at Won decision and continuing after the Opportunity ends.',
'value-realization':'Confirmation that the customer achieved the agreed operational and business outcomes, supported by measured results and customer evidence.',
'time-to-value':'The number of days from first verified on-site delivery to confirmed value achievement. It is calculated on the coordinating Case only when Value Achieved? is Yes.',
'forecast':'The sales forecast classification derived from the Opportunity stage: Pre-pipeline, Pipeline, Upside, Commit, Won or Loss.',
'deal-context':'The customer, solution and business-need summary, supported by links to current technical documentation.',
 'term-sal-sales-accepted-lead':'The conversion milestone recorded when an opportunity is created. Despite its name, SAL does not itself confirm the assigned seller’s acceptance; that is a separate decision.',
 'term-value-achieved':'The Case’s value-assessment outcome: Yes means achieved and confirmed; No means assessed and not achieved; blank means the assessment is pending.',
 'term-nvidia-engagement-status':'The Opportunity-level status describing NVIDIA’s engagement when its association is active. The exact field and allowed choices remain to be confirmed; association Active/Inactive is a separate status.',
 'term-seller-self-qualified-entry':'Direct creation of a seller-qualified opportunity in Stage 1 by its assigned seller, recording auto-accepted SAL and SQL. CHAMPS is completed before Stage 2.',
 'stage-creation':'The capture of a new opportunity, its source, originating Contact and core deal information. Inbound intake starts in Validate; seller-self-qualified opportunities may start in Discovery.',
 'stage-s0':'The stage for reviewing an inbound handoff, assigning the seller and completing acceptance and CHAMPS qualification before Discovery.',
 'stage-s1':'The stage for establishing business fit, use case, buying roles and route to market. Entry records SQL; discovery is completed before Solution design.',
 'stage-s2':'The stage for evaluating technical fit through candidate configurations, supported by pain, criteria, competitor and champion evidence.',
 'stage-s3':'The stage for agreeing one configuration and aligning the technical outcome, operational value, Economic Buyer and Decision Process.',
 'stage-s4':'The stage for aligning the commercial proposal, quantified Business Value, Primary Quote and Paper Process.',
 'stage-s5':'The stage for completing the PO, final agreements, IPG disposition and applicable shipping and delivery information.',
 'stage-s6':'The customer’s won decision, followed by order review and deployment planning. The opportunity remains Commit until booking is confirmed.',
 'stage-s7':'The OM-confirmed booked order, with locked booked facts and Close Date. Fulfillment and deployment coordination continue.',
 'stage-s8':'The final Opportunity stage, reached at verified delivery of the complete in-scope order. Invoice evidence is captured when issued; deployment and value work continue on the Case.',
 'stage-lost':'The outcome recording the customer’s decision not to buy, with the reason, competitive outcome, learning and follow-up.',
 'stage-post':'The delivery and validation of the customer’s agreed outcome, managed on the coordinating Case. It continues after Stage 8 rather than adding an Opportunity stage.'
}

# Examples are selective: concrete input or usage, not an extra explanation for every term.
DEFINITION_EXAMPLES = {
'source':'A BDR originates the deal and an AE takes ownership. The source remains BDR, with the originating BDR linked as Sourcing User.',
'challenge':'“Researchers wait overnight for datasets to be ready for analysis.”',
'authority':'“The architect recommends the design; the infrastructure director approves the budget.”',
'money':'“Estimated budget: $400,000. Funding approval depends on acceptance of the business case.”',
'priority':'“The platform is needed before the January research program; delay would postpone researcher onboarding.”',
'stack':'“Shared storage supports ingest and model training; the reported ingest bottleneck needs validation.”',
'use-case':'AI model training that requires faster dataset preparation between experiments.',
'route':'A Marketing-origin opportunity transacts through a reseller: source is Marketing; route is Indirect.',
'pain':'“Staging delays cause missed processing windows and repeated rescheduling each week.”',
'champion':'The architect arranges access to the budget owner and helps validate the internal business case.',
'criteria':'The solution must meet the agreed workload performance, usable capacity and integration requirements.',
'operational-value':'“Reduce dataset staging from 8 hours to a 2-hour target, measured on the same representative dataset.”',
'business-value':'“Avoid $120,000 in annual operating costs against an $80,000 annual solution cost, using customer-validated assumptions.”',
'decision-process':'Technical review → director’s value review → steering committee selection.',
'paper-process':'Legal review → vendor onboarding → agreement signature → PO issuance.',
'risk':'“Migration dependency may delay launch. Category: Migration. Level: High. Linked issue contains the validation plan.”',
'time-to-value':'Delivery verified October 10; value confirmed October 24: Time to Value is 14 days.',
 'term-opportunity-name':'“Research Lab — AI Training Storage Expansion”',
 'term-next-step':'“Friday: AE and director review the business case and confirm the procurement sequence.”',
 'term-se-next-step':'“Wednesday: SE and architect validate the migration requirement.”',
 'term-additional-use-case-information':'“Researchers need faster dataset preparation to reduce idle time between model-training experiments.”',
 'term-description':'“The lab needs to reduce dataset preparation delays for a new research program using a validated storage configuration.”',
 'term-quote-purpose':'Budgetary for a planning estimate; Best and Final for the final commercial proposal.',
 'term-timing-urgency':'“Urgent: proposal needed before the customer’s Friday funding-approval meeting.”',
 'term-delivery-notes':'“Receiving dock open weekdays 08:00–16:00. Confirm site access with the receiving contact before dispatch.”',
 'term-partner-led':'The first qualifying partner event occurs in Stage 2.',
 'term-joint':'The first qualifying partner event occurs in Stage 4.',
 'term-lost-next-step-recommendation':'“Reconnect after the customer’s next funding review in January.”',
 'term-value-realization-context':'“Customer measured 2-hour staging against the original 8-hour baseline and confirmed the agreed target was achieved.”'
}
DEFINITION_TEXT.update({
 'term-account-lifecycle-stage-als':'The account’s current position in the customer lifecycle.',
 'term-administrative-outcomes':'Dispositions for records such as duplicates and internal or reference transactions, separate from sales stages and Closed lost.',
 'term-amount':'The monetary value of the opportunity. Once a Primary Quote is selected, it supplies the quoted value.',
 'term-additional-use-case-information':'The details of the customer’s workload, context and intended outcome behind the selected Use Case.',
 'term-opportunity-conversion-lifecycle':'The opportunity’s last conversion milestone: SAL at creation or SQL on entry to Discovery. It is separate from the sales stage.',
 'term-opportunity-owner-assigned-ae':'The seller accountable for the opportunity.',
 'term-primary-se':'The Sales Engineering lead responsible for technical discovery and solution work.',
 'term-opportunity-type':'The sales motion: New Business, Existing Business, Renewal, Internal Transfer or Non-Revenue.',
 'term-opportunity-name':'The name identifying the customer opportunity or project.',
 'term-sourcing-user':'The person credited with originating a Direct or BDR opportunity.',
 'term-sourcing-campaign':'The campaign credited with originating a Marketing opportunity.',
 'term-sourcing-partner':'The partner account credited with originating the opportunity.',
 'term-indirect-route-type':'The specific purchasing motion used when Route to Market is Indirect.',
 'term-opportunity-contact-roles':'The roles assigned to customer Contacts involved in the opportunity’s buying decision.',
 'term-sharepoint-link':'Links to the technical documentation supporting the opportunity.',
 'term-primary-quote':'The selected CPQ quote that supplies the opportunity’s quoted Amount and Products.',
 'term-weekly-review-freshness':'How recently the AE confirmed the next customer action and expected Close Date, or the SE confirmed its technical next action.',
 'term-poc-required':'The Yes/No decision on whether a proof of concept is needed for the opportunity.',
 'term-poc-status':'The current state of the proof of concept. A required POC must be Cancelled or Completed before Stage 3.',
 'term-technical-deal-risk-category':'The type of technical risk: Parts, Software, System, Expertise, Timeline, Integration, Migration, Engineering or Support.',
 'term-technical-level-of-risk':'The severity or resolution of a technical risk: High, Medium, Low or Resolved.',
 'term-nvidia-engagement-status':'The Opportunity-level status of NVIDIA’s engagement, separate from the association’s Active/Inactive status.',
 'term-partner-contribution-override':'A management-approved correction to partner-contribution reporting, supported by a recorded reason.',
 'term-requested-install-date':'The date the customer wants installation to take place.',
 'term-estimated-shipping-date':'The date the order is expected to ship.',
 'term-requested-delivery-date':'The date the customer wants the order to arrive.',
 'term-delivery-notes':'Instructions and context for shipping, receiving and deployment.',
 'term-ipg-finalized':'The IPG disposition: Completed or explicitly Not Required.',
 'term-po-secured-po-attachment':'Confirmation that the purchase order has been received, with the supporting PO document attached.',
 'term-final-agreements-received':'Confirmation that the final agreements needed to complete procurement have been received.',
 'term-order-review-status':'The current status of Order Management’s review and processing of the order.',
 'term-sales-order-reference':'The reference connecting the opportunity to its booked sales order.',
 'term-resources-engaged':'The internal account-team and cross-functional contributors to the win, recorded for wins of $1M or more.',
 'term-contact-for-win-loss-interview':'The customer Contact the Win/Loss team may approach when interview eligibility is Yes.',
 'term-wl-reason-cannot-approach':'The reason the Win/Loss team cannot approach the customer for feedback when interview eligibility is No.',
 'term-loss-reason':'The specific reason the customer did not buy.',
 'term-loss-reason-details':'The explanation and evidence behind the loss, including the customer’s decision, relevant factors and lessons.',
 'term-lost-next-step-recommendation':'The recommended follow-up after the opportunity is lost.',
 'term-deployment-case-link':'The link to the Case coordinating the opportunity’s deployment.',
 'term-target-value-realization-date':'The planned date for confirming that the customer has achieved the agreed value.',
 'term-value-realization-context':'The measured results and customer evidence supporting the value assessment, or the gap and agreed action if value was not achieved.',
 'term-value-outcome-confirmed-date':'The date of the final Yes/No assessment of customer value.',
 'term-value-tracking-start-date':'The first verified on-site delivery date used as the starting point for measuring Time to Value.'
})
