"""Plain-language implementation summaries; full rules remain in the process sections."""

# ID | Requirement statement | Acceptance criteria | Rev Ops refinement notes
COPY = '''
2|Keep the sales forecast category aligned with the deal’s stage so pipeline reporting stays consistent.|Stage 0 is Pre-pipeline; 1–2 Pipeline; 3–4 Upside; 5–6 Commit; 7–8 Won; losses show Loss. Valid direct Stage 1 creation starts in Pipeline.|Reuse Forecast Category (Sales). Standard Salesforce forecast fields remain separate.
3|Give every inbound deal an accountable seller and a recorded acceptance decision before it enters qualified pipeline.|Inbound deals advance only after assignment, acceptance and qualification. Assigned sellers can still create self-qualified deals directly in Stage 1.|Keep SAL creation separate from seller acceptance. Opportunities remain owned by a user.
4|Apply CHAMPS consistently so every deal meets the qualification standard for its intake path.|Inbound deals complete all five CHAMPS answers before Stage 1; seller-self-qualified deals complete them before Stage 2. Reassignment does not change the rule.|Reuse the existing CHAMPS fields and preserve the original intake path.
5|Require complete discovery, accountable AE/SE owners and buying contacts before solution design.|Stage 2 requires the discovery inputs, CHAMPS, Route to Market, AE/Primary SE and at least one Contact Role.|The originating Contact is identified at creation; buying roles develop during discovery.
6|Support early budget estimates while keeping firm proposals and later quote changes controlled.|Allow controlled Budgetary quoting in Stages 0–1 and regular quoting in 2–5. Stage 6 corrections return to 5; booked deals stay protected.|Reuse existing CPQ and Primary Quote synchronization. See Quoting for release requirements.
7|Require documented customer pain, technical fit and evaluation evidence before buyer alignment.|Stage 3 requires the Stage 2 technical inputs and a POC decision. A required POC must be Completed or Cancelled.|Keep the existing Description and POC controls; update only the missing requirements.
8|Make POC progress visible and prevent unresolved evaluations from moving forward.|If POC Required? is Yes, progression beyond Stage 2 requires Completed or Cancelled. If No, a POC is unnecessary. Stage skips follow the same rule.|Add POC Status and POC Updates; retain existing POC Required? and POC Engagement.
9|Confirm customer preference for DDN and one agreed configuration before proposal and negotiation.|Stage 4 requires Technical Win, the selected configuration, Operational Value, Economic Buyer and Decision Process. In Progress cannot pass.|Technical Win requires customer-confirmed preference; technical fit or a completed POC alone is insufficient.
10|Build a complete business and purchasing case before procurement.|Stage 5 requires Business Value, a Primary Quote, Paper Process and Requested Install Date.|Move Paper Process into Stage 4; reuse the existing quote process.
11|Complete procurement and delivery requirements before handing a won decision to Order Management.|Stage 6 requires shipping/delivery requests, IPG disposition, secured PO and its file, final agreements and delivery instructions.|Reuse existing IPG and file controls. A PO reference alone is insufficient.
13|Give OM a reconciled order and an agreed GSS logistics plan before booking.|Only authorized OM can move 6 → 7 after reconciliation. Booked facts stay protected while authorized delivery and invoice-reference updates remain possible.|Start deployment planning at Stage 6. Protect booked values without blocking post-booking work.
15|Complete the sales opportunity when all applicable booked items are received on site.|OM moves 7 → 8 on verified complete receipt; partial delivery stays at 7. Pending financial invoicing does not block completion.|Keep the Invoice stage label. Continue invoice reconciliation on the Order and deployment on the Case.
17|Start deployment planning at the won decision with one coordinating PS Case.|Stage 6 creates or links the Case. Re-entry reuses it, and failed transitions leave no duplicate or orphan Case. OM/GSS planning is ready before booking.|Reuse existing Case relationships; confirm the applicable process for deals without physical delivery.
18|Track whether customers achieve the promised value after purchase.|The PS Case captures the plan, target date, outcome, evidence and Time to Value. Post-sale assessment does not hold open or reopen the Opportunity.|GSS owns the assessment. Reuse sales-defined Operational Value and Business Value.
19|Keep AE and SE next actions current and make stale deals visible.|Open Stage 1–6 deals show separate weekly AE/SE reviews and are flagged after seven days without review. Booked Close Date remains protected.|A review can confirm an unchanged action. Unrelated record edits do not refresh it.
20|Give Sales Engineering and Product a clear way to manage deal-related feature requests.|Feature requests created in Stages 2–5 have a linked Case, title and description. Existing technical-risk tracking continues.|Reuse Cases and the existing risk process; a request is not a roadmap commitment.
21|Show every account’s role in a deal, including partners, end customers and other contributors.|Associated accounts records capture the account, primary role, classification, engagement plan, contacts and status while preserving existing relationships.|Extend Partner Opportunity Influence and reuse its existing fields where specified.
22|Base partner credit on documented origin and the first qualifying partner involvement.|Qualifying associations and approved registrations produce the defined contribution category. Credit freezes at booking; later changes do not rewrite it.|Move the trigger from Primary Partner to Associated accounts. Retain audited management overrides.
23|Keep NVIDIA engagement information tied to its actual involvement in the deal.|An active NVIDIA association triggers the relevant engagement requirements. NVIDIA account plans and next steps sit on that association.|Reuse the existing Opportunity engagement fields; avoid duplicate capture.
24|Capture useful win evidence and deliver the right win notifications.|Stage 6 applies the agreed win, recognition and interview requirements. Notifications follow the Win/Loss guide without duplicates.|Check the existing Win/Loss rollout before adding fields or automation.
25|Capture why a deal was lost and the next action without forcing irrelevant competitor answers.|Loss reason, explanation and next action are required. The three approved reasons allow blank competition; selecting Other still requires detail. Interview rules apply separately.|Competitor exemptions: Opportunity Misqualified, Project Cancelled / Budget Lost, No Decision / Went Dark. Misqualification applies only from Stage 0.
26|Remove unnecessary legacy prompts and consolidate win justification into Business Value.|Removed prompts no longer block progression. Optional context and historical values remain available.|Follow the field tables for the exact moves and removals.
30|Rename Primary Partner to Transacting Partner once it no longer drives source attribution.|The new label is applied after Associated accounts and the replacement attribution rules are working; existing relationships and history remain intact.|Complete the attribution dependency before the rename.
32|Preserve a readable history of POC progress.|Each POC update retains its full prior text, author and time.|Confirm history can retain the complete text; use a dated log if needed.
33|Use consistent win/loss reasons and vendor information to improve analysis.|Won Reason, Loss Reason, competitors and incumbent capture follow the approved guide, with historical values preserved.|Confirm the shared competitor taxonomy and reuse fields already delivered by the Win/Loss rollout.
34|Capture whether customers can be approached for feedback, asking only for relevant details.|For New/Existing/Renewal, eligibility is required at win/loss except Stage 0 misqualification. Yes requires a Contact; No requires a reason; an exempt blank answer requires neither.|Reuse the Win/Loss fields. Budget-lost and went-dark losses still require eligibility.
35|Send win/loss information to the right people at the agreed time.|Notifications meet the guide’s thresholds, recipients and deadlines, occur once per event, and keep restricted loss reports out of the win channel.|Check what the existing rollout already delivers before adding automation.
104|Capture verified deal origin at creation so source credit is reliable.|Direct/BDR requires Sourcing User; Marketing requires Sourcing Campaign; Partner requires Sourcing Partner. A blank source or missing applicable reference blocks creation.|Use the originating person, campaign or partner, rather than the current owner or integration user.
109|Bring Marketing and AI qualification into a consistent Contact lifecycle.|MAP records MQL and PAX.AI records AQL against the correct Contact. Repeated or late events do not duplicate credit or downgrade lifecycle status.|MQL and AQL are separate qualification paths. Confirm source-system mappings.
110|Track SAL and SQL against the originating Contact so conversion reporting reflects genuine qualification.|Creation records SAL. First qualified entry to Stages 1–8 records SQL, including valid skips. A valid 0 → 4 records SQL and Pipeline Date while Stage 1 Date stays blank.|Preserve each deal’s conversion history and existing customer status. Re-entry must not duplicate SQL.
111|Put SAL review in Validate so sellers can clearly accept or reject inbound handoffs.|Acceptance/rejection records the decision and required dates or notes. Pending or rejected inbound deals cannot enter qualified pipeline.|Reuse existing SAL controls and confirm what their current date fields mean.
112|Identify whether a quote is an estimate or a final commercial proposal.|Every CPQ Quote has Quote Purpose set to Budgetary or Best and Final, with the appropriate release requirements enforced.|Add this field to the Quote, not the Opportunity.
113|Make urgent quote requests visible and explain why they need priority.|Timing Urgency defaults to Standard. Selecting Urgent requires an Urgency Reason.|Keep both fields on the CPQ Quote.
114|Let teams record available competitor pricing to support commercial decisions.|Competitor Pricing is optional on the CPQ Quote and explains what pricing visibility to capture.|Use the agreed help text; do not make competitor pricing a quoting prerequisite.
37|Record how the deal will transact, separately from who originated it.|Route to Market is Direct or Indirect. Indirect requires Resell/distribution, GSI, OEM, NCP or CSP; Direct requires no subtype.|Capture during discovery, or earlier for a Budgetary quote. CSP includes hyperscalers.
39|Allow deals to include more than one Product Type.|Users can select multiple existing Product Type values and historical selections remain available.|Keep the current choice list.
41|Make the primary GSS contact easy to find when assigned.|An optional Primary GSS user lookup appears in the Opportunity summary without blocking progression.|This identifies the contact; it does not replace deployment Case ownership.
96|Calculate partner contribution consistently from origin and the timing of partner involvement.|Apply Partner-only, Partner-Led, Joint or the existing no-partner category using the agreed rules. Freeze automated credit at booking; retain audited overrides.|Part of BR-SS-022. Preserve original involvement evidence through ownership and stage changes.
43|Rename Why DDN to Identify Pain to capture validated customer problems in Stage 2.|Identify Pain is available at Stage 2 with existing Why DDN history retained.|Keep CHAMPS Challenge as a separate qualification answer.
44|Rename SE User to Primary SE so technical accountability is clear.|Primary SE identifies the assigned sales engineer alongside the AE, with existing assignments retained.|Reuse the existing user field.
45|Rename Solution to Technical Value and capture the technical case for DDN.|Stage 2 records technical fit and configurations; Stage 3 identifies one selected configuration. Existing content remains available.|Reuse the existing Solution field.
46|Capture the operational improvement the customer expects from DDN.|Operational Value records outcomes, baseline, target and measurement expectations in Stage 3.|Confirm a suitable reuse candidate or add the field; Why DDN remains Identify Pain.
47|Rename Economic Justification to Business Value and connect the business case to the win.|Stage 4 captures quantified business value; Stage 6 adds win detail and ROI or cost-saving evidence. Existing history is retained.|Use the same field throughout the deal.
48|Move purchasing milestones into Stage 4 as Paper Process.|Paper Process covers legal, procurement, signatures and PO steps before Stage 5.|Rename and reuse Procurement (Close Plan).
49|Make technical-document links easy to identify in Stage 2.|SharePoint Link replaces the Sharepoint Links label while retaining the existing rich text and links.|This is a label and placement change.
50|Make IPG completion explicit before the won-decision handoff.|IPG Finalized requires Completed or Not Required before Stage 6.|Rename the existing IPG Finalized and submitted field; keep its choices.
51|Clarify the label for the sales engineer’s next actions.|Sales Engineer Next Steps replaces SE Next Steps with existing content retained.|Weekly review evidence is covered by BR-SS-019.
52|Identify the economic decision-maker during buyer alignment.|Economic Buyer appears in Stage 3 with the existing Budget holder content retained.|Rename and move the existing text field; no new lookup is needed.
97|Capture the actual winning competitor only when relevant to the loss.|The three approved noncompetitive reasons allow a blank Competitor Lost To. Other reasons require it; selecting Other always requires detail.|Align with the approved competitor list. Retain Not lost to competitor and leave membership validation off at launch.
53|Capture the requested installation date early enough to plan delivery.|Requested Install Date is captured in Stage 4 and remains distinct from actual installation completion.|Confirm applicability for non-shipping deals with OM/GSS; do not invent dates.
54|Capture Sales’ shipping estimate before the order is finalized.|Estimated Shipping Date is maintained in Stage 5 and remains separate from later Order shipping commitments.|Keep the original estimate. Confirm applicability for non-shipping deals with OM/GSS.
55|Carry the customer’s delivery request from the deal into the order handoff.|Requested Delivery Date is captured in Stage 5 and reconciled with the existing Order date.|Reuse the Order field. Confirm applicability for non-shipping deals with OM/GSS.
56|Rename PO Processing Status to Order Review Status to clarify booking readiness.|OM confirms order reconciliation before 6 → 7 using approved processing and exception states; a populated status alone does not permit booking.|RevOps and OM must agree how existing statuses map to booking decisions.
58|Start value tracking from verified customer receipt.|Value Tracking Start Date on the PS Case captures the first Stage 8 delivery milestone and remains unchanged on retries or reassignment.|Part of BR-SS-018. Use the delivery milestone, not the financial invoice date.
61|Give GSS a plan for confirming the value promised during the sale.|The PS Case records the value-validation plan from Stage 6 and supports assessment after delivery.|Part of BR-SS-018. Reference Operational Value and Business Value.
62|Set a clear target for confirming customer value.|Target Value Realization Date is recorded on the PS Case; changes retain an explanation.|Part of BR-SS-018. This does not delay Opportunity completion.
63|Distinguish pending, achieved and unmet customer value.|Value Achieved? stays blank while pending; a completed assessment records Yes or No on the PS Case.|Part of BR-SS-018. Final assessment is separate from Opportunity completion.
64|Explain the evidence behind the customer’s value outcome.|Value Realization Context records measured results and confirmation, or the gap and agreed action when value is not achieved.|Part of BR-SS-018. Keep the evidence on the PS Case.
65|Record when the value assessment was completed.|Value Outcome Confirmed Date records the final Yes/No assessment on the PS Case.|Part of BR-SS-018. This is separate from deployment completion and Case closure.
66|Measure how long customers take to achieve value after receipt.|Time to Value calculates days from the delivery milestone to confirmed achievement. Pending or No outcomes stay blank; the outcome cannot precede the start.|Part of BR-SS-018. Calculate on the PS Case without reopening the Opportunity.
67|Clarify the reference for the current deal’s sales order.|Sales Order Reference replaces Order No. and retains the existing order reference.|Keep Original SO# separate for original-order references.
68|Make the invoice reference clear without delaying delivery-led completion.|Invoice Reference replaces Invoice # and is required when issued. Pending invoicing does not block Stage 8.|Part of BR-SS-015. Continue invoice reconciliation on the Order.
69|Make the coordinating deployment Case visible from the deal.|Deployment Case Link reuses the existing PS Case relationship from Stage 6; re-entry does not create a duplicate Case.|Part of BR-SS-017. Confirm existing relationships and non-shipping applicability.
70|Capture whether the commercial route is Direct or Indirect.|Route to Market is recorded during discovery, or before an early quote; Indirect requires a route type.|Part of BR-SS-037. Keep route separate from source and partner credit.
71|Describe the indirect route without adding unnecessary questions to Direct deals.|Indirect Route Type is required only for Indirect: Resell/distribution, GSI, OEM, NCP or CSP. Previous selections remain in history when the route changes.|Part of BR-SS-037. CSP includes hyperscalers.
99|Capture a consistent reason for the customer’s decision to buy.|Won Reason is required on entry to Stage 6 and uses the agreed choices, with historical values preserved.|Use the Win/Loss guide taxonomy.
72|Identify the partner handling the commercial transaction.|Transacting Partner replaces Primary Partner after attribution changes are ready. Existing links remain, and OM verifies the actual shipping destination separately.|Keep transacting partner, originating partner and ship-to distinct.
74|Show POC progress and prevent unresolved required evaluations from advancing.|POC Status defaults to None. When a POC is required, only Completed or Cancelled permits progression beyond Stage 2, including skips.|Part of BR-SS-008. Keep the agreed POC status choices.
75|Capture short, traceable POC progress updates.|POC Updates accepts up to 255 characters and retains full prior updates with author and time.|Part of BR-SS-008; history is covered by BR-SS-032.
77|Allow any participating account to be linked to the deal.|Associated Account replaces Partner and supports partners, end customers and other accounts without losing existing links.|Reuse the existing Account lookup.
100|Make each account’s primary role in the deal clear.|Each association has one primary Role On Deal and one classification. Secondary contributions go in the plan without duplicating the association.|Extend the existing role choices; preserve Transacting and Influencer history.
78|Describe the type of account participating in the opportunity.|Each Associated Account has the agreed Account Classification, separate from its role in the deal.|Use the specified choices; CSP includes hyperscalers.
79|Capture how the associated account will contribute to the deal.|Association Description / Plan replaces Description (Influence), retaining existing narrative and engagement plans.|Explain Other role or classification selections here.
80|Make each associated account’s engagement status clear.|Association Engagement Status replaces Partner Stage (Influence), keeping the required Active/Inactive choices and history.|This changes the label, not the choice list.
81|Identify the sales contact for each participating account.|Association Sales Contact replaces Primary Contact (Partner), retaining existing Contact links.|Maintain the technical contact separately.
82|Identify the technical contact for each participating account.|Association Technical Contact replaces Technical Contact (Partner), retaining existing Contact links.|Reuse the existing Contact lookup.
84|Recognize the people who contributed to major wins.|Wins of at least $1M require Resources Engaged on entry to Stage 6.|Reuse the Win/Loss rollout field if already available.
85|Record the customer’s incumbent vendors to understand displacement.|Incumbent Vendor(s) is captured at Stage 6 using the aligned vendor list, or Not Applicable when there is no incumbent.|Confirm the shared taxonomy and reuse any existing rollout field.
86|Record whether the customer may be approached for win/loss feedback.|New/Existing/Renewal wins and losses require eligibility, except Stage 0 misqualification. A blank answer is permitted only under that exemption.|Reuse the rollout field. Budget-lost and went-dark losses still require eligibility.
87|Give the Win/Loss team a usable customer contact when outreach is allowed.|OK to Interview = Yes requires a linked Salesforce Contact; other answers do not require this field.|Reuse the rollout field; a free-text name is insufficient.
88|Explain why the Win/Loss team cannot approach the customer.|OK to Interview = No requires WL Reason Cannot Approach; other answers do not require this field.|Reuse the existing rollout field where available.
89|Use a clear, consistent reason for each loss.|Loss Reason replaces Reason Lost and is required at loss. Opportunity Misqualified is available only for losses from Stage 0.|Use the agreed choices without Other; keep competitor information separate.
90|Make each loss explanation useful for learning and follow-up.|Loss Reason Details replaces Lost Reason Explanation and is required at loss, with existing history retained.|Capture the supported decision, gaps, lessons and next action.
91|Identify competitors that are not in the standard list.|Competitor Detail (if Other) is required whenever Other is selected in Competitors or Competitor Lost To, including otherwise exempt losses.|Rename and reuse the existing detail field; preserve history.
101|Show when the AE last reviewed the next action and expected close date.|Next Step Reviewed At updates on an explicit AE review, even if values are unchanged. Unrelated edits do not refresh it.|Part of BR-SS-019. Review time is separate from Next Step Last Updated.
102|Show when the SE last reviewed the technical next action.|SE Next Step Reviewed At updates on an explicit SE review, even if the action is unchanged. Unrelated edits do not refresh it.|Part of BR-SS-019. Keep AE and SE reviews separate.
115|Add account segmentation and coverage context so teams know an account’s priority and responsible contacts.|Accounts support Tier 1/2/3, restricted RevOps Notes, partner account manager, technical lead and admin contact. Only the appropriate teams can maintain them.|Agree tier criteria and validate coverage owners before initial population. Admin Contact does not grant system rights.
116|Measure when qualified pipeline was first created and its value at that time.|First valid entry to Stages 1–8 captures Pipeline Date, entry Amount and currency once. A valid 0 → 4 matches Stage 4 Date; re-entry and later quotes preserve the snapshot.|Use one pipeline snapshot. Keep Created Date and actual stage-entry dates separate.
118|Clarify transacting and contact labels across partner relationships.|Transacting Partner, Association Sales Contact and Association Technical Contact replace the old labels with relationships and history preserved.|Complete attribution changes before renaming Primary Partner. Keep Associated accounts as the section name.
119|Make source and technical status choices consistent and easier to interpret.|Opportunity Source uses Direct/BDR/Marketing/Partner. Technical Outcome includes In Progress, which cannot pass the Technical Win gate. CSP includes hyperscalers.|Agree the historical source mapping and review ambiguous origins before conversion.
120|Give partner coverage owners access to relevant deals automatically.|Team membership requires both partner and geographic coverage. Coverage changes remove only the access they provided; other approved access remains.|Partner Ops resolves missing coverage. Team membership does not grant commercial or approval authority.
121|Keep managers and partner coverage informed before Direct-route pricing reaches the customer.|The relevant people are notified before pricing, including early Budgetary quotes. Missing coverage goes to Partner Ops, and duplicate notices are avoided.|This notification does not create a new approval gate; existing commercial approvals still apply.
122|Protect genuine source attribution and make unclear account roles explainable.|Registration does not change origin. Accepted Partner-source corrections require authorization and a reason. Other roles/classifications require an explanation.|Keep source, registration and transacting partner separate.
123|Allow useful early estimates without weakening technical or commercial standards.|Budgetary quotes can be released in 0–1 with required context and authority. Best and Final requires the documented technical and commercial gates.|Use the existing approval matrix. Early quoting does not qualify or advance the deal.
126|Use Tasks to record customer meetings, outcomes and accountable follow-up.|Meeting records distinguish scheduled, held and cancelled/no-show outcomes. Held meetings capture notes; follow-ups have owners and due dates. Meetings do not advance sales stages.|Reuse existing Task fields and access rules. Synergy supports voice follow-up creation; calendar sync remains outstanding.
130|Help sellers complete missing requirements while changing stage, instead of meeting an avoidable error.|The Update Stage flow shows missing inputs and responsible owners. Valid saves update evidence, stage and dates together; failed or cancelled saves leave them unchanged.|Keep the same gates on direct edits and integrations, including stage skips.
131|Record first entry to Stages 0–6 for reliable conversion and stage-timing analysis.|Successful entry stamps that stage’s date once. Skipped stages stay blank; re-entry does not reset dates. Failed or cancelled moves stamp nothing.|Use transition history for repeated visits; first-entry dates alone do not measure total time in a stage.
132|Protect the AE Next Steps history while letting sellers maintain their current next action.|Sellers edit Next Step; automation appends dated changes to read-only AE Next Steps. Existing entries remain, and unchanged values create no false history.|Reuse the existing log. Weekly review timestamps remain separate.
'''

SUMMARIES = {}
for line in COPY.strip().splitlines():
    number, requirement, acceptance, notes = line.split('|')
    number = int(number)
    assert number not in SUMMARIES, f'Duplicate summary: {number}'
    SUMMARIES[number] = (requirement, acceptance, notes)


def simplify(data):
    """Change only the three requested columns, retaining row order and IDs."""
    assert {int(r[1][-3:]) for r in data[1:]} == set(SUMMARIES), 'Summary coverage differs from requirements'
    result = [data[0][:]]
    for original in data[1:]:
        row = original[:]
        for column, value in zip((3, 8, 10), SUMMARIES[int(row[1][-3:])]):
            row[column] = value
        result.append(row)
    return result
